export const availableTags = [
  "trauma",
  "autistic",
  "ocd",
  "puberty discomfort",
  "got top surgery",
  "got bottom surgery",
  "internalised homophobia",
  "autogynephilia (AGP)",
  "started as non-binary",
  "escapism",
  "depression",
  "low self-esteem",
  "anxiety",
  "porn problem",
  "hated breasts",
  "benefited from non-affirming therapy",
  "eating disorder",
  "influenced online",
  "influenced by friends",
  "regrets transitioning",
  "doesn't regret transitioning",
  "trans kid",
  "took hormones",
  "took puberty blockers",
  "serious health complications",
  "now infertile",
  "body dysmorphia",
  "retransition",
  "benefited from psychedelic drugs",
  "became religious",
  "become non-religious",
  "only transitioned socially",
  "intersex",
  "asexual",
  "homosexual",
  "heterosexual",
  "bisexual",
  "sexuality changed",
  "suspicious account",
];

export const SankeyTags = [
  ['Male', 'Female'],
  ['homosexual', 'hetrosexual', 'bisexual', 'asexual'],
  ['transitioned before 18', 'transitioned after 18']
  ['took hormones', 'didnt take hormones (tag missing)'],
  ['Got top surgery', 'Got bottom surgery', 'socially transitioned only/ no surgery tag'],
  ['regrets transitioning', 'doesnt regret transitioning'],
];
