export const questionCategories = [
  {
    title: "Questions en vedette",
    description:
      "Les meilleures questions à poser aux personnes qui ont fait un détransition.",
    questions: [
      "Que signifie transgenre ?",
      "Les personnes transgenres ont-elles toujours existé ?",
      "Est-il vrai que seulement 1% des personnes font un détransition ?",
      "Les bloqueurs de puberté sont-ils réversibles ?",
      "Quelles preuves existent concernant les protocoles médicaux d'affirmation de genre ?",
      "Que signifie le terme « œuf » dans les communautés transgenres ?",
      "Quelles sont les implications du récit « né comme ça » ?",
      "Comment les labels non-binaires renforcent-ils les stéréotypes de genre traditionnels ?",
      "Quelle est la différence entre le sexe et le genre ?",
      "Qu'est-ce que la dysphorie de genre et quelles en sont les causes ?",
      "Pourquoi certaines personnes décident-elles de faire un détransition ?",
      "Comment les amis ou la famille peuvent-ils soutenir quelqu'un qui souhaite transitionner ?",
      "Comment les amis ou la famille peuvent-ils soutenir quelqu'un qui souhaite faire un détransition ?",
      "Est-il courant que les personnes en détransition regrettent leur transition ?",
      "Pourquoi certaines personnes décident-elles de refaire une transition après un détransition ?",
      "Que peuvent m'apprendre les récits de détransition, même si ma transition se passe bien jusqu'à présent ?",
      "Comment puis-je savoir si mes doutes sont juste des nerfs ou un signe que je devrais arrêter ?",
      "Pourquoi les récits transgenres sur les raisons pour lesquelles les gens font un détransition diffèrent-ils de ceux qui ont réellement fait un détransition ?",
      "Les personnes en détransition pensent-elles que la transition elle-même est mauvaise ?",
      "Quelles sont les fausses affirmations faites à propos des personnes transgenres ?",
      "Quelles sont les fausses affirmations faites à propos des personnes qui ont fait un détransition ?",
      "Quels signes précoces les personnes en détransition auraient-elles aimé remarquer plus tôt ?",
      "Le genre est-il une construction sociale ? Qu'est-ce que cela signifie ?",
      "Comment les mouvements féministes ont-ils historiquement perçu le concept de genre ?",
      "Comment la non-conformité de genre peut-elle réduire la pression pour se conformer aux rôles de genre ?",
      "Comment les personnes en détransition décrivent-elles le sentiment d'être « nées dans le mauvais corps » ?",
      "Qu'est-ce que les soins d'affirmation de genre et quels sont leurs objectifs ?",
      "Pourquoi les soins d'affirmation de genre sont-ils généralement la seule option dans la plupart des régions ?",
      "En quoi la thérapie d'exploration de genre diffère-t-elle des soins d'affirmation de genre ?",
      "Pourquoi certaines personnes n'aiment-elles pas le concept de thérapie d'exploration de genre, et pourquoi est-elle interdite dans certains endroits ?",
      "Les personnes en détransition pensent-elles que les soins d'affirmation de genre et les hormones devraient être interdits ?",
      "Les personnes en détransition regrettent-elles généralement les étapes médicales, sociales, ou les deux ?",
      "Qu'est-ce qu'un piège identitaire et comment les gens réalisent-ils généralement qu'ils y sont pris ?",
      "Où quelqu'un peut-il chercher un thérapeute offrant une exploration de genre ouverte et non directive ? Quels signaux d'alarme devrais-je surveiller ?",
      "Demander les pronoms aide-t-il ou nuit-il aux personnes non-conformes au genre ?",
      "Si une jeune fille aux cheveux courts se fait constamment demander ses pronoms, quelle est l'implication et comment cela la ferait-il se sentir ?",
      "Qu'est-ce que la culture de l'annulation et quels effets a-t-elle sur le discours de santé publique ?",
      "Les personnes en détransition voient-elles la transition comme ayant un point final ou comme un processus continu ?",
      "Pourquoi certaines adolescentes pourraient-elles éprouver de la détresse concernant le développement de leurs seins ?",
      "Comment les chambres d'écho en ligne peuvent-elles influencer la formation de l'identité ?",
      "Pourquoi les personnes en détransition rapportent-elles souvent le sentiment que leurs histoires et leurs voix sont réduites au silence dans les espaces trans et grand public ?",
      "Quels schémas démographiques sont visibles dans les références aux cliniques de genre ?",
      "Comment les identités queer contemporaines diffèrent-elles du mouvement LGB antérieur ?",
      "Que dit la recherche actuelle sur le chevauchement entre les traits du spectre autistique, la dysphorie de genre et les identités transgenres ?",
      "Pourquoi la dysphorie de genre n'est-elle plus classée comme un trouble mental dans le DSM-5 ?",
      "Comment la prévalence transgenre a-t-elle changé récemment et qu'est-ce qui pourrait l'expliquer ?",
    ],
  },
  {
    title: "Termes généraux",
    description: "Comprendre les concepts fondamentaux",
    questions: [
      "Qu'est-ce qu'un homme ?",
      "Qu'est-ce qu'une femme ?",
      "Qu'est-ce que le genre ?",
      "Qu'est-ce que la dysphorie de genre ?",
      "Qu'est-ce que l'identité transgenre ?",
      "Qu'est-ce que la transphobie ?",
      "Qu'est-ce que la culture de l'annulation ?",
      "Qu'est-ce que l'identité non-binaire ?",
      "Qu'est-ce que l'identité queer ?",
      "Qu'est-ce que la théorie queer ?",
      "Qu'est-ce que la personnalité ?",
      "En quoi la personnalité diffère-t-elle de l'identité de genre ?",
      "Qu'est-ce que la non-conformité de genre (GNC) ?",
      "Qu'est-ce que la conformité de genre ?",
      "Qu'est-ce que le détransition ?",
      "Qu'est-ce que la désistance ?",
      "Quels sont les pronoms et pourquoi sont-ils importants pour certains ?",
      "Que veulent dire les personnes transgenres lorsqu'elles parlent des « droits des trans » ?",
      "Pourquoi certaines personnes transgenres disent-elles « la mort avant le détransition » ?",
      "Quels facteurs sont considérés comme causant la dysphorie ?",
      "Qu'est-ce que la « bible de la dysphorie de genre » ?",
      "Quelles stratégies (médicales ou non médicales) aident les gens à gérer la dysphorie ?",
      "Les personnes intersexes sont-elles automatiquement transgenres ?",
      "Qu'est-ce que la fluidité de genre ?",
      "Que signifient AFAB et AMAB ?",
      "Qu'est-ce qu'une TERF ?",
      "Qu'est-ce que le deadnaming ?",
      "Qu'est-ce que le mégenrage ?",
      "Qu'est-ce qu'une personne cisgenre ?",
      "Qu'entend-on par sexe biologique ?",
      "Quelle est la différence entre la transition sociale et médicale ?",
    ],
  },
  {
    title: "La réalité médicale",
    description: "Santé, procédures et vérités biologiques",
    questions: [
      "Quels sont les effets indésirables de l'utilisation de testostérone chez les femmes ?",
      "Quels sont les effets indésirables de l'utilisation d'œstrogènes chez les hommes ?",
      "Quels changements physiologiques la testostérone peut-elle induire chez les femmes et quelles sont les limites ?",
      "Quels changements physiologiques les œstrogènes peuvent-ils induire chez les hommes et quelles sont les limites ?",
      "Qu'est-ce que la phalloplastie implique et quels sont les résultats typiques ?",
      "Qu'est-ce que la vaginoplastie implique et quels sont les résultats typiques ?",
      "Quels sont les différents types de chirurgie de vaginoplastie ?",
      "Comment quelqu'un devrait-il évaluer la poursuite versus l'arrêt des hormones ?",
      "Existe-t-il des différences mesurables dans les taux de diagnostic de dysphorie de genre entre les hommes et les femmes ?",
      "Que dit la recherche sur l'imagerie cérébrale à propos des cerveaux « masculins » versus « féminins » ?",
      "Comment la dysphorie de genre est-elle distinguée de la maladie mentale dans les manuels diagnostiques ?",
      "Qu'est-ce que l'atrophie vaginale et qu'est-ce qui la cause ?",
      "Quelles options de révision chirurgicale existent pour la vaginoplastie ou la phalloplastie ?",
      "Comment différents pays réglementent-ils le financement public des chirurgies de genre ?",
      "Quelles options existent pour la reconstruction thoracique après mastectomie ?",
      "Quels sont les bloqueurs de puberté et suspendent-ils vraiment la puberté ?",
      "Est-il vrai que les bloqueurs de puberté sont le même médicament utilisé pour castrer chimiquement les délinquants sexuels ?",
      "Quelles données de suivi à long terme existent pour l'utilisation d'hormones croisées ?",
      "Quelles sont les normes de soins WPATH et comment sont-elles développées ?",
      "Qu'est-ce que le Protocole néerlandais ?",
      "Qu'est-ce que la dysphorie de genre à début rapide (ROGD) et comment est-elle étudiée ?",
      "Quels sont les taux de regret rapportés pour les différentes chirurgies de genre ?",
      "À quoi ressemble la thérapie d'exploration de genre en pratique ?",
    ],
  },
  {
    title: "Société et culture",
    description:
      "Comment les croyances sur le genre interagissent avec le monde",
    questions: [
      "Quelles sont les implications du récit « né comme ça » ?",
      "Les identités de genre sont-elles un reconditionnement et un renforcement des stéréotypes sexistes ?",
      "Comment le féminisme mainstream a-t-il évolué au fil du temps pour accommoder les identités transgenres ?",
      "Comment la culture des pronoms peut-elle conduire à la surmédicalisation des enfants ?",
      "Quels sont les résultats documentés pour les enfants qui transitionnent socialement tôt ?",
      "Quels sont les liens entre le BDSM et les identités transgenres ?",
      "Comment le concept de genre a-t-il évolué historiquement ?",
      "Comment l'activisme transgenre a-t-il interagi avec l'activisme antérieur pour les droits des gays ?",
      "Comment les mantras ou slogans répétitifs affectent-ils la pensée critique dans n'importe quelle communauté ?",
      "Comment le discours contemporain sur le genre intersecte-t-il avec les identités gays et lesbiennes ?",
      "Qu'est-ce qui pourrait expliquer l'augmentation de l'identification non-binaire ?",
      "Quelles explications existent pour le risque élevé de suicide dans les populations transgenres ?",
      "Comment le risque de suicide perçu affecte-t-il le discours public sur la transition ?",
      "Que signifie « critique du genre » et en quoi cela diffère-t-il des vues trans-exclusionnaires ?",
      "Quel est le « débat des toilettes » et quelles preuves existent concernant les préjudices ou la sécurité ?",
      "Quels sont les principaux arguments dans la controverse sur la participation sportive ?",
      "Comment les écoles ont-elles géré les élèves questionnant leur genre dans différentes juridictions ?",
      "Que pensent les personnes en détransition des lectures de contes par des drag queens ?",
      "Que signifie l'expression « médicalisation des enfants non-conformes au genre » pour les critiques et pour les défenseurs ?",
    ],
  },
  {
    title: "Psychologie et identité",
    description: "Comprendre les aspects mentaux et émotionnels",
    questions: [
      "Quelqu'un peut-il être une femme sans être féminine, ou un homme sans être masculin ?",
      "Quel rôle les médias sociaux jouent-ils dans l'adoption d'identités de genre ?",
      "Quel est le cycle neurochimique de la validation ?",
      "Pourquoi les personnes autistes pourraient-elles être surreprésentées dans les cliniques de genre ?",
      "Qu'est-ce que la misogynie internalisée et comment pourrait-elle être liée à la détresse corporelle ?",
      "Qu'est-ce que l'homophobie internalisée ?",
      "Qu'est-ce que l'autogynéphilie et comment est-elle débattue dans la littérature ?",
      "Qu'est-ce que l'euphorie de genre ?",
      "L'adoption d'une identité transgenre peut-elle amplifier la dysphorie au lieu de la soulager ?",
      "Pourquoi la validation externe est-elle importante pour certaines personnes transgenres ?",
      "Quelle est la différence entre le trouble dysmorphique corporel et la dysphorie de genre ?",
      "Quels parallèles les cliniciens établissent-ils entre la dysphorie de genre et les troubles alimentaires ?",
      "Comment les antécédents de traumatisme pourraient-ils interagir avec la dysphorie de genre ?",
      "Quelles options non médicales existent pour gérer la dysphorie ?",
      "Que signifie « passer » et pourquoi cela peut-il devenir une obsession pour certaines personnes ?",
      "Comment les concepts jungiens d'anima/animus se rapportent-ils à l'identité de genre ?",
      "Qu'est-ce que le travail de l'ombre et peut-il être utilisé en thérapie ?",
    ],
  },
  {
    title: "Le parcours du détransition",
    description: "Guérison, soutien et retrouver son chemin",
    questions: [
      "Comment puis-je faire la paix avec les changements permanents que j'ai faits à mon corps ?",
      "J'ai l'impression que certaines personnes pensent que je suis juste « retournée dans le placard » et que je ne vis pas authentiquement",
      "Est-il vrai que la plupart des personnes en détransition finissent par refaire une transition ?",
      "Comment la transition et le détransition peuvent-ils tous deux faire partie du même parcours de guérison ?",
      "Où quelqu'un peut-il trouver des thérapeutes expérimentés dans le soutien au détransition ?",
      "Le détransition signifie-t-il que la transition originale était un échec ?",
      "La TCC ou la DBT ont-elles aidé les personnes en détransition à gérer la dysphorie ?",
      "Pourquoi certaines communautés transgenres découragent-elles la lecture des récits de détransition ?",
      "Quels groupes de soutien existent spécifiquement pour les personnes en détransition ?",
      "Comment quelqu'un peut-il faire son coming out (encore une fois) à sa famille en tant que personne en détransition ?",
      "Quelles sont les étapes courantes de deuil rapportées pendant le détransition ?",
      "Quel rôle les drogues psychédéliques ont-elles joué dans certains récits de détransition ?",
    ],
  },
  {
    title: "Biais académique et de recherche",
    description: "Remettre en question le récit dans les institutions",
    questions: [
      "Quelles préoccupations méthodologiques ont été soulevées concernant les principales enquêtes sur le détransition ?",
      "Pourquoi les chercheurs rapportent-ils des difficultés à obtenir des financements pour les études sur le détransition ?",
      "Les chercheurs qui s'identifient actuellement comme transgenres ont-ils un conflit d'intérêts ?",
      "Qu'était l'examen Cass et quelles recommandations a-t-il produites ?",
      "Qu'est-il arrivé à l'étude de 2018 de Lisa Littman sur le ROGD ?",
      "Qu'est-ce que l'examen de la clinique Tavistock et pourquoi a-t-il été commandité ?",
      "Comment la dysphorie de genre a-t-elle été reclassifiée entre le DSM-IV et le DSM-5 ?",
    ],
  },
  {
    title: "Perspectives controversées",
    description:
      "Perspectives de détransition que les militants du genre ne veulent vraiment pas que vous entendiez",
    questions: [
      "Qui fait de l'argent avec les soins d'affirmation de genre ?",
      "Quels facteurs structurels conduisent à la sous-représentation des histoires de détransition dans les médias grand public ?",
      "De quelles manières les systèmes de croyances sur le genre ressemblent-ils aux religions ou aux sectes ?",
      "Les écoles écartent-elles les parents lorsque les enfants prennent des décisions concernant leur identité de genre ?",
      "Pourquoi y a-t-il tant de ladyboys en Thaïlande ?",
      "Pourquoi l'Iran est-il un centre mondial pour les chirurgies de réassignation sexuelle ?",
    ],
  },
];
