/**
 * Turkish question categories and featured questions for detrans.ai
 * 
 * Cinsiyetle İlgili Terminoloji Notları (Gender-Related Terminology Notes):
 * - "Cinsiyet" = biyolojik cinsiyet (anatomi, kromozomlar, üreme, değiştirilemez özellikler)
 *   Note: In Turkish, "cinsiyet" can mean both sex and gender. Context determines meaning.
 * - "Toplumsal cinsiyet" = sosyal cinsiyet (roller, davranışlar, toplumun erkek ve kadınlar 
 *   için uygun gördüğü nitelikler)
 * - "Cinsiyet kimliği" = kendini erkek, kadın veya arada bir yerde hissetme hali
 * - "Cinsiyet uyumsuzluğu" = birinin biyolojik cinsiyetine dayalı toplumsal beklentilere
 *   uymayan şekilde davranması/kendini sunması
 * - "AFAB/AMAB" = doğumda kadın/erkek atandı (gözlemlenen biyolojik cinsiyete dayalı)
 *   Note: In Turkish, these are often explained as "doğumda kız/erkek olarak atandı"
 * - "Transgender/trans" = biyolojik cinsiyetinden farklı bir cinsiyet kimliğiyle tanınma
 * - "Detransition" = trans kimliğini bırakma ve/veya geçiş adımlarını geri alma
 * - "Desist/vazgeçme" = trans kimliğiyle tanımlanan ancak tıbbi müdahalede bulunmamış 
 *   birinin artık trans kimliğiyle tanımlanmaması
 * 
 * Önemli ayrım: Cinsiyet disforisi kavramı, biyolojik cinsiyet ve sosyal cinsiyetin farklı
 * olduğunu anlamaya dayanır. Cinsiyet uyumsuzluğu (stereotiplere uymama), cinsiyet kimliğinin
 * biyolojik cinsiyetten farklı olmasından farklıdır.
 */

export const questionCategories = [
  {
    title: "Öne Çıkan Sorular",
    description: "Detrans kişilere sorulacak en iyi sorular.",
    questions: [
      "Trans ne anlama gelir?",
      "Trans kişiler her zaman var mıydı?",
      "Gerçekten sadece %1'i detransition yapıyor mu?",
      "Puberte baskılayıcılar geri döndürülebilir mi?",
      "Cinsiyet onaylayıcı tıbbi protokoller için ne kanıtlar var?",
      "Trans topluluklarında 'yumurta' terimi ne anlama gelir?",
      "'Doğduğum gibi' anlatısının sonuçları nelerdir?",
      "Non-binary etiketler geleneksel cinsiyet kalıplarını nasır güçlendiriyor?",
      "Cinsiyet ve toplumsal cinsiyet arasındaki fark nedir?",
      "Cinsiyet disforisi nedir ve neye neden olabilir?",
      "Neden bazı kişiler detransition yapmaya karar verir?",
      "Arkadaşlar veya aile geçiş yapmak isteyen birini nasıl destekleyebilir?",
      "Arkadaşlar veya aile detransition yapmak isteyen birini nasıl destekleyebilir?",
      "Detrans kişiler geçiş yaptıklarına pişman olması yaygın mı?",
      "Neden bazı kişiler detransition sonrası yeniden geçiş yapmaya karar verir?",
      "Geçişim şu iyi gidiyor olsa bile, detrans hikayeleri bana ne öğretebilir?",
      "Şüpheler sadece sinirlerimden mi yoksa durmam gerektiğinin bir işareti mi, nasıl anlarım?",
      "İnsanların neden detransition yaptığına dair trans anlatıları, gerçekten detransition yapanların anlatılarından neden farklıdır?",
      "Detrans kişiler geçişin kendisinin kötü olduğunu düşünüyor mu?",
      "Trans kişiler hakkında yapılan yanlış iddialar nelerdir?",
      "Detransition yapan kişiler hakkında yapılan yanlış iddialar nelerdir?",
      "Detrans kişiler daha önce fark etmeyi diledikleri erken işaretler nelerdir?",
      "Toplumsal cinsiyet bir sosyal yapı mıdır? Bu ne anlama gelir?",
      "Feminist hareketler tarihsel olarak toplumsal cinsiyet kavramını nasıl görmüştür?",
      "Cinsiyet uyumsuzluğu cinsiyet rollerine uyma baskısını nasıl azaltabilir?",
      "Detrans kişiler 'yanlış bedende doğmuş' hissetmeyi nasıl tanımlar?",
      "Cinsiyet onaylayıcı bakım nedir ve hedefleri nelerdir?",
      "Neden cinsiyet onaylayıcı bakım çoğu bölgede genellikle tek seçenektir?",
      "Cinsiyet keşifçi terapi, cinsiyet onaylayıcı bakımdan nasıl farklıdır?",
      "Neden bazı kişiler cinsiyet keşifçi terapi kavramını sevmez ve neden bazı yerlerde yasaklanmıştır?",
      "Detrans kişiler cinsiyet onaylayıcı bakımın ve hormonların yasaklanması gerektiğini düşünüyor mu?",
      "Detrans kişiler genellikle tıbbi adımlara, sosyal adımlara veya her ikisine mi pişman olur?",
      "Kimlik tuzağı nedir ve insanlar tipik olarak içinde olduklarını nasıl fark eder?",
      "Açık uçlu, yönlendirici olmayan cinsiyet keşfi sunan bir terapisti nerede bulabilirim? Hangi kırmızı bayraklara dikkat etmeliyim?",
      "Zamir sormak cinsiyet uyumsuz kişilere yardım mı eder yoksa zarar mı verir?",
      "Kısa saçlı genç bir kıza sürekli zamirleri sorulursa, ima ne olur ve bu onu nasıl hissettirir?",
      "İptal kültürü nedir ve kamu sağlığı söylemi üzerinde ne etkileri vardır?",
      "Detrans kişiler geçişi bir bitiş noktası olan bir süreç mi yoksa devam eden bir süreç mi olarak görüyor?",
      "Neden bazı ergen kızlar meme gelişimi konusunda sıkıntı yaşayabilir?",
      "Çevrimiçi yankı odaları kimlik oluşumunu nasıl etkileyebilir?",
      "Neden detrans kişiler hikayelerinin ve seslerinin hem trans hem de ana akım alanlarda susturulduğunu hissettiklerini sıkça bildiriyor?",
      "Cinsiyet kliniklerine yönlendirmelerde hangi demografik kalıplar görülebilir?",
      "Çağdaş queer kimlikleri daha önceki LGB hareketinden nasıl farklıdır?",
      "Otizm spektrumu özellikleri, cinsiyet disforisi ve transgender kimlikler arasındaki örtüşme hakkında mevcut araştırma ne diyor?",
      "Neden cinsiyet disforisi artık DSM-5'te bir zihinsel bozukluk olarak sınıflandırılmıyor?",
      "Trans yaygınlığı son zamanlarda nasıl değişti ve bunu ne açıklayabilir?",
    ],
  },
  {
    title: "Genel Terimler",
    description: "Temel kavramları anlama",
    questions: [
      "Erkek nedir?",
      "Kadın nedir?",
      "Toplumsal cinsiyet nedir?",
      "Cinsiyet disforisi nedir?",
      "Transgender kimlik nedir?",
      "Transfobi nedir?",
      "İptal kültürü nedir?",
      "Non-binary kimlik nedir?",
      "Queer kimlik nedir?",
      "Queer teorisi nedir?",
      "Kişilik nedir?",
      "Kişilik cinsiyet kimliğinden nasıl farklıdır?",
      "Cinsiyet uyumsuzluğu (GNC) nedir?",
      "Cinsiyet uyumu nedir?",
      "Detransition nedir?",
      "Desisting/vazgeçme nedir?",
      "Zamirler nelerdir ve neden bazıları için önemlidir?",
      "Trans kişiler 'trans hakları'ndan bahsederken ne demek istiyor?",
      "Neden bazı trans kişiler 'detransition'dan önce ölüm' der?",
      "Disforiye neyin neden olduğu düşünülüyor?",
      "'Cinsiyet disforisi kitabı' nedir?",
      "Disforiyi yönetmeye yardımcı olan stratejiler (tıbbi veya tıbbi olmayan) nelerdir?",
      "İnterseks kişiler otomatik olarak trans mıdır?",
      "Cinsiyet akışkanlığı nedir?",
      "AFAB ve AMAB ne anlama gelir?",
      "TERF nedir?",
      "Ölü isimlendirme (deadnaming) nedir?",
      "Yanlış cinsiyetlendirme (misgendering) nedir?",
      "Cisgender kişi nedir?",
      "Biyolojik cinsiyet ne anlama gelir?",
      "Sosyal geçiş ve tıbbi geçiş arasındaki fark nedir?",
    ],
  },
  {
    title: "Tıbbi Gerçek",
    description: "Sağlık, prosedürler ve biyolojik gerçekler",
    questions: [
      "Kadınlarda testosteron kullanımının olumsuz etkileri nelerdir?",
      "Erkeklerde östrojen kullanımının olumsuz etkileri nelerdir?",
      "Testosteron kadınlarda hangi fizyolojik değişikliklere neden olabilir ve limitler nelerdir?",
      "Östrojen erkeklerde hangi fizyolojik değişikliklere neden olabilir ve limitler nelerdir?",
      "Falloplasti (penis oluşturma ameliyatı) neleri içerir ve tipik sonuçlar nelerdir?",
      "Vajinoplasti (vajina oluşturma ameliyatı) neleri içerir ve tipik sonuçlar nelerdir?",
      "Vajinoplasti ameliyatının farklı türleri nelerdir?",
      "Birisi hormonlara devam etme ve kesme arasında nasıl tartmalıdır?",
      "Erkekler ve kadınlar arasında cinsiyet disforisi teşhis oranlarında ölçülebilir farklar var mı?",
      "Beyin görüntüleme araştırmaları 'erkek' ve 'kadın' beyinleri hakkında ne söylüyor?",
      "Cinsiyet disforisi tanı kılavuzlarında zihinsel hastalıktan nasıl ayırt edilir?",
      "Vajinal atrofi nedir ve neye neden olur?",
      "Vajinoplasti veya falloplasti için hangi cerrahi revizyon seçenekleri var?",
      "Farklı ülkeler cinsiyet ameliyatları için kamu finansmanını nasıl düzenler?",
      "Mastektomi (göğüs aldırma) sonrası göğüs rekonstrüksiyonu için hangi seçenekler var?",
      "Puberte baskılayıcılar nedir ve gerçekten sadece puberteyi duraklatırlar mı?",
      "Puberte baskılayıcılarının cinsel suçluları kimyasal olarak hadım etmek için kullanılan ilaçla aynı olduğu doğru mu?",
      "Karşı cinsiyet hormonu kullanımı için uzun vadeli takip verileri nelerdir?",
      "WPATH Bakım Standartları nelerdir ve nasıl geliştirilir?",
      "Hollanda Protokolü nedir?",
      "Hızlı başlangıçlı cinsiyet disforisi (ROGD) nedir ve nasıl çalışılır?",
      "Çeşitli cinsiyet ameliyatları için bildirilen pişmanlık oranları nelerdir?",
      "Cinsiyet keşifçi terapi pratikte nasıl görünür?",
    ],
  },
  {
    title: "Toplum ve Kültür",
    description: "Cinsiyet inançları dünyayla nasıl etkileşir",
    questions: [
      "'Doğduğum gibi' anlatısının sonuçları nelerdir?",
      "Cinsiyet kimlikleri cinsiyetçi kalıpları yeniden paketliyor ve güçlendiriyor mu?",
      "Ana akım feminizm zaman içinde transgender kimlikleri barındırmak için nasıl değişti?",
      "Zamir kültürü çocukların aşırı tıbbi müdahalesine nasıl yol açabilir?",
      "Erken sosyal geçiş yapan çocuklar için belgelenmiş sonuçlar nelerdir?",
      "BDSM ve trans kimlikler arasındaki bağlantılar nelerdir?",
      "Toplumsal cinsiyet kavramı tarihsel olarak nasıl evrimleşti?",
      "Trans aktivizm daha önceki eşcinsel hakları aktivizmiyle nasıl etkileşti?",
      "Tekrarlayan mantralar veya sloganlar herhangi bir toplulukta eleştirel düşünceyi nasıl etkiler?",
      "Çağdaş cinsiyet söylemi eşcinsel ve lezbiyen kimliklerle nasıl kesişiyor?",
      "Non-binary tanımlanmasında artışı ne açıklayabilir?",
      "Trans popülasyonlarında yüksek intihar riskini açıklayan açıklamalar nelerdir?",
      "Algılanan intihar riski geçiş hakkındaki kamu söylemini nasıl etkiler?",
      "'Cinsiyet eleştireli' ne anlama gelir ve trans dışlayıcı görüşlerden nasıl farklıdır?",
      "'Banyo tartışması' nedir ve zarar veya güvenlik hakkında ne kanıtlar var?",
      "Spor katılımı tartışmasındaki ana argümanlar nelerdir?",
      "Okullar farklı yargı alanlarında cinsiyet sorgulayan öğrencileri nasıl ele aldı?",
      "Detrans kişiler drag queen hikaye anlatımı hakkında ne düşünüyor?",
      "'Cinsiyet uyumsuz çocukların tıbbi müdahalesi' ifadesi eleştirmenler ve savunucular için ne anlama gelir?",
    ],
  },
  {
    title: "Psikoloji ve Kimlik",
    description: "Zihinsel ve duygusal yönleri anlama",
    questions: [
      "Birisi kadınsız kadın veya erkeksiz erkek olabilir mi?",
      "Sosyal medya cinsiyet kimliklerinin benimsenmesinde ne rol oynar?",
      "Onayın nörokimyasal döngüsü nedir?",
      "Neden otistik kişiler cinsiyet kliniklerinde aşırı temsil edilebilir?",
      "İçselleştirilmiş kadın düşmanlığı nedir ve beden sıkıntısıyla nasıl ilişkilendirilebilir?",
      "İçselleştirilmiş homofobi nedir?",
      "Otoginefili nedir ve literatürde nasıl tartışılır?",
      "Cinsiyet öforisi nedir?",
      "Trans kimliği benimsemek disforiyi hafifletmek yerine artırabilir mi?",
      "Neden dış onay bazı trans kişiler için önemlidir?",
      "Vücut dismorfik bozukluğu ve cinsiyet disforisi arasındaki fark nedir?",
      "Klinisyenler cinsiyet disforisi ve yeme bozuklukları arasında hangi paralellikler çiziyor?",
      "Travma geçmişleri cinsiyet disforisiyle nasıl etkileşebilir?",
      "Disforiyi yönetmek için hangi tıbbi olmayan seçenekler var?",
      "'Geçmek' (passing) ne anlama gelir ve neden bazıları için bir takıntı haline gelebilir?",
      "Jungcu anima/animus kavramları cinsiyet kimliğiyle nasıl ilişkilidir?",
      "Gölge çalışması nedir ve terapide kullanılabilir mi?",
    ],
  },
  {
    title: "Detransition Yolculuğu",
    description: "İyileşme, destek ve geri dönüş yolunu bulma",
    questions: [
      "Bedenimde yaptığım kalıcı değişikliklerle nasıl barışabilirim?",
      "Bazı kişilerin benim sadece 'dolaba geri gittiğimi' ve otantik yaşamadığımı düşündüğünü hissediyorum",
      "Çoğu detrans kişinin yeniden geçiş yaptığı doğru mu?",
      "Geçiş ve detransition aynı iyileşme yolculuğunun parçası nasıl olabilir?",
      "Detransition desteğinde deneyimli terapistleri nerede bulabilirim?",
      "Detransition orijinal geçişin bir başarısızlık olduğu anlamına mı gelir?",
      "CBT veya DBT detrans kişilere disforiyi yönetmede yardımcı oldu mu?",
      "Neden bazı trans toplulukları detransition anlatılarını okumayı caydırıyor?",
      "Detransitioner'lar için özel olarak hangi destek grupları var?",
      "Birisi detransition yapan biri olarak aileye (tekrar) nasıl çıkabilir?",
      "Detransition sırasında bildirilen yaygın yas aşamaları nelerdir?",
      "Psikedelik ilaçlar bazı detrans hikayelerinde ne rol oynadı?",
    ],
  },
  {
    title: "Akademik ve Araştırma Önyargısı",
    description: "Kurumlardaki anlatıyı sorgulama",
    questions: [
      "Büyük detransition anketleri hakkında hangi metodolojik endişeler dile getirildi?",
      "Neden araştırmacılar detransition çalışmaları için finansman sağlamada zorluk bildiriyor?",
      "Şu anda trans kimliğiyle tanımlanan araştırmacıların çıkar çatışması var mı?",
      "Cass İncelemesi neydi ve hangi önerileri üretti?",
      "Lisa Littman'ın 2018 ROGD çalışmasına ne oldu?",
      "Tavistock klinik incelemesi nedir ve neden talep edildi?",
      "Cinsiyet disforisi DSM-IV ve DSM-5 arasında nasıl yeniden sınıflandırıldı?",
    ],
  },
  {
    title: "Tartışmalı Bakış Açıları",
    description:
      "Cinsiyet aktivistlerinin gerçekten duymanızı istemediği detrans bakış açıları",
    questions: [
      "Cinsiyet onaylayıcı bakımdan kim para kazanıyor?",
      "Ana akım medyada detransition hikayelerinin yetersiz temsil edilmesine ne yapısal faktörler yol açar?",
      "Cinsiyet inanç sistemleri hangi yönlerden dinlere veya kürtlere benziyor?",
      "Okullar çocuklar cinsiyet kimliği hakkında seçimler yaptığında ebeveynleri dışarıda mı bırakıyor?",
      "Tayland'da neden bu kadar çok ladyboy (kathoey) var?",
      "İran neden cinsiyet değiştirme ameliyatlarının küresel bir merkezi?",
    ],
  },
];
