/**
 * Portuguese question categories and featured questions for detrans.ai
 */

export const questionCategories = [
  {
    title: "Perguntas em Destaque",
    description: "As melhores perguntas para fazer a pessoas que fizeram detransição.",
    questions: [
      "O que significa trans?",
      "Pessoas trans sempre existiram?",
      "É verdade que apenas 1% fazem detransição?",
      "Bloqueadores de puberdade são reversíveis?",
      "Que evidências existem para protocolos médicos de afirmação de gênero?",
      "O que significa o termo 'ovo' em comunidades trans?",
      "Quais são as implicações da narrativa 'nascido assim'?",
      "Como rótulos não-binários reforçam estereótipos de gênero tradicionais?",
      "Qual é a diferença entre sexo e gênero?",
      "O que é disforia de gênero e o que pode causá-la?",
      "Por que algumas pessoas decidem fazer detransição?",
      "Como amigos ou familiares podem apoiar alguém que quer fazer transição?",
      "Como amigos ou familiares podem apoiar alguém que quer fazer detransição?",
      "É comum pessoas que fizeram detransição se arrependerem de ter feito transição?",
      "Por que algumas pessoas decidem fazer retransição após a detransição?",
      "O que histórias de detransição podem me ensinar, mesmo se minha transição estiver indo bem até agora?",
      "Como eu saberia se dúvidas são apenas nervosismo ou um sinal de que devo parar?",
      "Por que narrativas trans sobre por que pessoas fazem detransição diferem daquelas que realmente fizeram detransição?",
      "Pessoas que fizeram detransição acham que a transição em si é ruim?",
      "Quais são algumas afirmações falsas feitas sobre pessoas transgênero?",
      "Quais são algumas afirmações falsas feitas sobre pessoas que fizeram detransição?",
      "Quais sinais iniciais pessoas que fizeram detransição gostariam de ter notado mais cedo?",
      "Gênero é uma construção social? O que isso significa?",
      "Como movimentos feministas historicamente viram o conceito de gênero?",
      "Como não-conformidade de gênero pode reduzir a pressão para conformar-se com papéis de gênero?",
      "Como pessoas que fizeram detransição descrevem a sensação de ter 'nascido no corpo errado'?",
      "O que é cuidado de afirmação de gênero e quais são seus objetivos?",
      "Por que cuidado de afirmação de gênero é geralmente a única opção na maioria das regiões?",
      "Como terapia exploratória de gênero difere do cuidado de afirmação de gênero?",
      "Por que algumas pessoas não gostam do conceito de terapia exploratória de gênero, e por que ela é proibida em alguns lugares?",
      "Pessoas que fizeram detransição acham que cuidado de afirmação de gênero e hormônios devem ser proibidos?",
      "Pessoas que fizeram detransição geralmente se arrependem de passos médicos, sociais, ou ambos?",
      "O que é uma armadilha de identidade e como pessoas tipicamente percebem que estão em uma?",
      "Onde alguém pode procurar um terapeuta que oferece exploração de gênero aberta e não-diretiva? Que sinais de alerta devo ficar atento?",
      "Perguntar por pronomes ajuda ou prejudica pessoas não-conformes com gênero?",
      "Se uma jovem garota com cabelo curto está constantemente sendo perguntada sobre seus pronomes, qual é a implicação e como isso a faria sentir?",
      "O que é cultura de cancelamento e que efeitos ela tem no discurso de saúde pública?",
      "Pessoas que fizeram detransição veem transição como tendo um ponto final ou como um processo contínuo?",
      "Por que algumas adolescentes podem experimentar angústia sobre desenvolvimento de seios?",
      "Como câmaras de eco online podem influenciar formação de identidade?",
      "Por que pessoas que fizeram detransição frequentemente relatam sentir que suas histórias e vozes são silenciadas tanto em espaços trans quanto no mainstream?",
      "Quais padrões demográficos são visíveis em encaminhamentos para clínicas de gênero?",
      "Como identidades queer contemporâneas diferem do movimento LGB anterior?",
      "O que pesquisa atual diz sobre sobreposição entre traços do espectro autista, disforia de gênero e identidades transgênero?",
      "Por que disforia de gênero não é mais classificada como transtorno mental no DSM-5?",
      "Como a prevalência trans mudou em tempos recentes e o que pode explicar isso?",
    ],
  },
  {
    title: "Termos Gerais",
    description: "Compreendendo os conceitos fundamentais",
    questions: [
      "O que é um homem?",
      "O que é uma mulher?",
      "O que é gênero?",
      "O que é disforia de gênero?",
      "O que é identidade transgênero?",
      "O que é transfobia?",
      "O que é cultura de cancelamento?",
      "O que é identidade não-binária?",
      "O que é identidade queer?",
      "O que é teoria queer?",
      "O que é personalidade?",
      "Como personalidade difere de identidade de gênero?",
      "O que é não-conformidade de gênero (GNC)?",
      "O que é conformidade de gênero?",
      "O que é detransição?",
      "O que é desistência?",
      "Quais são pronomes e por que são significativos para alguns?",
      "O que pessoas trans querem dizer quando falam sobre 'direitos trans'?",
      "Por que algumas pessoas trans dizem 'morte antes da detransição'?",
      "Quais fatores são considerados como causadores de disforia?",
      "O que é a 'bíblia da disforia de gênero'?",
      "Quais estratégias (médicas ou não-médicas) ajudam pessoas a gerenciar disforia?",
      "Pessoas intersexo são automaticamente trans?",
      "O que é fluidez de gênero?",
      "O que significam AFAB e AMAB?",
      "O que é TERF?",
      "O que é deadnaming?",
      "O que é misgenerização?",
      "O que é uma pessoa cisgênero?",
      "O que se entende por sexo biológico?",
      "Qual é a diferença entre transição social e transição médica?",
    ],
  },
  {
    title: "A Realidade Médica",
    description: "Saúde, procedimentos e verdades biológicas",
    questions: [
      "Quais são os efeitos adversos do uso de testosterona em mulheres?",
      "Quais são os efeitos adversos do uso de estrogênio em homens?",
      "Quais mudanças fisiológicas a testosterona pode induzir em mulheres e quais são os limites?",
      "Quais mudanças fisiológicas o estrogênio pode induzir em homens e quais são os limites?",
      "O que a faloplastia envolve e quais são os resultados típicos?",
      "O que a vaginoplastia envolve e quais são os resultados típicos?",
      "Quais são os diferentes tipos de cirurgia de vaginoplastia?",
      "Como alguém deve ponderar continuar versus descontinuar hormônios?",
      "Existem diferenças mensuráveis nas taxas de diagnóstico de disforia de gênero entre homens e mulheres?",
      "O que pesquisa de imagem cerebral diz sobre cérebros 'masculinos' versus 'femininos'?",
      "Como disforia de gênero é distinguida de doença mental em manuais diagnósticos?",
      "O que é atrofia vaginal e o que a causa?",
      "Quais opções de revisão cirúrgica existem para vaginoplastia ou faloplastia?",
      "Como diferentes países regulam financiamento público para cirurgias de gênero?",
      "Quais opções existem para reconstrução de tórax após mastectomia?",
      "O que são bloqueadores de puberdade e eles realmente apenas pausam a puberdade?",
      "É verdade que bloqueadores de puberdade são o mesmo medicamento usado para castração química de criminosos sexuais?",
      "Que dados de acompanhamento de longo prazo existem para uso de hormônios de sexo cruzado?",
      "Quais são os Padrões de Cuidado da WPATH e como eles são desenvolvidos?",
      "O que é o Protocolo Holandês?",
      "O que é disforia de gênero de início rápido (ROGD) e como é estudada?",
      "Quais são as taxas de arrependimento relatadas para várias cirurgias de gênero?",
      "Como terapia exploratória de gênero se parece na prática?",
    ],
  },
  {
    title: "Sociedade e Cultura",
    description: "Como crenças de gênero interagem com o mundo",
    questions: [
      "Quais são as implicações da narrativa 'nascido assim'?",
      "Identidades de gênero estão reempacotando e reforçando estereótipos sexistas?",
      "Como o feminismo mainstream mudou ao longo do tempo para acomodar identidades transgênero?",
      "Como cultura de pronomes pode levar à super-medicalização de crianças?",
      "Quais são os resultados documentados para crianças que fazem transição social cedo?",
      "Quais são as conexões entre BDSM e identidades trans?",
      "Como o conceito de gênero evoluiu historicamente?",
      "Como ativismo trans interagiu com ativismo anterior por direitos gays?",
      "Como mantras ou slogans repetitivos afetam pensamento crítico em qualquer comunidade?",
      "Como discurso contemporâneo de gênero intersecciona com identidades gays e lésbicas?",
      "O que poderia explicar o aumento na identificação não-binária?",
      "Quais explicações existem para risco elevado de suicídio em populações trans?",
      "Como o risco percebido de suicídio afeta o discurso público sobre transição?",
      "O que significa 'crítico de gênero' e como difere de visões de exclusão trans?",
      "O que é o 'debate do banheiro' e que evidências existem para dano ou segurança?",
      "Quais são os principais argumentos na controvérsia de participação esportiva?",
      "Como escolas lidaram com alunos questionando gênero em diferentes jurisdições?",
      "O que pessoas que fizeram detransição acham sobre histórias de drag queen?",
      "O que a frase 'medicalização de crianças não-conformes com gênero' significa para críticos e defensores?",
    ],
  },
  {
    title: "Psicologia e Identidade",
    description: "Compreendendo os aspectos mentais e emocionais",
    questions: [
      "Alguém pode ser mulher sem ser feminina, ou homem sem ser masculino?",
      "Que papel a mídia social desempenha em pessoas adotando identidades de gênero?",
      "O que é o ciclo neuroquímico de validação?",
      "Por que pessoas autistas podem estar super-representadas em clínicas de gênero?",
      "O que é misoginia internalizada e como pode relacionar-se à angústia corporal?",
      "O que é homofobia internalizada?",
      "O que é autoginefilia e como é debatida na literatura?",
      "O que é euforia de gênero?",
      "Adotar uma identidade trans pode amplificar disforia em vez de aliviá-la?",
      "Por que validação externa é importante para algumas pessoas trans?",
      "Qual é a diferença entre transtorno dismórfico corporal e disforia de gênero?",
      "Quais paralelos clínicos traçam entre disforia de gênero e transtornos alimentares?",
      "Como históricos de trauma podem interagir com disforia de gênero?",
      "Quais opções não-médicas existem para gerenciar disforia?",
      "O que significa 'passar' e por que pode se tornar uma obsessão para algumas pessoas?",
      "Como conceitos jungianos de anima/animus relacionam-se à identidade de gênero?",
      "O que é trabalho de sombra e pode ser usado em terapia?",
    ],
  },
  {
    title: "A Jornada de Detransição",
    description: "Cura, apoio e encontrando seu caminho de volta",
    questions: [
      "Como posso fazer as pazes com as mudanças permanentes que fiz no meu corpo?",
      "Sinto que algumas pessoas pensam que eu apenas voltei 'para o armário' e que não estou vivendo autenticamente",
      "É verdade que a maioria das pessoas que fazem detransição acabam fazendo retransição?",
      "Como transição e detransição podem ambas fazer parte da mesma jornada de cura?",
      "Onde alguém pode encontrar terapeutas experientes em suporte de detransição?",
      "A detransição significa que a transição original foi um fracasso?",
      "TCC ou DBT ajudaram pessoas que fizeram detransição em gerenciar disforia?",
      "Por que algumas comunidades trans desencorajam a leitura de narrativas de detransição?",
      "Quais grupos de apoio existem especificamente para pessoas que fizeram detransição?",
      "Como alguém pode se assumir (novamente) para a família como fazendo detransição?",
      "Quais são os estágios comuns de luto relatados durante a detransição?",
      "Que papel drogas psicodélicas desempenharam em algumas histórias de detransição?",
    ],
  },
  {
    title: "Viés Acadêmico e de Pesquisa",
    description: "Questionando a narrativa nas instituições",
    questions: [
      "Quais preocupações metodológicas foram levantadas sobre grandes pesquisas de detransição?",
      "Por que pesquisadores relatam dificuldade em garantir financiamento para estudos de detransição?",
      "Pesquisadores que atualmente se identificam como trans têm conflito de interesse?",
      "O que foi a Revisão Cass e quais recomendações ela produziu?",
      "O que aconteceu com o estudo de 2018 de Lisa Littman sobre ROGD?",
      "O que é a revisão da clínica Tavistock e por que foi encomendada?",
      "Como disforia de gênero foi reclassificada entre DSM-IV e DSM-5?",
    ],
  },
  {
    title: "Perspectivas Controversas",
    description: "Perspectivas de detransição que ativistas de gênero realmente não querem que você ouça",
    questions: [
      "Quem está ganhando dinheiro com cuidado de afirmação de gênero?",
      "Quais fatores estruturais levam à sub-representação de histórias de detransição na mídia mainstream?",
      "De que formas sistemas de crença de gênero se assemelham a religiões ou cultos?",
      "Escolas estão marginalizando pais quando crianças fazem escolhas sobre identidade de gênero?",
      "Por que existem tantos ladyboys na Tailândia?",
      "Por que o Irã é um hub global para cirurgias de redesignação sexual?",
    ],
  },
];
