/**
 * English question categories and featured questions for detrans.ai
 *
 * Gender-Related Terminology Notes:
 * - "Sex" = biological sex (anatomy, chromosomes, reproduction, immutable characteristics)
 * - "Gender" = social gender (roles, behaviors, attributes that society considers appropriate
 *   for men and women based on their biological sex)
 * - "Gender identity" = internal sense of being male, female, or somewhere in between
 * - "Gender non-conformity (GNC)" = when a person acts/presents differently from societal
 *   expectations based on their biological sex
 * - "AFAB/AMAB" = assigned female/male at birth (based on observed biological sex)
 * - "Transgender/trans" = identifying with a gender that differs from one's biological sex
 * - "Detransition" = ceasing to identify as transgender and/or reversing transition steps
 * - "Desist" = when someone who identified as trans (without medical interventions) no longer
 *   identifies as trans
 *
 * Important distinction: Gender dysphoria as a concept relies on understanding that biological
 * sex and social gender are different. Gender non-conformity (not fitting stereotypes) is
 * different from having a gender identity that differs from one's biological sex.
 */

export const questionCategories = [
  {
    title: "Featured Questions",
    description: "The best questions to ask detrans people.",
    questions: [
      "What does trans mean?",
      "Have trans people always existed?",
      "Is it true that only 1% detransition?",
      "Are puberty blockers reversible?",
      "What evidence exists for gender-affirming medical protocols?",
      "What does the term ‘egg’ mean in trans communities?",
      "What are the implications of the 'born this way' narrative?",
      "How do non-binary labels reinforce traditional gender stereotypes?",
      "What is the difference between sex and gender?",
      "What is gender dysphoria and what can cause it?",
      "Why do some people decide to detransition?",
      "How can friends or family support someone who wants to transition?",
      "How can friends or family support someone who wants to detransition?",
      "Is it common for detransitioners to regret transitioning?",
      "Why do some people decide to retransition after detransitioning?",
      "What can detrans stories teach me, even if my transition is going well so far?",
      "How would I know if doubts are just nerves or a sign that I should stop?",
      "Why do trans narratives about why people detransition differ from those who have actually detransitioned?",
      "Do detrans people think transition itself is bad?",
      "What are some false claims made about transgender people?",
      "What are some false claims made about people who have detransitioned?",
      "What early signs do detrans folks wish they’d noticed sooner?",
      "Is gender a social construct? What does this mean?",
      "How have feminist movements historically viewed the concept of gender?",
      "How can gender-nonconformity reduce the pressure to conform to gender roles?",
      "How do detrans people describe the feeling of being ‘born in the wrong body’?",
      "What is gender-affirming care and what are its goals?",
      "Why is gender-affirming care usually the only option in most regions?",
      "How does gender-exploratory therapy differ from gender-affirming care?",
      "Why do some people dislike the concept of gender-exploratory therapy, and why is it banned in some places?",
      "Do detrans people think gender affirming care and hormones should be banned?",
      "Do detransitioners usually regret medical steps, social steps, or both?",
      "What is an identity trap and how do people typically realise they are in one?",
      "Where can someone look for a therapist who offers open-ended, non-directive gender exploration? What red-flags should I look out for?",
      "Does asking for pronouns help or hinder gender-nonconforming people?",
      "If a young girl with short hair is constantly being asked for her pronouns, what is the implication and how would this make her feel?",
      "What is cancel culture and what effects does it have on public health discourse?",
      "Do detrans people see transition as having an end-point or as an ongoing process?",
      "Why might some adolescent girls experience distress about breast development?",
      "How can online echo-chambers influence identity formation?",
      "Why do detransitioners often report feeling like their stories and voices are silenced in both trans and mainstream spaces?",
      "What demographic patterns are visible in referrals to gender clinics?",
      "How do contemporary queer identities differ from the earlier LGB movement?",
      "What does current research say about overlap between autism spectrum traits, gender dysphoria, and transgender identities?",
      "Why is gender dysphoria no longer classified as a mental disorder in the DSM-5?",
      "How has trans prevalence changed in recent times and what might explain this?",
    ],
  },
  {
    title: "General Terms",
    description: "Understanding the fundamental concepts",
    questions: [
      "What is a man?",
      "What is a woman?",
      "What is gender?",
      "What is gender dysphoria?",
      "What is transgender identity?",
      "What is transphobia?",
      "What is cancel culture?",
      "What is non-binary identity?",
      "What is queer identity?",
      "What is queer theory?",
      "What is personality?",
      "How is personality different from gender identity?",
      "What is gender non-conformity (GNC)?",
      "What is gender conformity?",
      "What is detransitioning?",
      "What is desisting?",
      "What are pronouns and why are they significant to some?",
      "What do trans people mean when they talk about 'trans rights'?",
      "Why do some trans people say 'death before detransition'?",
      "What factors are thought to cause dysphoria?",
      "What is the 'gender dysphoria bible'?",
      "What strategies (medical or non-medical) help people manage dysphoria?",
      "Are intersex people automatically trans?",
      "What is gender fluidity?",
      "What do AFAB and AMAB mean?",
      "What is a TERF?",
      "What is deadnaming?",
      "What is misgendering?",
      "What is a cisgender person?",
      "What is meant by biological sex?",
      "What is the difference between social and medical transition?",
    ],
  },
  {
    title: "The Medical Reality",
    description: "Health, procedures, and biological truths",
    questions: [
      "What are the adverse effects of female testosterone use?",
      "What are the adverse effects of male estrogen use?",
      "What physiological changes can testosterone induce in females and what are the limits?",
      "What physiological changes can estrogen induce in males and what are the limits?",
      "What does phalloplasty entail and what are typical outcomes?",
      "What does vaginoplasty entail and what are typical outcomes?",
      "What are the different kinds of vaginoplasty surgery?",
      "How should someone weigh continuing versus discontinuing hormones?",
      "Are there measurable differences in gender dysphoria diagnosis rates between males and females?",
      "What does brain-imaging research say about ‘male’ versus ‘female’ brains?",
      "How is gender dysphoria distinguished from mental illness in diagnostic manuals?",
      "What is vaginal atrophy and what causes it?",
      "What surgical revision options exist for either vaginoplasty or phalloplasty?",
      "How do different countries regulate public funding for gender surgeries?",
      "What options exist for chest reconstruction after mastectomy?",
      "What are puberty blockers and do they really just pause puberty?",
      "Is it true that puberty blockers are the same drug that is used to chemically castrate sex-offenders?",
      "What long-term follow-up data exist for cross-sex hormone use?",
      "What are the WPATH Standards of Care and how are they developed?",
      "What is the Dutch Protocol?",
      "What is rapid-onset gender dysphoria (ROGD) and how is it studied?",
      "What are reported regret rates for various gender surgeries?",
      "What does gender-exploratory therapy look like in practice?",
    ],
  },
  {
    title: "Society & Culture",
    description: "How gender beliefs interact with the world",
    questions: [
      "What are the implications of the 'born this way' narrative?",
      "Are gender identities repackaging and re-inforcing sexist stereotypes?",
      "How has mainstream feminism changed over time to accomodate transgender identities?",
      "How can pronoun culture lead to the over-medicalisation of children?",
      "What are documented outcomes for children who socially transition early?",
      "What are the links between BDSM and trans identities?",
      "How has the concept of gender evolved historically?",
      "How has trans activism interacted with earlier gay-rights activism?",
      "How do repetitive mantras or slogans affect critical thinking in any community?",
      "How does contemporary gender discourse intersect with gay and lesbian identities?",
      "What could explain the rise in non-binary identification?",
      "What explanations exist for elevated suicide risk in trans populations?",
      "How does the perceived suicide risk affect public discourse around transition?",
      "What does ‘gender-critical’ mean and how does it differ from trans-exclusionary views?",
      "What is the ‘bathroom debate’ and what evidence exists for either harm or safety?",
      "What are the main arguments in the sports-participation controversy?",
      "How have schools handled gender-questioning pupils in different jurisdictions?",
      "What do detrans people think about drag queen story telling?",
      "What does the phrase ‘medicalisation of gender non-conforming children’ mean to critics and to advocates?",
    ],
  },
  {
    title: "Psychology & Identity",
    description: "Understanding the mental and emotional aspects",
    questions: [
      "Can someone be a woman without being feminine, or a man without being masculine?",
      "What role does social-media play in people adopting gender identities?",
      "What is the neurochemical cycle of validation?",
      "Why might autistic people be over-represented in gender clinics?",
      "What is internalised misogyny and how might it relate to body distress?",
      "What is internalised homophobia?",
      "What is autogynephilia and how is it debated in the literature?",
      "What is gender euphoria?",
      "Can adopting a trans identity amplify dysphoria instead of relieving it?",
      "Why is external validation important to some trans people?",
      "What is the difference between body-dysmorphic disorder and gender dysphoria?",
      "What parallels do clinicians draw between gender dysphoria and eating disorders?",
      "How might trauma histories interact with gender dysphoria?",
      "What non-medical options exist for managing dysphoria?",
      "What does ‘passing’ mean and why can it become an obsession for some people?",
      "How do Jungian concepts of anima/animus relate to gender identity?",
      "What is shadow work and can it be used in therapy?",
    ],
  },
  {
    title: "The Detransition Journey",
    description: "Healing, support, and finding your way back",
    questions: [
      "How can I make peace with the permanent changes I've made to my body?",
      "I feel like some people think I've just gone 'back in the closet' and that I'm not living authentically",
      "Is it true that most detrans people end up re-transitioning?",
      "How can transition and detransition both be part of the same healing journey?",
      "Where can someone find therapists experienced in detransition support?",
      "Does detransition mean the original transition was a failure?",
      "Has CBT or DBT helped detrans people in managing dysphoria?",
      "Why do some trans communities discourage reading detransition narratives?",
      "What support groups exist specifically for detransitioners?",
      "How can someone come out (again) to family as detransitioning?",
      "What are common stages of grief reported during detransition?",
      "What role have psychedelic drugs played in some detrans stories?",
    ],
  },
  {
    title: "Academic & Research Bias",
    description: "Questioning the narrative in institutions",
    questions: [
      "What methodological concerns have been raised about major detransition surveys?",
      "Why do researchers report difficulty securing funding for detransition studies?",
      "Do researchers who currently identify as trans have a conflict of interest?",
      "What was the Cass Review and what recommendations did it produce?",
      "What happened to Lisa Littman’s 2018 study on ROGD?",
      "What is the Tavistock clinic review and why was it commissioned?",
      "How was gender dysphoria re-classified between DSM-IV and DSM-5?",
    ],
  },
  {
    title: "Controversial Perspectives",
    description:
      "Detrans perspectives that gender activists really don't want you to hear",
    questions: [
      "Who's making money out of gender-affirming care?",
      "What structural factors lead to under-representation of detransition stories in mainstream media?",
      "In what ways do gender belief systems resemble religions or cults?",
      "Are schools sidelining parents when children make choices about gender identity?",
      "Why are there so many ladyboys in Thailand?",
      "Why is Iran a global hub for sex-reassignment surgeries?",
    ],
  },
];
