/**
 * České otázky a kategorie pro detrans.ai
 * 
 * Poznámky k genderové terminologii:
 * - "Pohlaví (sex)" = biologické pohlaví (anatomie, chromozomy, reprodukce, neměnné znaky)
 * - "Gender" = sociální gender (role, chování, atributy, které společnost považuje za vhodné
 *   pro muže a ženy na základě jejich biologického pohlaví)
 * - "Genderová identita" = vnitřní pocit být mužem, ženou nebo někde mezi tím
 * - "Negenderová konformita (GNC)" = když člověk jedná/prezentuje jinak, než společnost
 *   očekává na základě jeho biologického pohlaví
 * - "AFAB/AMAB" = assigned female/male at birth (přiřazena žena/muž při narození)
 * - "Transgender/trans" = identifikace s gendrem, který se liší od biologického pohlaví člověka
 * - "Detranzice" = ukončení identifikace jako transgender a/nebo zvrácení kroků tranzice
 * - "Desistence (zanechání)" = když někdo, kdo se identifikoval jako trans (bez lékařských zákroků), 
 *   se již neidentifikuje jako trans
 * 
 * Důležité rozlišení: Koncept genderové dysforie závisí na pochopení, že biologické pohlaví
 * a sociální gender jsou odlišné. Negenderová konformita (nepasování do stereotypů) je
 * odlišná od genderové identity, která se liší od biologického pohlaví člověka.
 */

export const questionCategories = [
  {
    title: "Doporučené otázky",
    description: "Nejlepší otázky pro lidi po detranzici.",
    questions: [
      "Co znamená trans?",
      "Existovali trans lidé vždy?",
      "Je pravda, že pouze 1 % podstoupí detranzici?",
      "Jsou blokátory puberty reverzibilní?",
      "Jaké důkazy existují pro genderově potvrzující lékařské protokoly?",
      "Co znamená termín ‚vejce‘ (egg) v trans komunitách?",
      "Jaké jsou důsledky narativu ‚tak jsem se narodil‘?",
      "Jak nebinární štítky posilují tradiční genderové stereotypy?",
      "Jaký je rozdíl mezi pohlavím (sex) a gendrem?",
      "Co je genderová dysforie a co ji může způsobit?",
      "Proč se někteří lidé rozhodnou podstoupit detranzici?",
      "Jak mohou přátelé nebo rodina podpořit někoho, kdo chce podstoupit tranzici?",
      "Jak mohou přátelé nebo rodina podpořit někoho, kdo chce podstoupit detranzici?",
      "Je běžné, že lidé po detranzici litují, že podstoupili tranzici?",
      "Proč se někteří lidé rozhodnou znovu podstoupit tranzici po detranzici?",
      "Co mě mohou příběhy po detranzici naučit, i když moje tranzice zatím probíhá dobře?",
      "Jak bych poznal/a, zda pochybnosti jsou jen nervozita nebo znamení, že bych měl/a přestat?",
      "Proč se trans narativy o tom, proč lidé podstupují detranzici, liší od těch, kteří skutečně prošli detranzicí?",
      "Myslí si lidé po detranzici, že samotná tranzice je špatná?",
      "Jaké jsou některé nepravdivá tvrzení o transgender lidech?",
      "Jaké jsou některé nepravdivá tvrzení o lidech, kteří podstoupili detranzici?",
      "Jaké časné příznaky si lidé po detranzici přáli, aby si všimli dříve?",
      "Je gender sociální konstrukt? Co to znamená?",
      "Jak feministická hnutí historicky vnímala koncept genderu?",
      "Jak může negenderová konformita snížit tlak na konformitu s genderovými rolemi?",
      "Jak lidé po detranzici popisují pocit ‚narození v nesprávném těle‘?",
      "Co je genderově potvrzující péče a jaké jsou její cíle?",
      "Proč je genderově potvrzující péče obvykle jedinou možností ve většině regionů?",
      "Jak se genderově explorační terapie liší od genderově potvrzující péče?",
      "Proč někteří lidé nemají rádi koncept genderově explorační terapie a proč je v některých místech zakázána?",
      "Myslí si lidé po detranzici, že by genderově potvrzující péče a hormony měly být zakázány?",
      "Litují lidé po detranzici obvykle lékařských kroků, sociálních kroků nebo obojího?",
      "Co je past identity a jak lidé typicky zjistí, že jsou v ní?",
      "Kde může někdo hledat terapeuta, který nabízí otevřené, nenavádějící genderové zkoumání? Jaké červené vlajky bych měl/a hledat?",
      "Pomáhá nebo překáží žádost o zájmena lidem s negenderovou konformitou?",
      "Pokud je mladá dívka s krátkými vlasy neustále žádána o svá zájmena, jaký je to implikace a jak by se to na ni mohlo projevit?",
      "Co je cancel culture (kultura rušení) a jaké má účinky na veřejné zdravotní diskurzy?",
      "Vidí lidé po detranzici tranzici jako proces s koncovým bodem nebo jako probíhající proces?",
      "Proč by některé adolescentní dívky mohly prožívat tíseň ohledně vývoje prsou?",
      "Jak mohou online echo-komory ovlivnit formování identity?",
      "Proč lidé po detranzici často hlásí pocit, že jejich příběhy a hlasy jsou utišovány v trans i mainstreamových prostorách?",
      "Jaké demografické vzorce jsou viditelné v doporučeních na genderové kliniky?",
      "Jak se současné queer identity liší od dřívějšího LGB hnutí?",
      "Co říká současný výzkum o překryvu mezi rysy autismu, genderovou dysforií a transgender identitami?",
      "Proč již není genderová dysforie klasifikována jako duševní porucha v DSM-5?",
      "Jak se prevalence trans změnila v poslední době a co by to mohlo vysvětlit?",
    ],
  },
  {
    title: "Obecné pojmy",
    description: "Pochopení základních konceptů",
    questions: [
      "Co je to muž?",
      "Co je to žena?",
      "Co je to gender?",
      "Co je to genderová dysforie?",
      "Co je to transgender identita?",
      "Co je to transfobie?",
      "Co je to cancel culture (kultura rušení)?",
      "Co je to nebinární identita?",
      "Co je to queer identita?",
      "Co je to queer teorie?",
      "Co je to osobnost?",
      "Jak se liší osobnost od genderové identity?",
      "Co je to negenderová konformita (GNC)?",
      "Co je to genderová konformita?",
      "Co je to detranzice?",
      "Co je to desistence (zanechání)?",
      "Co jsou to zájmena a proč jsou pro některé významná?",
      "Co trans lidé myslí, když mluví o ‚trans právech‘?",
      "Proč někteří trans lidé říkají ‚smrt před detranzicí‘?",
      "Jaké faktory se předpokládají jako příčina dysforie?",
      "Co je to ‚bible genderové dysforie‘?",
      "Jaké strategie (lékařské nebo nelékařské) pomáhají lidem zvládat dysforii?",
      "Jsou intersex lidé automaticky trans?",
      "Co je to genderová fluidita?",
      "Co znamenají AFAB a AMAB?",
      "Co je to TERF?",
      "Co je to deadnaming (mrtvé jmenování)?",
      "Co je to misgendering (špatné genderování)?",
      "Co je to cisgender osoba?",
      "Co se myslí biologickým pohlavím?",
      "Jaký je rozdíl mezi sociální a lékařskou tranzicí?",
    ],
  },
  {
    title: "Lékařská realita",
    description: "Zdraví, zákroky a biologické pravdy",
    questions: [
      "Jaké jsou nežádoucí účinky testosteronu u žen?",
      "Jaké jsou nežádoucí účinky estrogenu u mužů?",
      "Jaké fyziologické změny může testosteron vyvolat u žen a jaké jsou limity?",
      "Jaké fyziologické změny může estrogen vyvolat u mužů a jaké jsou limity?",
      "Co obnáší falloplastika a jaké jsou typické výsledky?",
      "Co obnáší vaginoplastika a jaké jsou typické výsledky?",
      "Jaké jsou různé druhy vaginoplastické operace?",
      "Jak by měl někdo zvážit pokračování vs ukončení hormonů?",
      "Existují měřitelné rozdíly v diagnostických mírách genderové dysforie mezi muži a ženami?",
      "Co říká výzkum zobrazování mozku o ‚mužských‘ versus ‚ženských‘ mozcích?",
      "Jak se genderová dysforie odlišuje od duševní nemoci v diagnostických manuálech?",
      "Co je to vaginální atrofie a co ji způsobuje?",
      "Jaké existují možnosti chirurgických revizí pro vaginoplastiku nebo falloplastiku?",
      "Jak různé země regulují veřejné financování genderových operací?",
      "Jaké existují možnosti rekonstrukce hrudníku po mastektomii?",
      "Co jsou to blokátory puberty a skutečně pouze pozastavují pubertu?",
      "Je pravda, že blokátory puberty jsou stejný lék, který se používá k chemické kastraci sexuálních delikventů?",
      "Jaká existují data o dlouhodobém sledování používání hormonů opačného pohlaví?",
      "Co jsou standardy péče WPATH a jak se vyvíjejí?",
      "Co je to holandský protokol?",
      "Co je to rychle se rozvíjející genderová dysforie (ROGD) a jak se studuje?",
      "Jaké jsou hlášené míry lítosti po různých genderových operacích?",
      "Jak vypadá genderově explorační terapie v praxi?",
    ],
  },
  {
    title: "Společnost a kultura",
    description: "Jak genderová přesvědčení interagují se světem",
    questions: [
      "Jaké jsou důsledky narativu ‚tak jsem se narodil‘?",
      "Reprezentují genderové identity přebalování a posilování sexistických stereotypů?",
      "Jak se mainstreamový feminismus změnil v průběhu času, aby se přizpůsobil transgender identitám?",
      "Jak může kultura zájmen vést k přemedicinalizaci dětí?",
      "Jaké jsou dokumentované výsledky pro děti, které podstoupily sociální tranzici brzy?",
      "Jaké jsou vazby mezi BDSM a trans identitami?",
      "Jak se koncept genderu vyvíjel historicky?",
      "Jak trans aktivismus interagoval s dřívějším gay-rights aktivizmem?",
      "Jak opakující se mantry nebo slogany ovlivňují kritické myšlení v jakékoli komunitě?",
      "Jak současný genderový diskurz protíná gay a lesbické identity?",
      "Co by mohlo vysvětlit vzestup nebinární identifikace?",
      "Jaké existují vysvětlení pro zvýšené riziko sebevraždy u trans populací?",
      "Jak vnímané riziko sebevraždy ovlivňuje veřejný diskurz o tranzici?",
      "Co znamená ‚gender-kritický‘ a jak se liší od trans-exkluzivních názorů?",
      "Co je to ‚debata o toaletách‘ a jaké důkazy existují pro škodu nebo bezpečnost?",
      "Jaké jsou hlavní argumenty v kontroverzi o účasti ve sportu?",
      "Jak školy zacházely s genderově zpochybňujícími žáky v různých jurisdikcích?",
      "Co si lidé po detranzici myslí o drag queen vyprávění příběhů?",
      "Co znamená fráze ‚medicalizace dětí s negenderovou konformitou‘ pro kritiky a pro zastánce?",
    ],
  },
  {
    title: "Psychologie a identita",
    description: "Pochopení duševních a emočních aspektů",
    questions: [
      "Může být někdo ženou bez toho, aby byla femininní, nebo mužem bez toho, aby byl maskulinní?",
      "Jakou roli hraje sociální média v přijímání genderových identit u lidí?",
      "Co je to neurochemický cyklus validace?",
      "Proč mohou být autisté nadměrně zastoupeni v genderových klinikách?",
      "Co je to internalizovaná misogynie a jak může souviset s tísní těla?",
      "Co je to internalizovaná homofobie?",
      "Co je to autogynefilie a jak je diskutována v literatuře?",
      "Co je to genderová euforie?",
      "Může přijetí trans identity zesílit dysforii místo jejího zmírnění?",
      "Proč je vnější validace důležitá pro některé trans lidi?",
      "Jaký je rozdíl mezi poruchou dysmorfie těla a genderovou dysforií?",
      "Jaké paralely klinici kreslí mezi genderovou dysforií a poruchami příjmu potravy?",
      "Jak mohou historie traumatu interagovat s genderovou dysforií?",
      "Jaké nelékařské možnosti existují pro zvládání dysforie?",
      "Co znamená ‚passing‘ a proč se z toho může stát posedlost pro některé lidi?",
      "Jak se jungiánské koncepty anima/animus vztahují k genderové identitě?",
      "Co je to stínová práce a může být použita v terapii?",
    ],
  },
  {
    title: "Cesta detranzice",
    description: "Hojení, podpora a hledání cesty zpět",
    questions: [
      "Jak se mohu smířit s trvalými změnami, které jsem provedl/a na svém těle?",
      "Mám pocit, že si někteří lidé myslí, že jsem se jen ‚vrátil/a do skříně‘ a že nežiji autenticky",
      "Je pravda, že většina lidí po detranzici nakonec znovu podstoupí tranzici?",
      "Jak mohou být tranzice a detranzice součástí téže cesty hojení?",
      "Kde může někdo najít terapeuty se zkušenostmi s podporou detranzice?",
      "Znamená detranzice, že původní tranzice byla selháním?",
      "Pomohla CBT nebo DBT lidem po detranzici při zvládání dysforie?",
      "Proč některé trans komunity odrazují od čtení narativů detranzice?",
      "Jaké existují podpůrné skupiny specificky pro lidi po detranzici?",
      "Jak může někdo ‚vyjít ze skříně‘ (znovu) rodině jako někdo, kdo podstupuje detranzici?",
      "Jaké jsou běžné fáze smutku hlášené během detranzice?",
      "Jakou roli hrály psychedelické drogy v některých příbězích po detranzici?",
    ],
  },
  {
    title: "Akademická a výzkumná zaujatost",
    description: "Zpochybňování narativu v institucích",
    questions: [
      "Jaké metodologické obavy byly vzneseny ohledně hlavních průzkumů detranzice?",
      "Proč výzkumníci hlásí obtíže při zajišťování financování pro studie detranzice?",
      "Mají výzkumníci, kteří se aktuálně identifikují jako trans, střet zájmů?",
      "Co byla Cass Review a jaká doporučení vytvořila?",
      "Co se stalo se studií Lisy Littmanové z roku 2018 o ROGD?",
      "Co je to přezkum kliniky Tavistock a proč byl zadán?",
      "Jak byla genderová dysforie reklasifikována mezi DSM-IV a DSM-5?",
    ],
  },
  {
    title: "Kontroverzní perspektivy",
    description:
      "Perspektivy lidí po detranzici, které genderoví aktivisté opravdu nechtějí, abyste slyšeli",
    questions: [
      "Kdo vydělává na genderově potvrzující péči?",
      "Jaké strukturální faktory vedou k nedostatečné reprezentaci příběhů detranzice v mainstreamových médiích?",
      "V jakých ohledech se genderová přesvědčení podobají náboženstvím nebo kultům?",
      "Postrádají školy rodiče, když děti dělají rozhodnutí o genderové identitě?",
      "Proč je v Thajsku tolik ladyboys?",
      "Proč je Írán globálním centrem pro operace změny pohlaví?",
    ],
  },
];
