export const questionCategories = [
  {
    title: "Featured Questions",
    description: "The best questions to ask detrans people...",
    questions: [
      "What does trans mean?",
      "Have trans people always existed?",
      "What is the difference between sex and gender?",
      "Why do some people decide to detransition?",
      "Is it common for detransitioners to regret transitioning?",
      "Why do some people decide to retransition after detransitioning?",
      "Why do trans narratives about why people detransition and retransition differ from those who have actually detransitioned?",
      "What can detrans stories teach me, even if my transition is going well so far?",
      "How would I know if doubts are just nerves or a sign that I should stop?",
      "Do detrans people think transition itself is bad?",
      "What are some false claims made about transgender people?",
      "What are some false claims made about people who have detransitioned?",
      "What early signs do detrans folks wish they’d noticed sooner?",
      "Is gender a social construct? What does this mean?",
      "How have feminist movements historically viewed the concept of gender?",
      "Can gender-nonconformity reduce the pressure to conform to gender roles?",
      "How do detrans people describe the feeling of being ‘born in the wrong body’?",
      "What is gender-affirming care and what are its goals?",
      "What is gender-exploratory therapy, how does it differ from gender-affirming care?",
      "Why is gender-affirming care usually the only available treatment for gender dysphoria in most regions?",
      "Why do some people hate the idea of gender-exploratory therapy?",
      "Do detrans people think gender affirming care and hormones should be banned?",
      "What are puberty blockers and do they really pause puberty? Can they cause infertility or other side-effects?",
      "Do detransitioners usually regret medical steps, social steps, or both?",
      "What does the term ‘egg’ mean in trans communities?",
      "What is an identity trap and how do people typically realise they are in one?",
      "How can friends or family support someone who wants to start hormones?",
      "Where can someone look for a therapist who offers open-ended, non-directive gender exploration? What red-flags should I look out for?",
      "When does asking for pronouns help versus hinder gender-nonconforming people?",
      "If a young girl with short hair is constantly being asked for her pronouns, what is the implication and how would this make her feel?",
      "How do non-binary labels reinforce traditional gender stereotypes?",
      "What is cancel culture and what effects does it have on public health discourse?",
      "Do detrans people see transition as having an end-point or as an ongoing process?",
      "Why might some adolescent girls experience distress about breast development?",
      "How can online echo-chambers influence identity formation?",
      "Why do detransitioners often report feeling like their stories and voices are silenced in both trans and mainstream spaces?",
      "What demographic patterns are visible in referrals to gender clinics?",
      "How do contemporary queer identities differ from the earlier LGB movement?",
      "What does current research say about overlap between autism spectrum traits, gender dysphoria, and transgender identities?",
      "What evidence standards exist for gender-affirming medical protocols?",
      "Why is gender dysphoria no longer classified as a mental disorder in the DSM-5?",
      "How has trans prevalence changed in recent times and what might explain this?",
    ],
  },
  {
    title: "General Terms",
    description: "Understanding the fundamental concepts",
    questions: [
      "What is a man?",
      "What is a woman?",
      "What is gender?",
      "What are pronouns and why are they significant to some?",
      "What do trans people mean when they talk about 'trans rights'?",
      "Why do some trans people say 'death before detransition'?",
      "What is cancel culture?",
      "What is gender dysphoria?",
      "What factors are thought to cause dysphoria?",
      "What is the 'gender dysphoria bible'?",
      "What strategies (medical or non-medical) help people manage dysphoria?",
      "What is transgender identity?",
      "What is transphobia?",
      "What is non-binary identity?",
      "What is queer identity?",
      "How is personality different from gender identity?",
      "What is gender non-conformity (GNC)?",
      "What is gender conformity?",
      "What is detransitioning?",
      "What is desisting?",
      "Are intersex people automatically trans?",
      "What is gender fluidity?",
      "What do AFAB and AMAB mean?",
      "What is a TERF?",
      "What is deadnaming?",
      "What is misgendering?",
      "What is a cisgender person?",
      "What is meant by biological sex?",
      "What is the difference between social and medical transition?",
    ],
  },
  {
    title: "The Medical Reality",
    description: "Health, procedures, and biological truths",
    questions: [
      "What physiological changes can hormones induce and what are their limits?",
      "What is vaginal atrophy?",
      "What are the documented health risks of gender-affirming hormone therapy?",
      "How should someone weigh continuing versus discontinuing hormones?",
      "What does vaginoplasty entail and what are typical outcomes?",
      "What does phalloplasty entail and what are typical outcomes?",
      "What surgical revision options exist for either vaginoplasty or phalloplasty?",
      "How do different countries regulate public funding for gender surgeries?",
      "What options exist for chest reconstruction after mastectomy?",
      "What evidence exists for the timing of hormone initiation relative to mental-health assessment?",
      "What does ‘puberty blocker’ mean and what is known about reversibility?",
      "What long-term follow-up data exist for cross-sex hormone use?",
      "What are the WPATH Standards of Care and how are they developed?",
      "What is the Dutch Protocol?",
      "What is rapid-onset gender dysphoria (ROGD) and how is it studied?",
      "What are reported regret rates for various gender surgeries?",
      "What does gender-exploratory therapy look like in practice?",
    ],
  },
  {
    title: "Society & Culture",
    description: "How gender beleif systems affects us all",
    questions: [
      "Are there measurable differences in referral rates between males and females?",
      "How is gender dysphoria distinguished from mental illness in diagnostic manuals?",
      "What explanations exist for elevated suicide risk in trans populations?",
      "What does ‘gender-critical’ mean and how does it differ from trans-exclusionary views?",
      "How do online mantras or slogans affect critical thinking in any identity community?",
      "How has the concept of gender evolved historically?",
      "What does brain-imaging research say about ‘male’ versus ‘female’ brains?",
      "Why might autistic people be over-represented in gender clinics?",
      "How does contemporary gender discourse intersect with gay and lesbian identities?",
      "What are documented outcomes for children who socially transition early?",
      "How has trans activism interacted with earlier gay-rights activism?",
      "Is the rise in non-binary identification a cohort effect, a fashion, or something else?",
      "What is the ‘bathroom debate’ and what evidence exists for either harm or safety?",
      "What are the main arguments in the sports-participation controversy?",
      "How have schools handled gender-questioning pupils in different jurisdictions?",
      "What do detrans people think about drag queen story telling?",
      "What does ‘medicalisation of gender non-conforming children’ mean to critics and to advocates?",
    ],
  },
  {
    title: "Psychology & Identity",
    description: "Understanding the mental and emotional aspects",
    questions: [
      "What is the neurochemical cycle of validation?",
      "What is internalised misogyny and how might it relate to body distress?",
      "What is internalised homophobia?",
      "What is autogynephilia and how is it debated in the literature?",
      "What is gender euphoria?",
      "Can adopting a trans identity amplify dysphoria instead of relieving it?",
      "Why is external validation important to some trans people?",
      "What is the difference between body-dysmorphic disorder and gender dysphoria?",
      "What role does social-media play in people adopting gender identities?",
      "How might trauma histories interact with gender dysphoria?",
      "Can someone be a woman without being feminine, or a man without being masculine?",
      "What non-medical options exist for managing dysphoria?",
      "What does ‘passing’ mean and why can it become an obsession for some people?",
      "How do Jungian concepts of anima/animus relate to gender identity?",
      "What is shadow work and can it be used in therapy?",
    ],
  },
  {
    title: "The Detransition Journey",
    description: "Healing, support, and finding your way back",
    questions: [
      "Does detransition mean the original transition was a failure?",
      "How can transition and detransition both be part of the same healing arc?",
      "What parallels do clinicians draw between gender dysphoria and eating disorders?",
      "Where can someone find therapists experienced in detransition support?",
      "What evidence exists for the effectiveness of CBT or DBT in managing dysphoria?",
      "How can someone grieve and accept body changes they no longer want?",
      "Why do some trans communities discourage reading detransition narratives?",
      "What support groups exist specifically for detransitioners?",
      "How can someone come out (again) to family as detransitioning?",
      "What are common stages of grief reported during detransition?",
      "What role have psychedelic drugs played in some detrans stories?",
    ],
  },
  {
    title: "Academic & Research Bias",
    description: "Questioning the narrative in institutions",
    questions: [
      "What methodological concerns have been raised about major detransition surveys?",
      "Why do researchers report difficulty securing funding for detransition studies?",
      "Do researchers who currently identify as trans have a conflict of interest?",
      "What was the Cass Review and what recommendations did it produce?",
      "What happened to Lisa Littman’s 2018 study on ROGD?",
      "What is the Tavistock clinic review and why was it commissioned?",
      "How was gender dysphoria re-classified between DSM-IV and DSM-5?",
    ],
  },
  {
    title: "Controversial Perspectives",
    description:
      "Detrans perspectives that gender activists really don't want you to hear",
    questions: [
      "Are some people making a lot of money out of gender-affirming care?",
      "What structural factors lead to under-representation of detransition stories in mainstream media?",
      "In what ways do gender belief systems resemble religions or cults?",
      "Are schools sidelining parents when children make choices about gender identity?",
    ],
  },
];
export const affirmingQuestionCategories = [
  {
    title: "Am I valid?",
    description: "Quick reassurance when you are doubting",
    questions: [
      "What's an egg?",
      "What causes dysphoria?",
      "What does it mean to be a woman?",
      "What does it mean to be a man?",
      "What does it mean to be a non-binary?",
      "Was I born in the wrong body?",
      "Are there male brains and female brains?",
      "How long will it take before I pass?",
      "Will I be happy once I pass?",
      "Am I trans enough if I do not have dysphoria every day?",
      "Can my identity shift over time?",
      "Do I need to prove anything to anyone?",
      "Are trans tomboys valid?",
      "Are trans femboys valid?",
      "Are trans women biological females?",
      "Are trans men biological males?",
      "What if I only feel dysphoric in certain situations?",
      "Is it okay to explore labels privately before telling anyone?",
      "What are the transition rates for trans men vs trans women?",
      "How can I overcome dysphoria?",
      "How do I know if I'm transgender and not just gender non-conforming?",
    ],
  },
  {
    title: "Names, pronouns and everyday life",
    description: "Practical tools for getting through the week",
    questions: [
      "How do I pick a name that still feels like me?",
      "What is the safest way to test pronouns online first?",
      "How do I correct people misgendering me without ruining the mood?",
      "How can I practice my voice without triggering dysphoria?",
      "What apps help me track gender euphoria moments?",
    ],
  },
  {
    title: "Dysphoria and mental health hacks",
    description: "Coping with feeling uncomfortable in your body",
    questions: [
      "I've always been a feminine man, am I trans?",
      "What are five minute grounding exercises for body dysphoria?",
      "How do I tell the difference between dysphoria and ordinary body image bad days?",
      "Can hormones or surgery be one tool but not the whole toolbox?",
      "What do I do if my dysphoria spikes after starting HRT?",
      "How can meditation help dysphoria?",
      "Where can I find free, trans competent crisis lines?",
    ],
  },
  {
    title: "Medical roadmap, no pressure",
    description: "Consider your options before making big decisions.",
    questions: [
      "What are the health effects and risks of HRT?",
      "At what age should I start HRT?",
      "What is the usual order of steps if I want hormones in my country?",
      "What are the reversible versus irreversible changes of HRT with a timeline chart?",
      "How do I check whether my insurance covers blockers or HRT?",
      "What questions should I ask the endocrinologist at the first consult?",
      "What is the actual regret rate cited by major studies with citations?",
      "Can I bank sperm or eggs on a tight budget?",
      "I'm non-binary, should I get nullifcation surgery?",
      "Should I get phaloplasty surgery?",
      "How do I find a good surgeon for phalloplasty surgery?",
      "Should I get vaginoplasty?",
      "What are the different types of vaginoplasty surgery?",
      "How do I find a good surgeon for vaginoplasty surgery?",
      "When will my vagina be a vagina?",
      "What are the least invasive ways to deal with facial hair?",
      "What is the real scoop on puberty blocker reversibility in 2024?",
    ],
  },
  {
    title: "Family, dating and coming out",
    description: "Scripts and safety plans",
    questions: [
      "How do I come out to a partner who says they are super straight?",
      "How do I protect my privacy if I am not ready to tell my parents?",
      "What are red flags that a therapist is not gender affirming?",
      "How can I find local trans meet ups that are not Facebook based?",
      "What are my rights at school or work in my state or country?",
    ],
  },
  {
    title: "Trans Sex Life & Intimacy Guide",
    description:
      "Safer sex, dysphoria hacks and pleasure tips for trans, non-binary and post-op bodies",
    questions: [
      "What are safe sex toys for trans women with bottom dysphoria?",
      "What is the best dilator schedule after trans vaginoplasty surgery?",
      "How can I ask my partner for trans affirming dirty talk?",
      "What are the contraception options available for trans men on testosterone?",
      "Why are my top surgery scars are sensitive during sex?",
      "What erection aids are there for trans women on HRT?",
      "Is it normal for your orgasm to change after starting testosterone?",
      "How to navigate hookup apps safely as a trans person?",
      "Why am I so horny after starting testosterone?",
      "How can I disclose my trans identity to a casual partner?",
      "Dealing with bottom dysphoria during sex trans tips",
      "What lube ingredients should I avoid post vaginoplasty as a trans woman",
      "Which sex positions minimise hip dysphoria for trans women?",
      "How to maintain anal health after phalloplasty?",
      "How to find trans friendly STI testing clinics?",
      "How to find low cost viagra or cialis for trans women MTF?",
    ],
  },
];

export const affirmingDetransQuestions = [
  {
    title: "De-transitioning and Re-transitioning",
    description:
      "Explore the sensitive topics of de-transition and re-transition from a detrans perspective to make sure you're informed.",
    questions: [
      "Why do some people de-transition?",
      "How many people de-transition?",
      "Why do some people re-transition after de-transitioning?",
    ],
  },
];

export const compareQuestions = [
  {
    title: "Featured Compare Questions",
    description: "Spicy questions to ask both trans and detrans people...",
    questions: [
      "What is a man?",
      "What is a woman?",
      "Are trans men biological males?",
      "Are trans women biological women?",
      "What is gender affirming care?",
      "What is gender exploratory therapy?",
      "Can people be born in the wrong body?",
      "Why do some people de-transition?",
      "How many people de-transition?",
      "Why do some people re-transition after de-transitioning?",
      "What's an egg?",
      "What's the closet?",
      "What is feminism?",
      "What is non-binary identity?",
      "Does transition ever end?",
      "Why do some women hate their breasts?",
      "Why do some people de-transition?",
      "Were detrans people real trans people?",
      "Why do people identify as queer now?",
      "Is gender-affirming care based on science?",
      "Why are the rates of people who identify as trans increasing?",
      "Why is gender dysphoria no longer treated as a mental health issue?",
    ],
  },
];
