/**
 * Finnish translation of question categories and featured questions
 * 
 * Gender-Related Terminology Notes (Sukupuoleen liittyvä termistö):
 * - "Sukupuoli (biologinen)" = biological sex (anatomy, chromosomes, reproduction, immutable characteristics)
 * - "Gender (sosiaalinen sukupuoli)" = social gender (roles, behaviors, attributes assigned by society)
 * - "Sukupuoli-identiteetti" = gender identity (internal sense of being male/female/other)
 * - "Sukupuoleen sopimattomuus / sukupuolinormien vastaisuus (GNC)" = gender non-conformity
 * - "Transsukupuolinen / trans" = transgender (identifying with gender different from biological sex)
 * - "AFAB/AMAB" = syntyessä määritelty naiseksi/mieheksi (assigned female/male at birth)
 *   - Finnish abbreviations: SMN (syntyessä määritelty naiseksi), SMM (syntyessä määritelty mieheksi)
 * - "Detransitio" = detransition (ceasing to identify as transgender and/or reversing transition steps)
 * - "Luopuminen (desistance)" = when someone who identified as trans without medical interventions no longer identifies as trans
 * 
 * Important distinction: Finnish language uses "sukupuoli" for both biological sex and social gender,
 * which can cause confusion. In this context, we distinguish:
 * - "Biologinen sukupuoli" = biological sex (unchangeable characteristics)
 * - "Sosiaalinen sukupuoli / gender" = social roles and expectations
 * 
 * The concept of gender dysphoria relies on understanding these differences.
 */

export const questionCategories = [
  {
    title: "Suositellut kysymykset",
    description: "Parhaat kysymykset detransitionaaleille esitettäviksi.",
    questions: [
      "Mitä trans tarkoittaa?",
      "Ovatko trans-ihmiset aina olleet olemassa?",
      "Onko totta, että vain 1 % detransitionoi?",
      "Ovatko murrosäestä estävät lääkkeet peruutettavissa?",
      "Mitkä todisteet ovat olemassa sukupuoliaffirmoiville lääketieteellisille protokollille?",
      "Mitä termi 'muna' (egg) tarkoittaa trans-yhteisöissä?",
      "Mitä vaikutuksia 'syntynyt tällaiseksi' -kertomuksella on?",
      "Miten ei-binääriset merkinnät vahvistavat perinteisiä sukupuolistereotypioita?",
      "Mikä on ero biologisen sukupuolen (sex) ja sosiaalisen sukupuolen (gender) välillä?",
      "Mikä on sukupuolidysforia ja mikä sen voi aiheuttaa?",
      "Miksi jotkut ihmiset päättävät detransitionoida?",
      "Miten ystävät tai perhe voivat tukea jotakuta, joka haluaa siirtyä?",
      "Miten ystävät tai perhe voivat tukea jotakuta, joka haluaa detransitionoida?",
      "Onko yleistä, että detransitionaalit katuvat transitionia?",
      "Miksi jotkut ihmiset päättävät uudelleensiirtyä detransitionoinnin jälkeen?",
      "Mitä detrans-tarinat voivat opettaa minulle, vaikka transitioni sujuisi tähän asti hyvin?",
      "Miten tietäisin, ovatko epäilykset vain hermoja vai merkki siitä, että minun pitäisi lopettaa?",
      "Miksi trans-kertomukset siitä, miksi ihmiset detransitionoivat, eroavat niistä, jotka ovat todella detransitionoineet?",
      "Pitävätkö detrans-ihmiset siirtymää itsessään huonona asiana?",
      "Mitä vääriä väitteitä trans-ihmisistä esitetään?",
      "Mitä vääriä väitteitä detransitionoineista esitetään?",
      "Mitkä varhaiset merkit detrans-ihmiset toivovat huomanneensa aikaisemmin?",
      "Onko gender sosiaalinen konstruktio? Mitä tämä tarkoittaa?",
      "Miten feministiset liikkeet ovat historiallisesti suhtautuneet gender-käsitteeseen?",
      "Miten sukupuoleen sopimattomuus voi vähentää painetta noudattaa sukupuolirooleja?",
      "Miten detrans-ihmiset kuvaavat 'väärään kehoon syntynyt' -tunnetta?",
      "Mikä on sukupuoliaffirmoiva hoito ja mitkä ovat sen tavoitteet?",
      "Miksi sukupuoliaffirmoiva hoito on usein ainoa vaihtoehto useimmilla alueilla?",
      "Miten sukupuolen tutkiva terapia eroaa sukupuoliaffirmoivasta hoidosta?",
      "Miksi jotkut ihmiset vastustavat sukupuolen tutkivan terapian konseptia, ja miksi se on kielletty joissakin paikoissa?",
      "Pitäisikö sukupuoliaffermatiivisen hoidon ja hormonien olla kielletty detrans-ihmisten mielestä?",
      "Katuvatko detransitionaalit yleensä lääketieteellisiä toimia, sosiaalisia toimia vai molempia?",
      "Mikä on identiteettiansa ja miten ihmiset tyypillisesti tajuavat olevansa sellaisessa?",
      "Mistä voi löytää terapeutin, joka tarjoaa avointa, ei-direktiivistä sukupuolen tutkimista? Millaisia punaisia lippuja minun pitäisi etsiä?",
      "Auttaako vai haittaako pronominien kysyminen sukupuoleen sopimattomia ihmisiä?",
      "Jos nuorta tyttöä lyhyillä hiuksilla pyydetään jatkuvasti kertomaan pronomininsa, mikä vaikutus sillä on ja miten hän tuntisi itsensä?",
      "Mikä on cancel culture ja mitä vaikutuksia sillä on julkiseen terveyskeskusteluun?",
      "Näkevätkö detrans-ihmiset siirtymän loppupisteenä vai jatkuvana prosessina?",
      "Miksi jotkut nuoret tytöt saattavat kokea ahdistusta rintojen kehittymisestä?",
      "Miten online-kaikukammiot voivat vaikuttaa identiteetin muodostumiseen?",
      "Miksi detransitionaalit raportoivat usein, että heidän tarinansa ja äänensä vaimennetaan sekä trans- että valtavirtaisissa tiloissa?",
      "Mitkä demografiset kaavat ovat nähtävissä sukupuoliklinikoille lähetteissä?",
      "Miten nykyaikaiset queer-identiteetit eroavat aiemmasta LGB-liikkeestä?",
      "Mitä nykyinen tutkimus sanoo autismikirjon piirteiden, sukupuolidysforian ja transsukupuolisten identiteettien päällekkäisyydestä?",
      "Miksi sukupuolidysforiaa ei enää luokitella mielenterveyshäiriöksi DSM-5:ssä?",
      "Miten trans-prevalenssi on muuttunut viime aikoina ja mikä voisi selittää tämän?",
    ],
  },
  {
    title: "Yleiset termit",
    description: "Perustavanlaatuisten käsitteiden ymmärtäminen",
    questions: [
      "Mikä on mies?",
      "Mikä on nainen?",
      "Mikä on gender?",
      "Mikä on sukupuolidysforia?",
      "Mikä on transsukupuolinen identiteetti?",
      "Mikä on transfobia?",
      "Mikä on cancel culture?",
      "Mikä on ei-binäärinen identiteetti?",
      "Mikä on queer-identiteetti?",
      "Mikä on queer-teoria?",
      "Mikä on persoonallisuus?",
      "Miten persoonallisuus eroaa sukupuoli-identiteetistä?",
      "Mikä on sukupuoleen sopimattomuus (GNC)?",
      "Mikä on sukupuolinen konformisuus?",
      "Mikä on detransitio?",
      "Mikä on luopuminen (desisting)?",
      "Mitä ovat pronominit ja miksi ne ovat merkittäviä joillekin?",
      "Mitä trans-ihmiset tarkoittavat puhuessaan 'trans-oikeuksista'?",
      "Miksi jotkut trans-ihmiset sanovat 'kuolema ennen detransitiota'?",
      "Mitkä tekijät ajatellaan aiheuttavan dysforiaa?",
      "Mikä on 'sukupuolidysforian raamattu'?",
      "Mitkä strategiat (lääketieteelliset tai ei-lääketieteelliset) auttavat ihmisiä hallitsemaan dysforiaa?",
      "Ovatko intersukupuoliset ihmiset automaattisesti trans?",
      "Mikä on sukupuolinen fluiditeetti?",
      "Mitä AFAB ja AMAB tarkoittavat?",
      "Mikä on TERF?",
      "Mikä on deadnaming?",
      "Mikä on misgendering?",
      "Mikä on cis-sukupuolinen henkilö?",
      "Mitä tarkoitetaan biologisella sukupuolella?",
      "Mikä on ero sosiaalisen ja lääketieteellisen transition välillä?",
    ],
  },
  {
    title: "Lääketieteellinen todellisuus",
    description: "Terveys, toimenpiteet ja biologiset totuudet",
    questions: [
      "Mitkä ovat naisten testosteronikäytön haitalliset vaikutukset?",
      "Mitkä ovat miesten estrogeenikäytön haitalliset vaikutukset?",
      "Mitkä fysiologiset muutokset testosteroni voi aiheuttaa naisilla ja mitkä ovat rajat?",
      "Mitkä fysiologiset muutokset estrogeeni voi aiheuttaa miehillä ja mitkä ovat rajat?",
      "Mitä falloplastia sisältää ja mitkä ovat tyypilliset tulokset?",
      "Mitä vaginoplastia sisältää ja mitkä ovat tyypilliset tulokset?",
      "Mitkä ovat erilaiset vaginoplastialeikkauksen tyypit?",
      "Miten jonkun pitäisi punnita hormonien jatkamista vs. lopettamista?",
      "Onko mitattavissa eroja sukupuolidysforian diagnoosiprosenteissa miesten ja naisten välillä?",
      "Mitä aivokuvantamistutkimus sanoo 'miesten' vs. 'naisten' aivoista?",
      "Miten sukupuolidysforia erotetaan mielenterveyden häiriöistä diagnoosikäsikirjoissa?",
      "Mikä on emättimen atrofia ja mikä sen aiheuttaa?",
      "Mitkä kirurgiset korjausvaihtoehdot ovat olemassa joko vaginoplastialle tai falloplastialle?",
      "Miten eri maat säätelevät julkista rahoitusta sukupuolileikkauksille?",
      "Mitkä vaihtoehdot ovat olemassa rintojen jälleenrakentamiseen mastektomian jälkeen?",
      "Mitä ovat murrosäestä estävät lääkkeet ja keskeyttävätkö ne todella vain murrosiän?",
      "Onko totta, että murrosäestä estävät lääkkeet ovat sama lääke, jota käytetään seksuaalirikollisten kemialliseen kastraatioon?",
      "Mitä pitkän aikavälin seurantatietoja on olemassa ristisukupuolihormonien käytöstä?",
      "Mitä ovat WPATH-hoidon standardit ja miten ne kehitetään?",
      "Mikä on hollantilainen protokolla?",
      "Mikä on nopeasti puhjennut sukupuolidysforia (ROGD) ja miten sitä tutkitaan?",
      "Mitkä ovat raportoidut katumisprosentit erilaisissa sukupuolileikkauksissa?",
      "Miltä sukupuolen tutkiva terapia näyttää käytännössä?",
    ],
  },
  {
    title: "Yhteiskunta ja kulttuuri",
    description: "Miten sukupuoliuskomukset vuorovaikuttavat maailman kanssa",
    questions: [
      "Mitä vaikutuksia 'syntynyt tällaiseksi' -kertomuksella on?",
      "Ovatko sukupuoli-identiteetit uudelleenpakkaamassa ja vahvistamassa seksistisiä stereotypioita?",
      "Miten valtavirtafeminismi on muuttunut ajan myötä hyväksyäkseen transsukupuoliset identiteetit?",
      "Miten pronominikulttuuri voi johtaa lasten ylilääketieteellistämiseen?",
      "Mitä dokumentoituja tuloksia on olemassa lapsille, jotka ovat sosiaalisesti siirtyneet aikaisin?",
      "Mitä yhteyksiä on olemassa BDSM:n ja trans-identiteettien välillä?",
      "Miten gender-käsite on kehittynyt historiallisesti?",
      "Miten trans-aktivismi on vuorovaikuttanut aiemman homojen oikeuksien aktivismin kanssa?",
      "Miten toistuvat mantrat tai iskulauseet vaikuttavat kriittiseen ajatteluun missä tahansa yhteisössä?",
      "Miten nykyaikainen gender-keskustelu leikkaa homo- ja lesbo-identiteettien kanssa?",
      "Mitä voisi selittää ei-binäärisen identifioitumisen nousun?",
      "Mitä selityksiä on olemassa kohonneelle itsemurhariskille trans-populaatioissa?",
      "Miten koettu itsemurhariski vaikuttaa julkiseen keskusteluun siirtymästä?",
      "Mitä 'gender-kriittinen' tarkoittaa ja miten se eroaa trans-poissulkevista näkemyksistä?",
      "Mikä on 'wc-keskustelu' ja mitä todisteita on olemassa joko haitasta tai turvallisuudesta?",
      "Mitkä ovat pääargumentit urheiluosallistumiskiistassa?",
      "Miten koulut ovat käsitelleet sukupuolta pohtivia oppilaita eri oikeusalueilla?",
      "Mitä detrans-ihmiset ajattelevat drag queen -tarinankerronnasta?",
      "Mitä termi 'sukupuoleen sopimattomien lasten lääketieteellistäminen' tarkoittaa kriitikoille ja kannattajille?",
    ],
  },
  {
    title: "Psykologia ja identiteetti",
    description: "Mentaalisten ja emotionaalisten näkökohtien ymmärtäminen",
    questions: [
      "Voiko joku olla nainen ilman feminiinisyyttä tai mies ilman maskuliinisuutta?",
      "Mikä rooli sosiaalisella medialla on sukupuoli-identiteettien omaksumisessa?",
      "Mikä on validoinnin neurokemiallinen sykli?",
      "Miksi autistiset ihmiset saattavat olla yliedustettuina sukupuoliklinikoilla?",
      "Mikä on internalisoitu misogynia ja miten se saattaa liittyä kehon ahdistukseen?",
      "Mikä on internalisoitu homofobia?",
      "Mikä on autogynefilia ja miten siitä keskustellaan kirjallisuudessa?",
      "Mikä on gendereuforia?",
      "Voiko trans-identiteetin omaksuminen vahvistaa dysforiaa sen lievittämisen sijaan?",
      "Miksi ulkoinen validointi on tärkeää joillekin trans-ihmisille?",
      "Mikä on ero kehodysmorfiasta ja sukupuolidysforiasta?",
      "Mitkä rinnastukset kliinikot tekevät sukupuolidysforian ja syömishäiriöiden välillä?",
      "Miten traumahistoriat saattavat vuorovaikuttaa sukupuolidysforian kanssa?",
      "Mitkä ei-lääketieteelliset vaihtoehdot ovat olemassa dysforian hallintaan?",
      "Mitä 'passing' tarkoittaa ja miksi siitä voi tulla pakkomielle joillekin ihmisille?",
      "Miten jungilaiset anima/animus-käsitteet liittyvät sukupuoli-identiteettiin?",
      "Mikä on varjotyö ja voiko sitä käyttää terapiassa?",
    ],
  },
  {
    title: "Detransition-matka",
    description: "Parantuminen, tuki ja oman tiensä löytäminen takaisin",
    questions: [
      "Miten voin tehdä rauhan kehooni tekemieni pysyvien muutosten kanssa?",
      "Tunnen, että jotkut ihmiset ajattelevat, että olen vain mennyt 'takaisin kaappiin' ja etten elä autenttisesti",
      "Onko totta, että useimmat detrans-ihmiset päätyvät lopulta uudelleensiirtymään?",
      "Miten siirtymä ja detransitio voivat molemmat olla osa samaa parantumismatkaa?",
      "Mistä voi löytää terapeutteja, joilla on kokemusta detransition-tuesta?",
      "Tarkoittaako detransitio, että alkuperäinen siirtymä oli epäonnistuminen?",
      "Onko CBT tai DBT auttanut detrans-ihmisiä dysforian hallinnassa?",
      "Miksi jotkut trans-yhteisöt kannustavat lukemaan detransition-tarinoita?",
      "Mitkä tukiryhmät ovat olemassa erityisesti detransitionaaleille?",
      "Miten joku voi tulla ulos (uudelleen) perheestä detransitionoivana?",
      "Mitkä ovat yleiset surun vaiheet, joista raportoidaan detransition aikana?",
      "Mikä rooli psykedeelisillä huumeilla on ollut joissakin detrans-tarinoissa?",
    ],
  },
  {
    title: "Akateeminen ja tutkimusharha",
    description: "Narratiivin kyseenalaistaminen instituutioissa",
    questions: [
      "Mitä metodologisia huolia on esitetty suurista detransition-kyselyistä?",
      "Miksi tutkijat raportoivat vaikeuksista saada rahoitusta detransition-tutkimuksiin?",
      "Onko tutkijoilla, jotka tällä hetkellä identifioituvat transnaisiksi, eturistiriita?",
      "Mikä oli Cass Review ja mitkä suositukset se tuotti?",
      "Mitä tapahtui Lisa Littmanin vuoden 2018 tutkimukselle ROGD:stä?",
      "Mikä on Tavistock-klinikan tarkastelu ja miksi se tilattiin?",
      "Miten sukupuolidysforia luokiteltiin uudelleen DSM-IV:n ja DSM-5:n välillä?",
    ],
  },
  {
    title: "Kiistanalaiset näkökulmat",
    description:
      "Detrans-näkökulmat, joita gender-aktivistit eivät halua sinun kuulevan",
    questions: [
      "Kuka tekee rahaa sukupuoliaffirmoivalla hoidolla?",
      "Mitkä rakenteelliset tekijät johtavat detransition-tarinoiden aliedustukseen valtavirtamediassa?",
      "Millä tavoilla sukupuoliuskomusjärjestelmät muistuttavat uskontoja tai kultteja?",
      "Sivuuttaavatko koulut vanhempia, kun lapset tekevät valintoja sukupuoli-identiteetistä?",
      "Miksi Thaimaassa on niin monta ladyboyta?",
      "Miksi Iran on globaali keskus sukupuolenkorjausleikkauksille?",
    ],
  },
];
