/**
 * Norsk oversettelse av spørsmålskategorier og utvalgte spørsmål for detrans.ai
 *
 * Merknader om kjønnsrelatert terminologi:
 * - "Kjønn" (biologisk kjønn) = biological sex (anatomi, kromosomer, reproduksjon, uforanderlige egenskaper)
 * - "Gender" (sosialt kjønn) = social gender (roller, atferd, attributter som samfunnet anser passende
 *   for menn og kvinner basert på deres biologiske kjønn)
 * - "Kjønnsidentitet" = indre følelse av å være mann, kvinne eller et sted midt imellom
 * - "Kjønnsnonkonformitet (GNC)" = når en person handler/presenterer seg annerledes enn samfunnets
 *   forventninger basert på deres biologiske kjønn
 * - "AFAB/AMAB" = assigned female/male at birth (tilordnet kvinne/mann ved fødselen) – basert på observert biologisk kjønn
 * - "Transperson/trans" = identifiserer seg med et kjønn som skiller seg fra ens biologiske kjønn
 * - "Detransisjon" = slutter å identifisere seg som transperson og/eller reverserer transisjonstrinn
 * - "Desistere" = når noen som identifiserte seg som trans (uten medisinske inngrep) ikke lenger
 *   identifiserer seg som trans
 *
 * Viktig skille: Kjønnsdysfori som konsept er avhengig av forståelsen av at biologisk kjønn og
 * sosialt kjønn er forskjellige. Kjønnsnonkonformitet (å ikke passe inn i stereotyper) er
 * forskjellig fra å ha en kjønnsidentitet som skiller seg fra ens biologiske kjønn.
 */

export const questionCategories = [
  {
    title: "Utvalgte spørsmål",
    description: "De beste spørsmålene å stille til detransisjonerte.",
    questions: [
      "Hva betyr trans?",
      "Har transpersoner alltid eksistert?",
      "Er det sant at bare 1% detransisjonerer?",
      "Er pubertetsblokkere reversible?",
      "Hvilke bevis finnes for kjønnsbekreftende medisinske protokoller?",
      "Hva betyr uttrykket 'egg' i transfellesskap?",
      "Hva er implikasjonene av 'født slik'-fortellingen?",
      "Hvordan forsterker ikke-binære merkelapper tradisjonelle kjønnsstereotyper?",
      "Hva er forskjellen på kjønn og gender?",
      "Hva er kjønnsdysfori og hva kan forårsake det?",
      "Hvorfor bestemmer noen mennesker seg for å detransisjonere?",
      "Hvordan kan venner eller familie støtte noen som ønsker å transisjonere?",
      "Hvordan kan venner eller familie støtte noen som ønsker å detransisjonere?",
      "Er det vanlig at detransisjonerte angrer på at de transisjonerte?",
      "Hvorfor bestemmer noen mennesker seg for å retransisjonere etter detransisjon?",
      "Hva kan detransisjonertes historier lære meg, selv om min transisjon går bra så langt?",
      "Hvordan vet jeg om tvil bare er nerver eller et tegn på at jeg burde stoppe?",
      "Hvorfor skiller transfortellinger om hvorfor folk detransisjonerer seg fra de som faktisk har detransisjonert?",
      "Mener detransisjonerte at transisjon i seg selv er dårlig?",
      "Hvilke falske påstander fremmes om transpersoner?",
      "Hvilke falske påstander fremmes om mennesker som har detransisjonert?",
      "Hvilke tidlige tegn ønsker detransisjonerte at de hadde lagt merke til tidligere?",
      "Er gender en sosial konstruksjon? Hva betyr dette?",
      "Hvordan har feministiske bevegelser historisk sett betraktet konseptet gender?",
      "Hvordan kan kjønnsnonkonformitet redusere presset om å tilpasse seg kjønnsroller?",
      "Hvordan beskriver detransisjonerte følelsen av å være 'født i feil kropp'?",
      "Hva er kjønnsbekreftende behandling og hva er målene?",
      "Hvorfor er kjønnsbekreftende behandling vanligvis det eneste alternativet i de fleste regioner?",
      "Hvordan skiller kjønnsutforskende terapi seg fra kjønnsbekreftende behandling?",
      "Hvorfor misliker noen konseptet kjønnsutforskende terapi, og hvorfor er det forbudt noen steder?",
      "Mener detransisjonerte at kjønnsbekreftende behandling og hormoner burde forbys?",
      "Anger detransisjonerte vanligvis medisinske skritt, sosiale skritt, eller begge deler?",
      "Hva er en identitetsfelle og hvordan innser folk typisk at de er i en?",
      "Hvor kan noen lete etter en terapeut som tilbyr åpen, ikke-direktiv kjønnsutforskning? Hvilke røde flagg bør jeg se etter?",
      "Hjelper det å spørre om pronomen kjønnsnonkonforme mennesker eller hemmer det dem?",
      "Hvis en ung jente med kort hår stadig blir spurt om pronomenene sine, hva er implikasjonen og hvordan ville dette få henne til å føle seg?",
      "Hva er cancel-kultur og hvilke effekter har det på folkehelse-diskurs?",
      "Ser detransisjonerte på transisjon som å ha et endepunkt eller som en pågående prosess?",
      "Hvorfor kan noen unge jenter oppleve nød om brystutvikling?",
      "Hvordan kan nettbaserte ekkokamre påvirke identitetsdannelse?",
      "Hvorfor rapporterer detransisjonerte ofte at de føler at historiene og stemmene deres blir knebelt i både trans- og mainstream-rom?",
      "Hvilke demografiske mønstre er synlige i henvisninger til kjønnsklinikker?",
      "Hvordan skiller moderne skeive identiteter seg fra den tidligere LHBT-bevegelsen?",
      "Hva sier aktuell forskning om overlapping mellom autisme-spekter-trekk, kjønnsdysfori og transidentiteter?",
      "Hvorfor klassifiseres ikke lenger kjønnsdysfori som en psykisk lidelse i DSM-5?",
      "Hvordan har transprevalens endret seg i nyere tid og hva kan forklare dette?",
    ],
  },
  {
    title: "Generelle begreper",
    description: "Forstå de grunnleggende konseptene",
    questions: [
      "Hva er en mann?",
      "Hva er en kvinne?",
      "Hva er gender?",
      "Hva er kjønnsdysfori?",
      "Hva er transidentitet?",
      "Hva er transfobi?",
      "Hva er cancel-kultur?",
      "Hva er ikke-binær identitet?",
      "Hva er skeiv identitet?",
      "Hva er skeiv teori?",
      "Hva er personlighet?",
      "Hvordan skiller personlighet seg fra kjønnsidentitet?",
      "Hva er kjønnsnonkonformitet (GNC)?",
      "Hva er kjønnskonformitet?",
      "Hva er detransisjon?",
      "Hva er å desistere?",
      "Hva er pronomen og hvorfor er de betydningsfulle for noen?",
      "Hva mener transpersoner når de snakker om 'transrettigheter'?",
      "Hvorfor sier noen transpersoner 'død før detransisjon'?",
      "Hvilke faktorer antas å forårsake dysfori?",
      "Hva er 'kjønnsdysfori-bibelen'?",
      "Hvilke strategier (medisinske eller ikke-medisinske) hjelper mennesker med å håndtere dysfori?",
      "Er interseksuelle mennesker automatisk trans?",
      "Hva er kjønnsfluiditet?",
      "Hva betyr AFAB og AMAB?",
      "Hva er TERF?",
      "Hva er dødnavning?",
      "Hva er misgendering?",
      "Hva er en cisgender-person?",
      "Hva menes med biologisk kjønn?",
      "Hva er forskjellen på sosial og medisinsk transisjon?",
    ],
  },
  {
    title: "Den medisinske virkeligheten",
    description: "Helse, prosedyrer og biologiske sannheter",
    questions: [
      "Hva er de negative effektene av kvinnelig testosteron-bruk?",
      "Hva er de negative effektene av mannlig østrogen-bruk?",
      "Hvilke fysiologiske endringer kan testosteron indusere hos kvinner og hva er grensene?",
      "Hvilke fysiologiske endringer kan østrogen indusere hos menn og hva er grensene?",
      "Hva innebærer falloplastikk og hva er typiske utfall?",
      "Hva innebærer vaginoplastikk og hva er typiske utfall?",
      "Hvilke forskjellige typer vaginoplastikk-kirurgi finnes?",
      "Hvordan bør noen veie fortsettelse versus seponering av hormoner?",
      "Finnes det målbare forskjeller i kjønnsdysfori-diagnostiseringsrater mellom menn og kvinner?",
      "Hva sier hjerneavbildningsforskning om 'mannlige' versus 'kvinnelige' hjerner?",
      "Hvordan skilles kjønnsdysfori fra psykisk lidelse i diagnostiske manualer?",
      "Hva er vaginal atrofi og hva forårsaker det?",
      "Hvilke kirurgiske revisjonsalternativer finnes for enten vaginoplastikk eller falloplastikk?",
      "Hvordan regulerer forskjellige land offentlig finansiering av kjønnskirurgi?",
      "Hvilke alternativer finnes for brystrekonstruksjon etter mastektomi?",
      "Hva er pubertetsblokkere og setter de virkelig bare puberteten på pause?",
      "Er det sant at pubertetsblokkere er det samme legemidlet som brukes til å kjemisk kastrere sex-forbrytere?",
      "Hvilken langsiktig oppfølgingsdata finnes for kjønnshormon-bruk?",
      "Hva er WPATH-standardene for omsorg og hvordan utvikles de?",
      "Hva er den nederlandske protokollen?",
      "Hva er raskt innsettende kjønnsdysfori (ROGD) og hvordan studeres det?",
      "Hva er rapporterte angerrater for ulike kjønnskirurgier?",
      "Hvordan ser kjønnsutforskende terapi ut i praksis?",
    ],
  },
  {
    title: "Samfunn og kultur",
    description: "Hvordan kjønnsforestillinger samhandler med verden",
    questions: [
      "Hva er implikasjonene av 'født slik'-fortellingen?",
      "Er kjønnsidentiteter ompakking og forsterking av sexistiske stereotyper?",
      "Hvordan har mainstream-feminisme endret seg over tid for å romme transidentiteter?",
      "Hvordan kan pronomen-kultur føre til over-medikalisering av barn?",
      "Hva er dokumenterte utfall for barn som sosialt transisjonerer tidlig?",
      "Hva er koblingene mellom BDSM og transidentiteter?",
      "Hvordan har gender-konseptet utviklet seg historisk?",
      "Hvordan har transaktivisme samhandlet med tidligere homorettighetsaktivisme?",
      "Hvordan påvirker repetitive mantraer eller slagord kritisk tenkning i ethvert fellesskap?",
      "Hvordan skjærer moderne gender-diskurs med homo- og lesbiske identiteter?",
      "Hva kan forklare økningen i ikke-binær identifisering?",
      "Hvilke forklaringer finnes på forhøyet selvmordsrisiko i transbefolkningen?",
      "Hvordan påvirker den oppfattede selvmordsrisikoen offentlig diskurs rundt transisjon?",
      "Hva betyr 'kjønnskritisk' og hvordan skiller det seg fra trans-ekskluderende syn?",
      "Hva er 'toalettdebatten' og hvilke bevis finnes for enten skade eller sikkerhet?",
      "Hva er hovedargumentene i sportsdeltakelseskontroversen?",
      "Hvordan har skoler håndtert kjønnsspørrende elever i forskjellige jurisdiksjoner?",
      "Hva mener detransisjonerte om drag queen-eventyrfortelling?",
      "Hva betyr uttrykket 'medikalisering av kjønnsnonkonforme barn' for kritikere og for tilhengere?",
    ],
  },
  {
    title: "Psykologi og identitet",
    description: "Forstå de mentale og emosjonelle aspektene",
    questions: [
      "Kan noen være en kvinne uten å være feminin, eller en mann uten å være maskulin?",
      "Hvilken rolle spiller sosiale medier i at mennesker adopterer kjønnsidentiteter?",
      "Hva er den nevrokjemiske valideringssyklusen?",
      "Hvorfor kan autistiske mennesker være overrepresentert i kjønnsklinikker?",
      "Hva er internalisert kvinnehat og hvordan kan det relatere til kroppsnød?",
      "Hva er internalisert homofobi?",
      "Hva er autogynefili og hvordan debatteres det i litteraturen?",
      "Hva er kjønnseufori?",
      "Kan adoptering av en transidentitet forsterke dysfori i stedet for å lindre det?",
      "Hvorfor er ekstern validering viktig for noen transpersoner?",
      "Hva er forskjellen mellom kroppsdysmorfi og kjønnsdysfori?",
      "Hvilke paralleller trekker klinikere mellom kjønnsdysfori og spiseforstyrrelser?",
      "Hvordan kan traumehistorier samhandle med kjønnsdysfori?",
      "Hvilke ikke-medisinske alternativer finnes for å håndtere dysfori?",
      "Hva betyr 'å passe' og hvorfor kan det bli en besettelse for noen mennesker?",
      "Hvordan relaterer jungianske konsepter om anima/animus seg til kjønnsidentitet?",
      "Hva er skyggearbeid og kan det brukes i terapi?",
    ],
  },
  {
    title: "Detransisjonsreisen",
    description: "Helbredelse, støtte og å finne veien tilbake",
    questions: [
      "Hvordan kan jeg gjøre fred med de permanente endringene jeg har gjort med kroppen min?",
      "Jeg føler at noen mennesker tror jeg bare har 'gått tilbake i skapet' og at jeg ikke lever autentisk",
      "Er det sant at de fleste detransisjonerte ender opp med å retransisjonere?",
      "Hvordan kan både transisjon og detransisjon være deler av den samme helbredelsesreisen?",
      "Hvor kan noen finne terapeuter med erfaring i detransisjonsstøtte?",
      "Betyr detransisjon at den opprinnelige transisjonen var en fiasko?",
      "Har KBT eller DBT hjulpet detransisjonerte med å håndtere dysfori?",
      "Hvorfor fraråder noen transfellesskap å lese detransisjonsfortellinger?",
      "Hvilke støttegrupper finnes spesifikt for detransisjonerte?",
      "Hvordan kan noen komme ut (igjen) til familien som detransisjonerende?",
      "Hva er vanlige sorgstadier rapportert under detransisjon?",
      "Hvilken rolle har psykedeliske rusmidler spilt i noen detransisjonshistorier?",
    ],
  },
  {
    title: "Akademisk og forsknings-skjevhet",
    description: "Sette spørsmål ved narrativet i institusjoner",
    questions: [
      "Hvilke metodiske bekymringer er blitt reist om store detransisjonsundersøkelser?",
      "Hvorfor rapporterer forskere vanskeligheter med å sikre finansiering for detransisjonsstudier?",
      "Har forskere som for øyeblikket identifiserer seg som trans en interessekonflikt?",
      "Hva var Cass-rapporten og hvilke anbefalinger kom den med?",
      "Hva skjedde med Lisa Littmans 2018-studie om ROGD?",
      "Hva er Tavistock-klinikkgjennomgangen og hvorfor ble den bestilt?",
      "Hvordan ble kjønnsdysfori reklassifisert mellom DSM-IV og DSM-5?",
    ],
  },
  {
    title: "Kontroversielle perspektiver",
    description:
      "Detrans-perspektiver som kjønnsaktivister virkelig ikke vil at du skal høre",
    questions: [
      "Hvem tjener penger på kjønnsbekreftende behandling?",
      "Hvilke strukturelle faktorer fører til underrepresentasjon av detransisjonshistorier i mainstream-medier?",
      "På hvilke måter ligner kjønnsforestillingssystemer religioner eller kult?",
      "Sidemer skolene foreldre når barn tar valg om kjønnsidentitet?",
      "Hvorfor er det så mange ladyboys i Thailand?",
      "Hvorfor er Iran et globalt knutepunkt for kjønnsskiftekirurgi?",
    ],
  },
];
