/**
 * Slovenian translation of question categories and featured questions for detrans.ai
 *
 * Gender-Related Terminology Notes:
 * - "Spol" = biological sex (anatomy, chromosomes, reproduction, immutable characteristics)
 * - "Spolni izraz" / "Rod" = social gender (roles, behaviors, attributes that society considers appropriate
 *   for men and women based on their biological sex)
 * - "Spolna identiteta" = gender identity (internal sense of being male, female, or somewhere in between)
 * - "Nekonformnost s spolom (GNC)" = gender non-conformity (when a person acts/presents differently from societal
 *   expectations based on their biological sex)
 * - "AFAB/AMAB" = dodeljen ženski/moški ob rojstvu (assigned female/male at birth, based on observed biological sex)
 * - "Transspolni/trans" = identifying with a gender that differs from one's biological sex
 * - "Detranzicija" = ceasing to identify as transgender and/or reversing transition steps
 * - "Opustitev" = when someone who identified as trans (without medical interventions) no longer
 *   identifies as trans
 *
 * Important distinction: Gender dysphoria as a concept relies on understanding that biological
 * sex and social gender are different. Gender non-conformity (not fitting stereotypes) is
 * different from having a gender identity that differs from one's biological sex.
 */

export const questionCategories = [
  {
    title: "Izpostavljena vprašanja",
    description: "Najboljša vprašanja za postavitev osebam, ki so opravile detranzicijo.",
    questions: [
      "Kaj pomeni trans?",
      "Ali so trans osebe obstajale vedno?",
      "Ali je res, da le 1% opravi detranzicijo?",
      "Ali so zaviralci pubertete reverzibilni?",
      "Kakšni dokazi obstajajo za medicinske protokole potrjevanja spola?",
      "Kaj pomeni izraz ‚jajce' (egg) v trans skupnostih?",
      "Kakšne so posledice narativa ‚rojeni tako'?",
      "Kako nebinarne oznake krepijo tradicionalne stereotipe o spolu?",
      "Kakšna je razlika med spolom in spolnim izrazom?",
      "Kaj je disforija spola in kaj jo lahko povzroči?",
      "Zakaj se nekateri ljudje odločijo za detranzicijo?",
      "Kako lahko prijatelji ali družina podpirajo nekoga, ki želi opraviti tranzicijo?",
      "Kako lahko prijatelji ali družina podpirajo nekoga, ki želi opraviti detranzicijo?",
      "Ali je pogosto, da ljudje, ki so opravili detranzicijo, obžalujejo tranzicijo?",
      "Zakaj se nekateri ljudje po detranziciji odločijo za retranzicijo?",
      "Kaj se lahko naučim iz zgodb o detranziciji, tudi če moja tranzicija do sedaj poteka dobro?",
      "Kako naj vem, ali so dvomi le živčnost ali znak, da naj neham?",
      "Zakaj se trans narativi o tem, zakaj ljudje opravijo detranzicijo, razlikujejo od tistih, ki so jo dejansko opravili?",
      "Ali ljudje z izkušnjo detranzicije menijo, da je tranzicija sama po sebi slaba?",
      "Katere so nekatere napačne trditve o transspolnih osebah?",
      "Katere so nekatere napačne trditve o ljudeh, ki so opravili detranzicijo?",
      "Katere zgodnje znake si želijo ljudje z izkušnjo detranzicije, da bi jih prej opazili?",
      "Ali je spol družbena konstrukcija? Kaj to pomeni?",
      "Kako so feministična gibanja zgodovinsko gledala na koncept spola?",
      "Kako lahko nekonformnost s spolom zmanjša pritisk, da se ujemaš v spolne vloge?",
      "Kako ljudje z izkušnjo detranzicije opisujejo občutek, da so ‚rojeni v napačno telo'?",
      "Kaj je skrb, ki potrjuje spol, in kakšni so njeni cilji?",
      "Zakaj je skrb, ki potrjuje spol, običajno edina možnost v večini regij?",
      "Kako se raziskovalna terapija spola razlikuje od skrbi, ki potrjuje spol?",
      "Zakaj nekateri ljudje zavračajo koncept raziskovalne terapije spola in zakaj je na nekaterih mestih prepovedana?",
      "Ali ljudje z izkušnjo detranzicije menijo, da bi morala biti skrb, ki potrjuje spol, in hormoni prepovedani?",
      "Ali ljudje z izkušnjo detranzicije običajno obžalujejo medicinske korake, družbene korake ali oboje?",
      "Kaj je past identitete in kako ljudje običajno ugotovijo, da so v njej?",
      "Kje lahko nekdo poišče terapevta, ki ponuja odprto, nedirektivno raziskovanje spola? Na katera opozorilna znaka naj bom pozoren?",
      "Ali spraševanje o zaimkih pomaga ali ovira osebe, ki so nekonformne s spolom?",
      "Če se mlado dekle s kratkimi lasmi nenehno sprašuje po svojih zaimkih, kakšne posledice ima to in kako bi se počutilo?",
      "Kaj je kultura preklica in kakšne učinke ima na javno zdravstveno razpravo?",
      "Ali ljudje z izkušnjo detranzicije vidijo tranzicijo kot proces z končno točko ali kot tekoči proces?",
      "Zakaj bi lahko nekatere najstniške deklice občutile stisko zaradi razvoja prsi?",
      "Kako lahko spletni odmevni komori vplivajo na oblikovanje identitete?",
      "Zakaj ljudje, ki so opravili detranzicijo, pogosto poročajo, da so njihove zgodbe in glasovi utišani tako v trans kot v mainstream prostorih?",
      "Katere demografske vzorce je mogoče opaziti pri napotitvah na spolne klinike?",
      "Kako se sodobne queer identitete razlikujejo od prejšnjega LGB gibanja?",
      "Kaj pravi trenutna raziskava o prekrivanju med lastnostmi avtizem spektra, disforijo spola in transspolnimi identitetami?",
      "Zakaj disforija spola ni več klasificirana kot duševna motnja v DSM-5?",
      "Kako se je pogostnost trans spola spremenila v zadnjem času in kaj bi to lahko razložilo?",
    ],
  },
  {
    title: "Splošni izrazi",
    description: "Razumevanje temeljnih konceptov",
    questions: [
      "Kaj je moški?",
      "Kaj je ženska?",
      "Kaj je spol?",
      "Kaj je disforija spola?",
      "Kaj je transspolna identiteta?",
      "Kaj je transfobija?",
      "Kaj je kultura preklica?",
      "Kaj je nebinarna identiteta?",
      "Kaj je queer identiteta?",
      "Kaj je teorija queer?",
      "Kaj je osebnost?",
      "Kako se osebnost razlikuje od spolne identitete?",
      "Kaj je nekonformnost s spolom (GNC)?",
      "Kaj je konformnost s spolom?",
      "Kaj je detranzicija?",
      "Kaj je opustitev?",
      "Kaj so zaimki in zakaj so pomembni za nekatere?",
      "Kaj transspolne osebe mislijo, ko govorijo o ‚trans pravicah'?",
      "Zakaj nekatere trans osebe pravijo ‚raje smrt kot detranzicija'?",
      "Kateri dejavniki se štejejo za vzroke disforije?",
      "Kaj je ‚Biblija o disforiji spola'?",
      "Katere strategije (medicinske ali ne-medicinske) pomagajo ljudem pri obvladovanju disforije?",
      "Ali so interspolne osebe samodejno trans?",
      "Kaj je spolna fluidnost?",
      "Kaj pomenita AFAB in AMAB?",
      "Kaj je TERF?",
      "Kaj je mrtvo imenovanje?",
      "Kaj je napačno spolno poimenovanje?",
      "Kaj je cisspolna oseba?",
      "Kaj pomeni biološki spol?",
      "Kakšna je razlika med družbeno in medicinsko tranzicijo?",
    ],
  },
  {
    title: "Medicinska realnost",
    description: "Zdravje, posegi in biološke resnice",
    questions: [
      "Kakšni so neželeni učinki uporabe testosterona pri ženskah?",
      "Kakšni so neželeni učinki uporabe estrogena pri moških?",
      "Kakšne fiziološke spremembe lahko testosteron povzroči pri ženskah in kje so meje?",
      "Kakšne fiziološke spremembe lahko estrogen povzroči pri moških in kje so meje?",
      "Kaj obsega faloplastika in kakšni so tipični izidi?",
      "Kaj obsega vaginoplastika in kakšni so tipični izidi?",
      "Katere različne vrste vaginoplastike obstajajo?",
      "Kako naj nekdo pretehta nadaljevanje ali prekinitev jemanja hormonov?",
      "Ali obstajajo merljive razlike v stopnjah diagnoze disforije spola med moškimi in ženskami?",
      "Kaj pravijo raziskave slikanja možganov o ‚moških' v primerjavi z ‚ženskimi' možgani?",
      "Kako se disforija spola razlikuje od duševne bolezni v diagnostičnih priročnikih?",
      "Kaj je vaginalna atrofija in kaj jo povzroča?",
      "Katere kirurške revizijske možnosti obstajajo za vaginoplastiko ali faloplastiko?",
      "Kako različne države urejajo javno financiranje spolnih operacij?",
      "Katere možnosti obstajajo za rekonstrukcijo prsi po mastektomiji?",
      "Kaj so zaviralci pubertete in ali res samo zaustavijo puberteto?",
      "Ali je res, da so zaviralci pubertete enako zdravilo, ki se uporablja za kemično kastracijo spolnih prestopnikov?",
      "Katere dolgoročne podatke o sledenju obstajajo za uporabo hormonov nasprotnega spola?",
      "Kaj so standardi skrbi WPATH in kako so razviti?",
      "Kaj je nizozemski protokol?",
      "Kaj je hitro nastala disforija spola (ROGD) in kako se raziskuje?",
      "Kakšne so poročane stopnje obžalovanja za različne spolne operacije?",
      "Kako izgleda raziskovalna terapija spola v praksi?",
    ],
  },
  {
    title: "Družba in kultura",
    description: "Kako se prepričanja o spolu interakcijo s svetom",
    questions: [
      "Kakšne so posledice narativa ‚rojeni tako'?",
      "Ali so spolne identitete preoblikovanje in krepitev seksističnih stereotipov?",
      "Kako se je mainstream feminizem spremenil skozi čas, da bi sprejel transspolne identitete?",
      "Kako lahko kultura zaimkov vodi k prekomerni medikalizaciji otrok?",
      "Kakšni so dokumentirani izidi za otroke, ki zgodaj opravijo družbeno tranzicijo?",
      "Kakšne povezave obstajajo med BDSM in trans identitetami?",
      "Kako se je koncept spola zgodovinsko razvil?",
      "Kako se je trans aktivizem interakcijal s prejšnjim aktivizmom za pravice gejev?",
      "Kako vplivajo repetitivne mantre ali sloganji na kritično razmišljanje v kateri koli skupnosti?",
      "Kako se sodobna spolna razprava križa z gejevskimi in lezbičnimi identitetami?",
      "Kaj bi lahko pojasnilo porast nebinarne identifikacije?",
      "Katere razlage obstajajo za povečano tveganje samomora v trans populacijah?",
      "Kako vpliva zaznano tveganje samomora na javno razpravo o tranziciji?",
      "Kaj pomeni ‚spolno kritičen' in kako se razlikuje od trans-izključujočih pogledov?",
      "Kaj je ‚razprava o straniščih' in kateri dokazi obstajajo za škodo ali varnost?",
      "Kakšni so glavni argumenti v kontroverzi o udeležbi v športu?",
      "Kako so se šole v različnih jurisdikcijah spopadle z učenci, ki sprašujejo o spolu?",
      "Kaj ljudje z izkušnjo detranzicije mislijo o pripovedovanju zgodb drag queen?",
      "Kaj pomeni izraz ‚medikalizacija otrok, ki so nekonformni s spolom' za kritike in zagovornike?",
    ],
  },
  {
    title: "Psihologija in identiteta",
    description: "Razumevanje duševnih in čustvenih vidikov",
    questions: [
      "Ali lahko nekdo postane ženska, ne da bi bil ženstven, ali moški, ne da bi bil moški?",
      "Kakšno vlogo igrajo družbena omrežja pri sprejemanju spolnih identitet?",
      "Kaj je nevrokemični cikel potrjevanja?",
      "Zakaj bi lahko bili avtistični ljudje prekomerno zastopani v spolnih klinikah?",
      "Kaj je internaliziran seksizem in kako bi lahko bil povezan s stisko telesa?",
      "Kaj je internalizirana homofobija?",
      "Kaj je avtoginefilija in kako se razpravlja o njej v literaturi?",
      "Kaj je spolna evforija?",
      "Ali lahko prevzemanje trans identitete okrepi disforijo namesto da jo olajša?",
      "Zakaj je zunanje potrjevanje pomembno za nekatere trans osebe?",
      "Kakšna je razlika med motnjo telesne dismorfije in disforijo spola?",
      "Kakšne vzporednice zdravniki potegnejo med disforijo spola in motnjami prehranjevanja?",
      "Kako bi lahko zgodovine travme interakcijale z disforijo spola?",
      "Katere ne-medicinske možnosti obstajajo za obvladovanje disforije?",
      "Kaj pomeni ‚passing' in zakaj lahko postane obsesija za nekatere ljudi?",
      "Kako se jungijanski koncepti anime/animusa nanašajo na spolno identiteto?",
      "Kaj je delo s senco (Shadow Work) in ali se lahko uporablja v terapiji?",
    ],
  },
  {
    title: "Pot detranzicije",
    description: "Ozdravitev, podpora in iskanje poti nazaj",
    questions: [
      "Kako se lahko sprijaznim s trajnim spremembami, ki sem jih naredil na svojem telesu?",
      "Imam občutek, da nekateri ljudje mislijo, da sem se preprosto ‚vrnil v omaro' in da ne živim pristno",
      "Ali je res, da večina ljudi z izkušnjo detranzicije na koncu ponovno opravi tranzicijo?",
      "Kako lahko tranzicija in detranzicija obe delujeta kot del istega potovalnega ozdravljenja?",
      "Kje lahko nekdo najde terapevte z izkušnjami pri podpori detranzicije?",
      "Ali detranzicija pomeni, da je bila izvirna tranzicija neuspeh?",
      "Ali je CBT ali DBT pomagal ljudem z izkušnjo detranzicije pri obvladovanju disforije?",
      "Zakaj nekatere trans skupnosti odvračajo od branja narativov o detranziciji?",
      "Katere podporne skupine obstajajo posebej za ljudi, ki opravljajo detranzicijo?",
      "Kako lahko nekdo (ponovno) pride iz omare družini kot oseba, ki opravlja detranzicijo?",
      "Katere so pogoste faze žalovanja, ki se poročajo med detranzicijo?",
      "Kakšno vlogo so imeli psihedeliki v nekaterih zgodbah o detranziciji?",
    ],
  },
  {
    title: "Akademska in raziskovalna pristranskost",
    description: "Vprašanje narativa v institucijah",
    questions: [
      "Katere metodološke pomisleke so izrazili glede večjih anket o detranziciji?",
      "Zakaj raziskovalci poročajo o težavah pri zagotavljanju financiranja za študije o detranziciji?",
      "Ali imajo raziskovalci, ki se trenutno identificirajo kot trans, navzkrižje interesov?",
      "Kaj je bila Cass Review in kakšna priporočila je dala?",
      "Kaj se je zgodilo s študijo Lise Littman iz leta 2018 o ROGD?",
      "Kaj je pregled klinike Tavistock in zakaj je bil naročen?",
      "Kako je bila disforija spola med DSM-IV in DSM-5 preklasificirana?",
    ],
  },
  {
    title: "Kontroverzne perspektive",
    description:
      "Detrans perspektive, ki jih spolni aktivisti resnično ne želijo, da jih slišite",
    questions: [
      "Kdo zasluži denar s skrbjo, ki potrjuje spol?",
      "Kateri strukturni dejavniki vodijo v podreprezentiranost zgodb o detranziciji v mainstream medijih?",
      "Na katere načine se sistemi prepričanj o spolu podobajo religijam ali kultom?",
      "Ali šole postavljajo starše ob stran, ko otroci sprejemajo odločitve o spolni identiteti?",
      "Zakaj je na Tajskem toliko ladyboyev?",
      "Zakaj je Iran globalno središče za operacije spremembe spola?",
    ],
  },
];
