// Italian translation of questions
// Note: Gender-related terms are preserved from English where they are technical terms,
// with Italian explanations provided in parentheses where helpful

export const questionCategories = [
  {
    title: "Domande in Evidenza",
    description: "Le migliori domande da fare alle persone detrans.",
    questions: [
      "Cosa significa trans?",
      "Le persone trans sono sempre esistite?",
      "È vero che solo l'1% fa detransizione?",
      "I bloccanti della pubertà sono reversibili?",
      "Quali prove esistono per i protocolli medici di affermazione di genere?",
      "Cosa significa il termine 'uovo' ('egg') nelle comunità trans?",
      "Quali sono le implicazioni della narrazione 'nato così'?",
      "Come le etichette non-binarie rinforzano gli stereotipi di genere tradizionali?",
      "Qual è la differenza tra sesso (sex) e genere (gender)?",
      "Cos'è la disforia di genere (gender dysphoria) e cosa può causarla?",
      "Perché alcune persone decidono di fare detransizione?",
      "Come possono amici o familiari sostenere qualcuno che vuole fare transizione?",
      "Come possono amici o familiari sostenere qualcuno che vuole fare detransizione?",
      "È comune che le persone detrans rimpiangano la transizione?",
      "Perché alcune persone decidono di rifare transizione dopo la detransizione?",
      "Cosa possono insegnarmi le storie detrans, anche se la mia transizione sta andando bene finora?",
      "Come faccio a sapere se i dubbi sono solo nervosismo o un segno che dovrei smettere?",
      "Perché le narrazioni trans sul perché le persone fanno detransizione differiscono da chi ha effettivamente fatto detransizione?",
      "Le persone detrans pensano che la transizione stessa sia cattiva?",
      "Quali sono alcune affermazioni false fatte sulle persone transgender?",
      "Quali sono alcune affermazioni false fatte sulle persone che hanno fatto detransizione?",
      "Quali segnali precoci le persone detrans desiderano aver notato prima?",
      "Il genere (gender) è un costrutto sociale? Cosa significa questo?",
      "Come hanno visto storicamente i movimenti femministi il concetto di genere?",
      "Come può la non conformità di genere ridurre la pressione a conformarsi ai ruoli di genere?",
      "Come descrivono le persone detrans la sensazione di essere 'nate nel corpo sbagliato'?",
      "Cos'è la cura di affermazione di genere (gender-affirming care) e quali sono i suoi obiettivi?",
      "Perché la cura di affermazione di genere è solitamente l'unica opzione nella maggior parte delle regioni?",
      "In che modo la terapia esplorativa di genere (gender-exploratory therapy) differisce dalla cura di affermazione di genere?",
      "Perché alcune persone non amano il concetto di terapia esplorativa di genere, e perché è vietata in alcuni posti?",
      "Le persone detrans pensano che la cura di affermazione di genere e gli ormoni dovrebbero essere vietati?",
      "Le persone che fanno detransizione di solito rimpiangono i passaggi medici, quelli sociali, o entrambi?",
      "Cos'è una trappola identitaria (identity trap) e come le persone tipicamente si rendono conto di essere in una?",
      "Dove può cercare qualcuno un terapeuta che offre esplorazione di genere aperta e non direttiva? Quali segnali di pericolo dovrei cercare?",
      "Chiedere i pronomi aiuta o ostacola le persone non conformi di genere?",
      "Se una ragazza giovane con i capelli corti viene costantemente chiesta dei suoi pronomi, qual è l'implicazione e come si sentirebbe?",
      "Cos'è la cultura della cancellazione (cancel culture) e quali effetti ha sul discorso di salute pubblica?",
      "Le persone detrans vedono la transizione come avendo un punto finale o come un processo continuo?",
      "Perché alcune ragazze adolescenti potrebbero provare disagio per lo sviluppo del seno?",
      "Come possono le camere di risonanza online influenzare la formazione dell'identità?",
      "Perché le persone che fanno detransizione spesso riferiscono di sentire che le loro storie e voci sono silenziate sia negli spazi trans che mainstream?",
      "Quali modelli demografici sono visibili nei rinvii alle cliniche di genere?",
      "In che modo le identità queer contemporanee differiscono dal precedente movimento LGB?",
      "Cosa dice la ricerca attuale sulla sovrapposizione tra tratti dello spettro autistico, disforia di genere e identità transgender?",
      "Perché la disforia di genere non è più classificata come disturbo mentale nel DSM-5?",
      "Come è cambiata la prevalenza trans nei tempi recenti e cosa potrebbe spiegarlo?",
    ],
  },
  {
    title: "Termini Generali",
    description: "Comprendere i concetti fondamentali",
    questions: [
      "Cos'è un uomo?",
      "Cos'è una donna?",
      "Cos'è il genere (gender)?",
      "Cos'è la disforia di genere (gender dysphoria)?",
      "Cos'è l'identità transgender?",
      "Cos'è la transfobia (transphobia)?",
      "Cos'è la cultura della cancellazione (cancel culture)?",
      "Cos'è l'identità non-binaria (non-binary)?",
      "Cos'è l'identità queer?",
      "Cos'è la teoria queer (queer theory)?",
      "Cos'è la personalità?",
      "In che modo la personalità differisce dall'identità di genere?",
      "Cos'è la non conformità di genere (GNC - Gender Non-Conformity)?",
      "Cos'è la conformità di genere?",
      "Cos'è la detransizione (detransitioning)?",
      "Cos'è il desistere (desisting)?",
      "Cosa sono i pronomi e perché sono significativi per alcuni?",
      "Cosa intendono le persone trans quando parlano di 'diritti trans'?",
      "Perché alcune persone trans dicono 'morte prima della detransizione'?",
      "Quali fattori si pensa causino la disforia?",
      "Cos'è la 'bibbia della disforia di genere' (gender dysphoria bible)?",
      "Quali strategie (mediche o non mediche) aiutano le persone a gestire la disforia?",
      "Le persone intersex sono automaticamente trans?",
      "Cos'è la fluidità di genere (gender fluidity)?",
      "Cosa significano AFAB e AMAB?",
      "Cos'è un TERF?",
      "Cos'è il deadnaming?",
      "Cos'è il misgendering?",
      "Cos'è una persona cisgender (cisgender)?",
      "Cosa si intende per sesso biologico (biological sex)?",
      "Qual è la differenza tra transizione sociale e transizione medica?",
    ],
  },
  {
    title: "La Realtà Medica",
    description: "Salute, procedure e verità biologiche",
    questions: [
      "Quali sono gli effetti avversi dell'uso di testosterone nelle femmine?",
      "Quali sono gli effetti avversi dell'uso di estrogeno nei maschi?",
      "Quali cambiamenti fisiologici può indurre il testosterone nelle femmine e quali sono i limiti?",
      "Quali cambiamenti fisiologici può indurre l'estrogeno nei maschi e quali sono i limiti?",
      "Cosa comporta la falloplastica (phalloplasty) e quali sono i risultati tipici?",
      "Cosa comporta la vaginoplastica (vaginoplasty) e quali sono i risultati tipici?",
      "Quali sono i diversi tipi di chirurgia vaginoplastica?",
      "Come dovrebbe qualcuno valutare se continuare o interrompere gli ormoni?",
      "Ci sono differenze misurabili nei tassi di diagnosi di disforia di genere tra maschi e femmine?",
      "Cosa dice la ricerca sull'imaging cerebrale sui cervelli 'maschili' versus 'femminili'?",
      "Come viene distinta la disforia di genere dalla malattia mentale nei manuali diagnostici?",
      "Cos'è l'atrofia vaginale e cosa la causa?",
      "Quali opzioni di revisione chirurgica esistono per la vaginoplastica o la falloplastica?",
      "Come i diversi paesi regolano il finanziamento pubblico per le chirurgie di genere?",
      "Quali opzioni esistono per la ricostruzione del torace dopo la mastectomia?",
      "Cosa sono i bloccanti della pubertà e mettono davvero in pausa solo la pubertà?",
      "È vero che i bloccanti della pubertà sono lo stesso farmaco usato per castrare chimicamente i colpevoli di reati sessuali?",
      "Quali dati di follow-up a lungo termine esistono per l'uso di ormoni cross-sesso?",
      "Cosa sono gli Standard di Cura WPATH e come vengono sviluppati?",
      "Cos'è il Protocollo Olandese (Dutch Protocol)?",
      "Cos'è la disforia di genere a esordio rapido (ROGD - Rapid-Onset Gender Dysphoria) e come viene studiata?",
      "Quali sono i tassi di rimpianto riportati per le varie chirurgie di genere?",
      "Come appare in pratica la terapia esplorativa di genere (gender-exploratory therapy)?",
    ],
  },
  {
    title: "Società e Cultura",
    description: "Come le credenze di genere interagiscono con il mondo",
    questions: [
      "Quali sono le implicazioni della narrazione 'nato così'?",
      "Le identità di genere stanno reimpacchettando e rinforzando gli stereotipi sessisti?",
      "Come è cambiato il femminismo mainstream nel tempo per accogliere le identità transgender?",
      "Come può la cultura dei pronomi portare alla sovra-medicalizzazione dei bambini?",
      "Quali sono i risultati documentati per i bambini che fanno transizione sociale precoce?",
      "Quali sono i collegamenti tra BDSM e identità trans?",
      "Come è evoluto il concetto di genere storicamente?",
      "Come ha interagito l'attivismo trans con l'attivismo precedente per i diritti gay?",
      "Come influenzano i mantra o slogan ripetitivi il pensiero critico in qualsiasi comunità?",
      "In che modo il discorso contemporaneo sul genere interseca con le identità gay e lesbiche?",
      "Cosa potrebbe spiegare l'aumento dell'identificazione non-binaria?",
      "Quali spiegazioni esistono per l'elevato rischio di suicidio nelle popolazioni trans?",
      "Come il rischio di suicidio percepito influenza il discorso pubblico sulla transizione?",
      "Cosa significa 'critico del genere' (gender-critical) e come differisce dalle vedute trans-esclusionarie?",
      "Cos'è il 'dibattito sui bagni' (bathroom debate) e quali prove esistono per danno o sicurezza?",
      "Quali sono gli argomenti principali nella controversia sulla partecipazione sportiva?",
      "Come hanno gestito le scuole gli studenti che si interrogano sul genere in diverse giurisdizioni?",
      "Cosa pensano le persone detrans dello storytelling delle drag queen?",
      "Cosa significa la frase 'medicalizzazione dei bambini non conformi di genere' per i critici e per i sostenitori?",
    ],
  },
  {
    title: "Psicologia e Identità",
    description: "Comprendere gli aspetti mentali ed emotivi",
    questions: [
      "Qualcuno può essere una donna senza essere femminile, o un uomo senza essere mascolino?",
      "Che ruolo giocano i social media nell'adozione di identità di genere?",
      "Qual è il ciclo neurochimico della convalida?",
      "Perché le persone autistiche potrebbero essere sovrarappresentate nelle cliniche di genere?",
      "Cos'è la misoginia interiorizzata (internalised misogyny) e come potrebbe relazionarsi al disagio corporeo?",
      "Cos'è l'omofobia interiorizzata (internalised homophobia)?",
      "Cos'è l'autoginefilia (autogynephilia) e come è dibattuta nella letteratura?",
      "Cos'è l'euforia di genere (gender euphoria)?",
      "L'adozione di un'identità trans può amplificare la disforia invece di alleviarla?",
      "Perché la convalida esterna è importante per alcune persone trans?",
      "Qual è la differenza tra disturbo dismorfico corporeo (BDD) e disforia di genere?",
      "Quali paralleli traggono i clinici tra disforia di genere e disturbi alimentari?",
      "Come potrebbero interagire le storie di trauma con la disforia di genere?",
      "Quali opzioni non mediche esistono per gestire la disforia?",
      "Cosa significa 'passing' e perché può diventare un'ossessione per alcune persone?",
      "Come i concetti junghiani di anima/animus si relazionano all'identità di genere?",
      "Cos'è il lavoro sull'ombra (shadow work) e può essere usato in terapia?",
    ],
  },
  {
    title: "Il Viaggio della Detransizione",
    description: "Guarigione, supporto e trovare la propria strada",
    questions: [
      "Come posso fare pace con i cambiamenti permanenti che ho fatto al mio corpo?",
      "Mi sento come se alcune persone pensino che sono solo 'tornata nell'armadio' e che non sto vivendo autenticamente",
      "È vero che la maggior parte delle persone detrans finiscono per rifare transizione?",
      "Come possono la transizione e la detransizione essere entrambe parte dello stesso viaggio di guarigione?",
      "Dove può trovare qualcuno terapeuti esperti nel supporto alla detransizione?",
      "La detransizione significa che la transizione originale era un fallimento?",
      "CBT o DBT hanno aiutato le persone detrans nella gestione della disforia?",
      "Perché alcune comunità trans scoraggiano la lettura delle narrazioni di detransizione?",
      "Quali gruppi di supporto esistono specificamente per chi fa detransizione?",
      "Come può qualcuno fare coming out (di nuovo) alla famiglia come detransizionante?",
      "Quali sono le fasi comuni del lutto riportate durante la detransizione?",
      "Che ruolo hanno avuto le droghe psichedeliche in alcune storie detrans?",
    ],
  },
  {
    title: "Bias Accademico e di Ricerca",
    description: "Mettere in discussione la narraziva nelle istituzioni",
    questions: [
      "Quali preoccupazioni metodologiche sono state sollevate sui principali sondaggi sulla detransizione?",
      "Perché i ricercatori riferiscono difficoltà nel garantire finanziamenti per studi sulla detransizione?",
      "I ricercatori che attualmente si identificano come trans hanno un conflitto di interessi?",
      "Cos'era la Cass Review e quali raccomandazioni ha prodotto?",
      "Cosa è successo allo studio del 2018 di Lisa Littman sulla ROGD?",
      "Cos'è la revisione della clinica Tavistock e perché è stata commissionata?",
      "Come è stata riclassificata la disforia di genere tra DSM-IV e DSM-5?",
    ],
  },
  {
    title: "Prospettive Controverse",
    description:
      "Prospettive detrans che gli attivisti di genere non vogliono assolutamente che tu senta",
    questions: [
      "Chi sta facendo soldi con la cura di affermazione di genere?",
      "Quali fattori strutturali portano alla sottorappresentazione delle storie di detransizione nei media mainstream?",
      "In che modo i sistemi di credenze di genere assomigliano a religioni o sette?",
      "Le scuole stanno mettendo da parte i genitori quando i bambini fanno scelte sull'identità di genere?",
      "Perché ci sono così tante ladyboy in Thailandia?",
      "Perché l'Iran è un hub globale per le chirurgie di riassegnazione del sesso?",
    ],
  },
];
