/**
 * Nederlandse vraagcategorieën en uitgelichte vragen voor detrans.ai
 *
 * Opmerkingen over Gender-Gerelateerde Terminologie:
 * - "Geslacht" (Sex) = biologisch geslacht (anatomie, chromosomen, voortplanting, onveranderlijke kenmerken)
 * - "Gender" = sociale gender (rollen, gedragingen, attributen die de samenleving passend acht
 *   voor mannen en vrouwen op basis van hun biologisch geslacht)
 * - "Genderidentiteit" = intern gevoel man, vrouw of ergens daartussenin te zijn
 * - "Gender non-conformiteit (GNC)" = wanneer een persoon handelt/presenteert anders dan de samenleving
 *   verwacht op basis van hun biologisch geslacht
 * - "AFAB/AMAB" = assigned female/male at birth (vrouw/man toegewezen bij geboorte, gebaseerd op geobserveerd biologisch geslacht)
 * - "Transgender/trans" = identificeren met een gender dat verschilt van het biologisch geslacht
 * - "Detransitie" = stoppen met identificeren als transgender en/of transitiestappen terugdraaien
 * - "Desisteren" = wanneer iemand die zich als trans identificeerde (zonder medische ingrepen) niet meer
 *   als trans identificeert
 *
 * Belangrijk onderscheid: Genderdysforie als concept steunt op het begrip dat biologisch geslacht
 * en sociale gender verschillend zijn. Gender non-conformiteit (niet passen in stereotypen) is
 * anders dan een genderidentiteit hebben die verschilt van het biologisch geslacht.
 */

export const questionCategories = [
  {
    title: "Uitgelichte Vragen",
    description: "De beste vragen om aan detrans mensen te stellen.",
    questions: [
      "Wat betekent trans?",
      "Hebben trans mensen altijd bestaan?",
      "Is het waar dat slechts 1% detransitioneert?",
      "Zijn puberteitsremmers omkeerbaar?",
      "Welk bewijs bestaat er voor genderbevestigende medische protocollen?",
      "Wat betekent de term 'ei' in trans gemeenschappen?",
      "Wat zijn de implicaties van het 'zo geboren' narratief?",
      "Hoe versterken non-binaire labels traditionele genderstereotypen?",
      "Wat is het verschil tussen geslacht en gender?",
      "Wat is genderdysforie en wat kan het veroorzaken?",
      "Waarom beslissen sommige mensen te detransitioneren?",
      "Hoe kunnen vrienden of familie iemand ondersteunen die wil transitioneren?",
      "Hoe kunnen vrienden of familie iemand ondersteunen die wil detransitioneren?",
      "Is het gebruikelijk dat detransitioners spijt hebben van het transitioneren?",
      "Waarom beslissen sommige mensen om opnieuw te transitioneren na detransitie?",
      "Wat kunnen detrans verhalen me leren, zelfs als mijn transitie tot nu toe goed gaat?",
      "Hoe weet ik of twijfels gewoon zenuwen zijn of een teken dat ik moet stoppen?",
      "Waarom verschillen trans verhalen over waarom mensen detransitioneren van degenen die daadwerkelijk zijn gedetransitioneerd?",
      "Vinden detrans mensen dat transitie zelf slecht is?",
      "Wat zijn enkele valse beweringen over transgender mensen?",
      "Wat zijn enkele valse beweringen over mensen die zijn gedetransitioneerd?",
      "Welke vroege signalen wensen detrans mensen dat ze eerder hadden opgemerkt?",
      "Is gender een sociaal construct? Wat betekent dit?",
      "Hoe hebben feministische bewegingen historisch naar het concept gender gekeken?",
      "Hoe kan gender-non-conformiteit de druk om te voldoen aan genderrollen verminderen?",
      "Hoe beschrijven detrans mensen het gevoel 'in het verkeerde lichaam geboren' te zijn?",
      "Wat is genderbevestigende zorg en wat zijn de doelen ervan?",
      "Waarom is genderbevestigende zorg meestal de enige optie in de meeste regio's?",
      "Hoe verschilt gender-verkennende therapie van genderbevestigende zorg?",
      "Waarom houden sommige mensen niet van het concept gender-verkennende therapie, en waarom is het in sommige plaatsen verboden?",
      "Vinden detrans mensen dat genderbevestigende zorg en hormonen verboden moeten worden?",
      "Hebben detransitioners meestal spijt van medische stappen, sociale stappen, of beide?",
      "Wat is een identiteitsval en hoe realiseren mensen zich doorgaans dat ze erin zitten?",
      "Waar kan iemand naar een therapeut zoeken die open einde, niet-richtinggevende genderverkenning biedt? Waar moet ik op letten als rode vlaggen?",
      "Helpt het vragen naar voornaamwoorden gender-non-conforme mensen of hindert het hen?",
      "Als een jong meisje met kort haar constant naar haar voornaamwoorden wordt gevraagd, wat is de implicatie en hoe zou dit haar doen voelen?",
      "Wat is cancelcultuur en welke effecten heeft het op het publieke gezondheidsdiscours?",
      "Zien detrans mensen transitie als een eindpunt of als een doorlopend proces?",
      "Waarom zouden sommige adolescente meisjes distress kunnen ervaren over borstontwikkeling?",
      "Hoe kunnen online echokamers identiteitsvorming beïnvloeden?",
      "Waarom rapporteren detransitioners vaak dat ze het gevoel hebben dat hun verhalen en stemmen worden gedempt in zowel trans als mainstream ruimtes?",
      "Welke demografische patronen zijn zichtbaar in verwijzingen naar genderklinieken?",
      "Hoe verschillen hedendaagse queer identiteiten van de eerdere LGB-beweging?",
      "Wat zegt het huidige onderzoek over overlap tussen autisme spectrum kenmerken, genderdysforie en transgender identiteiten?",
      "Waarom wordt genderdysforie niet langer geclassificeerd als een mentale stoornis in de DSM-5?",
      "Hoe is trans prevalentie veranderd in recente tijden en wat zou dit kunnen verklaren?",
    ],
  },
  {
    title: "Algemene Termen",
    description: "De fundamentele concepten begrijpen",
    questions: [
      "Wat is een man?",
      "Wat is een vrouw?",
      "Wat is gender?",
      "Wat is genderdysforie?",
      "Wat is transgender identiteit?",
      "Wat is transfobie?",
      "Wat is cancelcultuur?",
      "Wat is non-binaire identiteit?",
      "Wat is queer identiteit?",
      "Wat is queer theorie?",
      "Wat is persoonlijkheid?",
      "Hoe verschilt persoonlijkheid van genderidentiteit?",
      "Wat is gender non-conformiteit (GNC)?",
      "Wat is genderconformiteit?",
      "Wat is detransitie?",
      "Wat is desisteren?",
      "Wat zijn voornaamwoorden en waarom zijn ze belangrijk voor sommigen?",
      "Wat bedoelen trans mensen wanneer ze over 'trans rechten' praten?",
      "Waarom zeggen sommige trans mensen 'dood voor detransitie'?",
      "Welke factoren worden verondersteld dysforie te veroorzaken?",
      "Wat is de 'genderdysforie bijbel'?",
      "Welke strategieën (medisch of niet-medisch) helpen mensen dysforie te beheersen?",
      "Zijn intersekse mensen automatisch trans?",
      "Wat is genderfluïditeit?",
      "Wat betekenen AFAB en AMAB?",
      "Wat is een TERF?",
      "Wat is deadnamen?",
      "Wat is misgendern?",
      "Wat is een cisgender persoon?",
      "Wat wordt bedoeld met biologisch geslacht?",
      "Wat is het verschil tussen sociale en medische transitie?",
    ],
  },
  {
    title: "De Medische Realiteit",
    description: "Gezondheid, ingrepen en biologische waarheden",
    questions: [
      "Wat zijn de nadelige effecten van testosterongebruik bij vrouwen?",
      "Wat zijn de nadelige effecten van oestrogeengebruik bij mannen?",
      "Welke fysiologische veranderingen kan testosteron induceren bij vrouwen en wat zijn de limieten?",
      "Welke fysiologische veranderingen kan oestrogeen induceren bij mannen en wat zijn de limieten?",
      "Wat houdt falloplastiek in en wat zijn typische resultaten?",
      "Wat houdt vaginoplastiek in en wat zijn typische resultaten?",
      "Wat zijn de verschillende soorten vaginoplastiek chirurgie?",
      "Hoe moet iemand doorgaan versus stoppen met hormonen afwegen?",
      "Zijn er meetbare verschillen in genderdysforie diagnosepercentages tussen mannen en vrouwen?",
      "Wat zegt hersenonderzoek over 'mannelijke' versus 'vrouwelijke' hersenen?",
      "Hoe wordt genderdysforie onderscheiden van mentale ziekte in diagnostische handleidingen?",
      "Wat is vaginale atrofie en wat veroorzaakt het?",
      "Welke chirurgische revisie opties bestaan er voor zowel vaginoplastiek als falloplastiek?",
      "Hoe reguleren verschillende landen publieke financiering voor genderchirurgie?",
      "Welke opties bestaan er voor borstreconstructie na mastectomie?",
      "Wat zijn puberteitsremmers en pauzeren ze echt alleen puberteit?",
      "Is het waar dat puberteitsremmers hetzelfde medicijn zijn dat wordt gebruikt om zedendelinquenten chemisch te castreren?",
      "Welke langetermijn follow-up gegevens bestaan er voor cross-sex hormoongebruik?",
      "Wat zijn de WPATH Standaarden van Zorg en hoe worden ze ontwikkeld?",
      "Wat is het Nederlandse Protocol?",
      "Wat is rapid-onset gender dysforie (ROGD) en hoe wordt het bestudeerd?",
      "Wat zijn gerapporteerde spijtpercentages voor verschillende genderchirurgische ingrepen?",
      "Hoe ziet gender-verkennende therapie er in de praktijk uit?",
    ],
  },
  {
    title: "Samenleving & Cultuur",
    description: "Hoe genderovertuigingen interageren met de wereld",
    questions: [
      "Wat zijn de implicaties van het 'zo geboren' narratief?",
      "Zijn genderidentiteiten seksistische stereotypen opnieuw verpakt en versterkend?",
      "Hoe is de mainstream feminisme veranderd in de loop der tijd om transgender identiteiten te accommoderen?",
      "Hoe kan voornaamwoordencultuur leiden tot over-medicalisering van kinderen?",
      "Wat zijn gedocumenteerde resultaten voor kinderen die vroeg sociaal transitioneren?",
      "Wat zijn de verbanden tussen BDSM en trans identiteiten?",
      "Hoe is het concept gender historisch geëvolueerd?",
      "Heeft trans activisme interactie gehad met eerdere homorechtenactivisme?",
      "Hoe beïnvloeden repetitieve mantra's of slogans kritisch denken in elke gemeenschap?",
      "Hoe snijdt hedendaags genderdiscours homo- en lesbische identiteiten aan?",
      "Wat zou de toename in non-binaire identificatie kunnen verklaren?",
      "Welke verklaringen bestaan er voor verhoogd zelfmoordrisico in trans populaties?",
      "Hoe beïnvloedt het waargenomen zelfmoordrisico het publieke discours rond transitie?",
      "Wat betekent 'gender-kritisch' en hoe verschilt het van trans-uitsluitende opvattingen?",
      "Wat is het 'badkamerdebat' en welk bewijs bestaat er voor schade of veiligheid?",
      "Wat zijn de belangrijkste argumenten in de sportdeelname-controverse?",
      "Hoe hebben scholen omgegaan met gendervragende leerlingen in verschillende jurisdicties?",
      "Wat vinden detrans mensen van drag queen story telling?",
      "Wat betekent de zin 'medicalisering van gender-non-conforme kinderen' voor critici en voor pleitbezorgers?",
    ],
  },
  {
    title: "Psychologie & Identiteit",
    description: "De mentale en emotionele aspecten begrijpen",
    questions: [
      "Kan iemand een vrouw zijn zonder vrouwelijk te zijn, of een man zonder mannelijk te zijn?",
      "Welke rol speelt sociale media bij het aannemen van genderidentiteiten?",
      "Wat is de neurochemische cyclus van validatie?",
      "Waarom zouden autistische mensen oververtegenwoordigd kunnen zijn in genderklinieken?",
      "Wat is geïnternaliseerde misogynie en hoe zou dit kunnen samenhangen met lichaamsdistress?",
      "Wat is geïnternaliseerde homofobie?",
      "Wat is autogynefilie en hoe wordt het gedebatteerd in de literatuur?",
      "Wat is gender euforie?",
      "Kan het aannemen van een trans identiteit dysforie versterken in plaats van verlichten?",
      "Waarom is externe validatie belangrijk voor sommige trans mensen?",
      "Wat is het verschil tussen lichaamsdysmorfische stoornis en genderdysforie?",
      "Welke parallellen trekken clinici tussen genderdysforie en eetstoornissen?",
      "Hoe kunnen trauma-historieën interageren met genderdysforie?",
      "Welke niet-medische opties bestaan er voor het beheersen van dysforie?",
      "Wat betekent 'passen' en waarom kan het een obsessie worden voor sommige mensen?",
      "Hoe verhouden Jungiaanse concepten van anima/animus zich tot genderidentiteit?",
      "Wat is schaduwwerk en kan het worden gebruikt in therapie?",
    ],
  },
  {
    title: "Het Detransitie Traject",
    description: "Helen, ondersteuning en je weg terugvinden",
    questions: [
      "Hoe kan ik vrede maken met de permanente veranderingen die ik aan mijn lichaam heb aangebracht?",
      "Ik heb het gevoel dat sommige mensen denken dat ik gewoon 'terug de kast in ben gegaan' en dat ik niet authentiek leef",
      "Is het waar dat de meeste detrans mensen eindigen met opnieuw te transitioneren?",
      "Hoe kunnen transitie en detransitie beide deel uitmaken van hetzelfde helingspad?",
      "Waar kan iemand therapeuten met ervaring in detransitieondersteuning vinden?",
      "Betekent detransitie dat de originele transitie een mislukking was?",
      "Heeft CBT of DBT detrans mensen geholpen bij het beheersen van dysforie?",
      "Waarom ontmoedigen sommige trans gemeenschappen het lezen van detransitienarratieven?",
      "Welke ondersteuningsgroepen bestaan er specifiek voor detransitioners?",
      "Hoe kan iemand (opnieuw) uit de kast komen naar familie als detransitionering?",
      "Wat zijn veelvoorkomende stadia van rouw die tijdens detransitie worden gerapporteerd?",
      "Welke rol hebben psychedelische drugs gespeeld in sommige detrans verhalen?",
    ],
  },
  {
    title: "Academisch & Onderzoeksbevooroordeeldheid",
    description: "Het narratief in instituties in twijfel trekken",
    questions: [
      "Welke methodologische bezorgdheden zijn geuit over grote detransitie-enquêtes?",
      "Waarom rapporteren onderzoekers moeite om financiering voor detransitie-onderzoek te verkrijgen?",
      "Hebben onderzoekers die zich momenteel als trans identificeren een belangenverstrengeling?",
      "Wat was de Cass Review en welke aanbevelingen produceerde het?",
      "Wat is er gebeurd met Lisa Littman's studie uit 2018 over ROGD?",
      "Wat is de Tavistock kliniek review en waarom werd het opgestart?",
      "Hoe is genderdysforie geherclassificeerd tussen DSM-IV en DSM-5?",
    ],
  },
  {
    title: "Controversiële Perspectieven",
    description:
      "Detrans perspectieven die genderactivisten echt niet willen dat je hoort",
    questions: [
      "Wie verdient er geld aan genderbevestigende zorg?",
      "Welke structurele factoren leiden tot ondervertegenwoordiging van detransitieverhalen in mainstream media?",
      "Op welke manieren lijken genderovertuigingssystemen op religies of sekten?",
      "Zetten scholen ouders opzij wanneer kinderen keuzes maken over genderidentiteit?",
      "Waarom zijn er zoveel ladyboys in Thailand?",
      "Waarom is Iran een wereldwijd centrum voor geslachtsveranderingsoperaties?",
    ],
  },
];
