/**
 * Hungarian translation of question categories and featured questions
 * 
 * Gender-Related Terminology Notes:
 * - 'Nem' (biological sex) = biológiai nem (anatómia, kromoszómák, reprodukció)
 * - 'Gender' (social gender) = társadalmi nem (szerepek, viselkedés, társadalmi elvárások)
 * - 'Nemi identitás' (gender identity) = belső érzék, hogy valaki férfi, nő vagy valahol közöttük
 * - 'Nemi nem-konformitás (GNC)' = gender non-conformity (nem illeszkedik a társadalmi nem szerepekhez)
 * - 'AFAB/AMAB' = születési nőként/férfiként meghatározva (assigned female/male at birth)
 * - 'Transznemű/trans' = transgender (nem azonosul a születési nemével)
 * - 'Detransition/visszaátmenet' = nem transzneműként való azonosulás abbahagyása
 * - 'Desistance/leállás' = nem transzneműként való azonosulás abbahagyása orvosi beavatkozások nélkül
 * 
 * Important distinction: A nemi diszfória (gender dysphoria) megértéséhez elengedhetetlen 
 * a biológiai nem és a társadalmi nem megkülönböztetése. A nemi nem-konformitás 
 * (a sztereotípiákhoz való nem illeszkedés) különbözik attól, ha valaki nemi identitása 
 * eltér a biológiai nemétől.
 */

export const questionCategories = [
  {
    title: 'Kiemelt kérdések',
    description: 'A legjobb kérdések, amelyeket feltehet a detransitionereknek.',
    questions: [
      "Mit jelent a trans?",
      "Mindig is léteztek transznemű emberek?",
      "Igaz, hogy csak 1% hajt végre detransition-t?",
      "Visszafordíthatók a pubertásgátlók?",
      "Milyen bizonyítékok vannak a nemi azonosságot megerősítő orvosi protokollokra?",
      "Mit jelent a 'tojás' kifejezés a transznemű közösségekben?",
      "Mik a 'így születtem' narratíva következményei?",
      "Hogyan erősítik a nem-bináris címkék a hagyományos nemi sztereotípiákat?",
      "Mi a különbség a biológiai nem és a társadalmi nem között?",
      "Mi a nemi diszfória és mi okozhatja?",
      "Miért döntenek egyes emberek a detransition mellett?",
      "Hogyan tudják a barátok vagy családtagok támogatni azt, aki transition-t szeretne végezni?",
      "Hogyan tudják a barátok vagy családtagok támogatni azt, aki detransition-t szeretne végezni?",
      "Gyakori, hogy a detransitionerek megbánják a transition-t?",
      "Miért döntenek egyes emberek újra transition mellett a detransition után?",
      "Mit tanulhatok a detransitionerek történeteiből, még ha az én transition-om eddig jól is megy?",
      "Hogyan tudom megkülönböztetni, hogy a kétségek csak idegesség vagy figyelmeztetés arra, hogy le kellene állni?",
      "Miért különböznek a transznemű narratívák a detransition okairól azoktól, akik valóban átestek detransition-en?",
      "A detransitionerek szerint maga a transition rossz dolog?",
      "Mik azok a téves állítások a transznemű emberekről?",
      "Mik azok a téves állítások a detransitionerekre?",
      "Milyen korai jeleket kívánják, hogy a detransitionerek hamarabb észrevettek volna?",
      "A nem társadalmi konstrukció? Mit jelent ez?",
      "Hogyan tekintettek a feministák a nem fogalmára történelmileg?",
      "Hogyan csökkentheti a nemi nem-konformitás a nyomást a nemi szerepek betartására?",
      "Hogyan írják le a detransitionerek az 'rossz testbe született' érzést?",
      "Mi a nemi azonosságot megerősítő ellátás és mik a céljai?",
      "Miért a nemi azonosságot megerősítő ellátás az egyetlen lehetőség a legtöbb régióban?",
      "Miben különbözik a nemi felfedező terápia a nemi azonosságot megerősítő ellátástól?",
      "Miért utálják egyes emberek a nemi felfedező terápia fogalmát, és miért van tiltva egyes helyeken?",
      "A detransitionerek szerint betiltandó a nemi azonosságot megerősítő ellátás és a hormonok?",
      "A detransitionerek általában megbánják az orvosi lépéseket, a társadalmi lépéseket vagy mindkettőt?",
      "Mi az identitáscsapdázat és hogyan szokták az emberek felismerni, hogy benne vannak?",
      "Hol tud valaki olyan terapeutát találni, aki nyitott, nem irányított nemi felfedezést kínál? Mire figyeljek oda figyelmeztető jelzésként?",
      "Segít vagy hátráltatja a nemi nem-konform embereket a névmások megkérdezése?",
      "Ha egy fiatal lányt rövid hajjal folyamatosan a névmásairól kérdeznek, mi ennek a következménye és hogyan érezné magát?",
      "Mi a cancel culture és milyen hatásai vannak a közegészségügyi diskurzusra?",
      "A detransitionerek szerint a transition-nek van végpontja vagy folyamatos folyamat?",
      "Miért tapasztalhatnak néhány kamasz lány distresszt a mell fejlődése miatt?",
      "Hogyan befolyásolhatják az online visszhangkamrák az identitás kialakulását?",
      "Miért számolnak be a detransitionerek gyakran arról, hogy történeteik és hangjuk elhallgattatják őket mind a transznemű, mind a mainstream terekben?",
      "Milyen demográfiai mintázatok láthatók a nemi klinikákhoz való beutalásokban?",
      "Miben különböznek a kortárs queer identitások a korábbi LMB mozgalomtól?",
      "Mit mond a jelenlegi kutatás az autizmus spektrum jellemzői, a nemi diszfória és a transznemű identitások közötti átfedésről?",
      "Miért nem minősül már mentális zavarnak a nemi diszfória a DSM-5-ben?",
      "Hogyan változott a transzneműség gyakorisága az utóbbi időben és mi magyarázhatja ezt?",
    ],
  },
  {
    title: 'Általános fogalmak',
    description: 'Az alapvető fogalmak megértése',
    questions: [
      "Mi a férfi?",
      "Mi a nő?",
      "Mi a nem?",
      "Mi a nemi diszfória?",
      "Mi a transznemű identitás?",
      "Mi a transzfóbia?",
      "Mi a cancel culture?",
      "Mi a nem-bináris identitás?",
      "Mi a queer identitás?",
      "Mi a queer elmélet?",
      "Mi a személyiség?",
      "Miben különbözik a személyiség a nemi identitástól?",
      "Mi a nemi nem-konformitás (GNC)?",
      "Mi a nemi konformitás?",
      "Mi a detransition?",
      "Mi a leállás (desistance)?",
      "Mik a névmások és miért fontosak egyeseknek?",
      "Mit értenek a transznemű emberek a 'trans jogok' alatt?",
      "Miért mondják egyes transznemű emberek, hogy 'halál a detransition előtt'?",
      "Milyen tényezőket tekintenek a diszfória okainak?",
      "Mi a 'nemi diszfória bibliája'?",
      "Milyen stratégiák (orvosi vagy nem orvosi) segítenek az embereknek a diszfória kezelésében?",
      "A interszexuális emberek automatikusan transzneműek?",
      "Mi a nemi fluiditás?",
      "Mit jelentenek az AFAB és AMAB rövidítések?",
      "Mi a TERF?",
      "Mi a deadnaming?",
      "Mi a misgendering?",
      "Mi a cisznemű személy?",
      "Mit értünk biológiai nem alatt?",
      "Mi a különbség a társadalmi és az orvosi transition között?",
    ],
  },
  {
    title: 'Az orvosi valóság',
    description: 'Egészség, beavatkozások és biológiai igazságok',
    questions: [
      "Mik a női tesztoszteron-használat mellékhatásai?",
      "Mik a férfi ösztrogén-használat mellékhatásai?",
      "Milyen élettani változásokat idézhet elő a tesztoszteron a nőknél és mik a korlátok?",
      "Milyen élettani változásokat idézhet elő az ösztrogén a férfiaknál és mik a korlátok?",
      "Mit jelent a falloplasztika és mik a tipikus eredmények?",
      "Mit jelent a vaginoplasztika és mik a tipikus eredmények?",
      "Milyen különböző típusai vannak a vaginoplasztika műtétnek?",
      "Hogyan mérlegelje valaki a hormonok folytatását vagy abbahagyását?",
      "Vannak-e mérhető különbségek a nemi diszfória diagnózisának arányában férfiak és nők között?",
      "Mit mond az agyi képalkotó kutatás a 'férfi” versus 'női” agyakról?",
      "Hogyan különböztetik meg a nemi diszfóriát a mentális betegségektől a diagnosztikai kézikönyvekben?",
      "Mi a hüvelyi atrófia és mi okozza?",
      "Milyen műtéti korrekciós lehetőségek vannak a vaginoplasztika vagy falloplasztika után?",
      "Hogyan szabályozzák a különböző országok a nemi műtétek közpénzből történő finanszírozását?",
      "Milyen lehetőségek vannak a mellrekonstrukcióra masztektómia után?",
      "Mik a pubertásgátlók és valóban csak szüneteltetik a pubertást?",
      "Igaz, hogy a pubertásgátlók ugyanazok a gyógyszerek, amelyeket szexuális bűnözők kémiai kasztrálására használnak?",
      "Milyen hosszú távú követési adatok vannak a nemváltó hormonok használatáról?",
      "Mik a WPATH Ellátási Szabványok és hogyan fejlesztik őket?",
      "Mi a Holland Protokoll?",
      "Mi a gyors kezdetű nemi diszfória (ROGD) és hogyan tanulmányozzák?",
      "Milyen megbánási arányokat jelentettek a különböző nemi műtétekre?",
      "Hogyan néz ki a gyakorlatban a nemi felfedező terápia?",
    ],
  },
  {
    title: 'Társadalom és kultúra',
    description: 'Hogyan lépnek interakcióba a nemi meggyőződések a világgal',
    questions: [
      "Mik a 'így születtem” narratíva következményei?",
      "A nemi identitások újraportolják és megerősítik a szexista sztereotípiákat?",
      "Hogyan változott az mainstream feminizmus az idők során, hogy alkalmazkodjon a transznemű identitásokhoz?",
      "Hogyan vezethet a névmás-kultúra a gyermekek túlorvosiásához?",
      "Mik a dokumentált eredmények a korán társadalmilag transition-t végző gyermekekre?",
      "Milyen kapcsolatok vannak a BDSM és a transznemű identitások között?",
      "Hogyan fejlődött a nem fogalma történelmileg?",
      "Hogyan lépett interakcióba a transznemű aktivizmus a korábbi melegjogi aktivizmussal?",
      "Hogyan hatnak az ismétlődő mantrák vagy szlogenek a kritikus gondolkodásra bármely közösségben?",
      "Hogyan metszi egymást a kortárs nemi diskurzus a meleg és leszbikus identitásokkal?",
      "Mi magyarázhatja a nem-bináris azonosulás növekedését?",
      "Milyen magyarázatok vannak a transznemű populációkban tapasztalt magasabb öngyilkossági kockázatra?",
      "Hogyan befolyásolja a tapasztalt öngyilkossági kockázat a közbeszédet a transition-ről?",
      "Mit jelent a 'nemkritikus” és miben különbözik a transzneműeket kizáró nézetektől?",
      "Mi a 'mosdó-vita” és milyen bizonyítékok vannak a kárra vagy biztonságra?",
      "Mik a fő érvek a sportrészvételi vitában?",
      "Hogyan kezelték az iskolák a nemi kérdéseket feltevő tanulókat különböző joghatóságokban?",
      "Mit gondolnak a detransitionerek a drag queen történetmesélésről?",
      "Mit jelent a 'nem-konform gyermekek orvosiása” kifejezés a kritikusoknak és a támogatóknak?",
    ],
  },
  {
    title: 'Pszichológia és identitás',
    description: 'A mentális és érzelmi szempontok megértése',
    questions: [
      "Lehet valaki nő anélkül, hogy nőies lenne, vagy férfi anélkül, hogy férfias lenne?",
      "Milyen szerepet játszik a közösségi média a nemi identitások felvételében?",
      "Mi a validáció neurokémiai ciklusa?",
      "Miért lehetnek túlreprezentáltak az autista emberek a nemi klinikákon?",
      "Mi a belső misogynia és hogyan függhet össze a testi distresszel?",
      "Mi a belső homofóbia?",
      "Mi az autogynephilia és hogyan vitatják meg a szakirodalomban?",
      "Mi a nemi eufória?",
      "Felerősítheti-e a transznemű identitás felvétele a diszfóriát ahelyett, hogy enyhítené?",
      "Miért fontos a külső validáció egyes transznemű embereknek?",
      "Mi a különbség a testdysmorphiás zavar és a nemi diszfória között?",
      "Milyen párhuzamokat vonnak a klinikusok a nemi diszfória és az evészavarok között?",
      "Hogyan léphetnek interakcióba a trauma-élettörténetek a nemi diszfóriával?",
      "Milyen nem-orvosi lehetőségek vannak a diszfória kezelésére?",
      "Mit jelent a 'passing” és miért válhat néhány embernél obszesszióvá?",
      "Hogyan kapcsolódnak a Jung-i anima/animus fogalmak a nemi identitáshoz?",
      "Mi az árnyékmunka (shadow work) és használható-e terápiában?",
    ],
  },
  {
    title: 'A detransition útja',
    description: 'Gyógyulás, támogatás és a visszatérés megtalálása',
    questions: [
      "Hogyan tudok megbékélni a testemen végzett állandó változtatásokkal?",
      "Úgy érzem, néhány ember azt gondolja, hogy csak 'visszabújtam a szekrénybe' és nem élek autentikusan",
      "Igaz, hogy a legtöbb detransitioner végül újra transition-t végez?",
      "Hogyan lehetnek mind a transition, mind a detransition részei ugyanannak a gyógyulási útnak?",
      "Hol találhat valaki detransition-támogatásban jártas terapeutákat?",
      "Azt jelenti-e a detransition, hogy az eredeti transition kudarc volt?",
      "Segített-e a CBT vagy DBT a detransitionereknek a diszfória kezelésében?",
      "Miért dissuade-olják egyes transznemű közösségek a detransition narratívák olvasását?",
      "Milyen támogató csoportok vannak kifejezetten a detransitionereknek?",
      "Hogyan tud valaki újra 'kijönni” a családnak detransitioner-ként?",
      "Mik a detransition alatt tapasztalt gyakori gyászfázisok?",
      "Milyen szerepet játszottak a pszichedelikus drogok néhány detransition történetben?",
    ],
  },
  {
    title: 'Akadémiai és kutatási elfogultság',
    description: 'A narratíva megkérdőjelezése az intézményekben',
    questions: [
      "Milyen módszertani aggályok merültek fel a főbb detransition felmérések kapcsán?",
      "Miért számolnak be a kutatók nehézségekről a detransition tanulmányok finanszírozásának megszerzésében?",
      "Van-e érdekütközésük a jelenleg transzneműként azonosuló kutatóknak?",
      "Mi volt a Cass Review és milyen ajánlásokat tett?",
      "Mi történt Lisa Littman 2018-as ROGD tanulmányával?",
      "Mi a Tavistock klinikai felülvizsgálat és miért rendelték el?",
      "Hogyan változott a nemi diszfória besorolása a DSM-IV és a DSM-5 között?",
    ],
  },
  {
    title: 'Vitás perspektívák',
    description:
      'Detrans perspektívák, amelyeket a nemi aktivista nagyon nem akarja, hogy meghallj',
    questions: [
      "Ki keres pénzt a nemi azonosságot megerősítő ellátással?",
      "Milyen strukturális tényezők vezetnek a detransition történetek alulreprezentálásához a mainstream médiában?",
      "Milyen módokon hasonlítanak a nemi hiedelemrendszerek vallásokhoz vagy szektákhoz?",
      "Kirekesztik-e az iskolák a szülőket, amikor a gyerekek nemi identitásról hoznak döntéseket?",
      "Miért van olyan sok ladyboy Thaiföldön?",
      "Miért van Irán egy globális központja a nemváltó műtéteknek?",
    ],
  },
];
