/**
 * German translation of question categories and featured questions
 * 
 * Gender-Related Terminology Notes:
 * - "Geschlecht" = biological sex (anatomy, chromosomes, reproduction)
 * - "Gender" = social gender (roles, behaviors, attributes assigned by society)
 * - "Geschlechtsidentität" = gender identity (internal sense of being male/female/other)
 * - "Geschlechter-Nichtkonformität (GNC)" = gender non-conformity
 * - "transgeschlechtlich" = transgender (literally: trans-gendered)
 * - "AFAB/AMAB" = zugewiesen weiblich/männlich bei Geburt (assigned female/male at birth)
 * 
 * German distinguishes between biological sex (Geschlecht) and social gender (Gender),
 * which is crucial for understanding detransition narratives and gender dysphoria discussions.
 */

export const questionCategories = [
  {
    title: "Empfohlene Fragen",
    description: "Die besten Fragen, die Sie Personen stellen können, die eine Detransition durchgeführt haben.",
    questions: [
      "Was bedeutet trans?",
      "Haben trans Personen schon immer existiert?",
      "Ist es wahr, dass nur 1% eine Detransition durchführen?",
      "Sind Pubertätsblocker reversibel?",
      "Welche Beweise gibt es für geschlechtsbestätigende medizinische Protokolle?",
      "Was bedeutet der Begriff ‚Ei' (egg) in trans Communities?",
      "Was sind die Implikationen des Narrativs ‚so geboren'?",
      "Wie verstärken nicht-binäre Labels traditionelle Geschlechterstereotypen?",
      "Was ist der Unterschied zwischen biologischem Geschlecht (Sex) und sozialem Geschlecht (Gender)?",
      "Was ist Geschlechtsdysphorie und was kann sie verursachen?",
      "Warum entscheiden sich einige Menschen für eine Detransition?",
      "Wie können Freunde oder Familie jemanden unterstützen, der eine Transition durchführen möchte?",
      "Wie können Freunde oder Familie jemanden unterstützen, der eine Detransition durchführen möchte?",
      "Bereuen Personen, die eine Detransition durchgeführt haben, ihre Transition häufig?",
      "Warum entscheiden sich einige Menschen nach einer Detransition erneut für eine Transition (Retransition)?",
      "Was können mir die Geschichten von Personen mit Detransition-Erfahrung lehren, auch wenn meine Transition bisher gut verläuft?",
      "Wie erkenne ich, ob Zweifel nur Nervosität sind oder ein Zeichen, dass ich aufhören sollte?",
      "Warum unterscheiden sich trans Narrative über Gründe für Detransition von denen, die tatsächlich eine Detransition durchgeführt haben?",
      "Denken Personen mit Detransition-Erfahrung, dass Transition an sich schlecht ist?",
      "Was sind einige falsche Behauptungen über transgeschlechtliche Personen?",
      "Was sind einige falsche Behauptungen über Personen, die eine Detransition durchgeführt haben?",
      "Welche frühen Anzeichen wünschten sich Personen mit Detransition-Erfahrung, früher bemerkt zu haben?",
      "Ist Gender ein soziales Konstrukt? Was bedeutet das?",
      "Wie haben feministische Bewegungen das Konzept von Gender historisch betrachtet?",
      "Wie kann Geschlechter-Nichtkonformität den Druck zur Einhaltung von Geschlechterrollen verringern?",
      "Wie beschreiben Personen mit Detransition-Erfahrung das Gefühl, ‚im falschen Körper geboren' zu sein?",
      "Was ist geschlechtsbestätigende Versorgung und was sind ihre Ziele?",
      "Warum ist geschlechtsbestätigende Versorgung in den meisten Regionen oft die einzige Option?",
      "Wie unterscheidet sich explorative Geschlechtertherapie von geschlechtsbestätigender Versorgung?",
      "Warum lehnen einige Menschen das Konzept der explorativen Geschlechtertherapie ab, und warum ist sie an manchen Orten verboten?",
      "Sollten geschlechtsbestätigende Versorgung und Hormone laut Personen mit Detransition-Erfahrung verboten werden?",
      "Bereuen Personen mit Detransition-Erfahrung normalerweise medizinische Schritte, soziale Schritte oder beides?",
      "Was ist eine Identitätsfalle und wie erkennen Menschen typischerweise, dass sie in einer sind?",
      "Wo kann jemand einen Therapeuten finden, der offene, nicht direktive Geschlechterexploration anbietet? Auf welche Warnsignale sollte ich achten?",
      "Hilft oder behindert das Nachfragen nach Pronomen geschlechter-nichtkonforme Personen?",
      "Wenn ein junges Mädchen mit kurzen Haaren ständig nach ihren Pronomen gefragt wird, welche Implikation hat das und wie würde sie sich fühlen?",
      "Was ist Cancel Culture und welche Auswirkungen hat sie auf den öffentlichen Gesundheitsdiskurs?",
      "Sehen Personen mit Detransition-Erfahrung Transition als einen Prozess mit einem Endpunkt oder als einen fortlaufenden Prozess?",
      "Warum könnten einige jugendliche Mädchen Bedauern über die Brustentwicklung empfinden?",
      "Wie können Online-Echokammern die Identitätsbildung beeinflussen?",
      "Warum berichten Personen mit Detransition-Erfahrung oft, dass ihre Geschichten und Stimmen sowohl in trans als auch in Mainstream-Räumen zum Schweigen gebracht werden?",
      "Welche demografischen Muster sind bei Überweisungen zu Geschlechtskliniken zu erkennen?",
      "Wie unterscheiden sich zeitgenössische queere Identitäten von der früheren LGB-Bewegung?",
      "Was sagt die aktuelle Forschung über Überschneidungen zwischen Autismus-Spektrum-Merkmalen, Geschlechtsdysphorie und transgeschlechtlichen Identitäten?",
      "Warum ist Geschlechtsdysphorie im DSM-5 nicht mehr als psychische Störung klassifiziert?",
      "Wie hat sich die Prävalenz von Trans in letzter Zeit verändert und was könnte dies erklären?",
    ],
  },
  {
    title: "Allgemeine Begriffe",
    description: "Die grundlegenden Konzepte verstehen",
    questions: [
      "Was ist ein Mann?",
      "Was ist eine Frau?",
      "Was ist Gender?",
      "Was ist Geschlechtsdysphorie?",
      "Was ist eine transgeschlechtliche Identität?",
      "Was ist Transphobie?",
      "Was ist Cancel Culture?",
      "Was ist eine nicht-binäre Identität?",
      "Was ist eine queere Identität?",
      "Was ist Queer-Theorie?",
      "Was ist Persönlichkeit?",
      "Wie unterscheidet sich Persönlichkeit von Geschlechtsidentität?",
      "Was ist Geschlechter-Nichtkonformität (GNC)?",
      "Was ist Geschlechter-Konformität?",
      "Was ist Detransition?",
      "Was ist Abgelassen (Desistence)?",
      "Was sind Pronomen und warum sind sie für einige bedeutsam?",
      "Was meinen trans Personen, wenn sie über ‚Trans-Rechte' sprechen?",
      "Warum sagen einige trans Personen ‚Lieber tot als Detransition'?",
      "Welche Faktoren werden als Ursache für Dysphorie angesehen?",
      "Was ist die ‚Geschlechtsdysphorie-Bibel'?",
      "Welche Strategien (medizinisch oder nicht-medizinisch) helfen Menschen, Dysphorie zu bewältigen?",
      "Sind intersexuelle Personen automatisch trans?",
      "Was ist Geschlechter-Fluidität?",
      "Was bedeuten AFAB und AMAB?",
      "Was ist eine TERF?",
      "Was ist Deadnaming?",
      "Was ist Misgendern?",
      "Was ist eine cisgeschlechtliche Person?",
      "Was ist mit biologischem Geschlecht (Sex) gemeint?",
      "Was ist der Unterschied zwischen sozialer und medizinischer Transition?",
    ],
  },
  {
    title: "Die medizinische Realität",
    description: "Gesundheit, Eingriffe und biologische Wahrheiten",
    questions: [
      "Was sind die Nebenwirkungen von Testosteron bei Frauen?",
      "Was sind die Nebenwirkungen von Östrogen bei Männern?",
      "Welche physiologischen Veränderungen kann Testosteron bei Frauen bewirken und wo sind die Grenzen?",
      "Welche physiologischen Veränderungen kann Östrogen bei Männern bewirken und wo sind die Grenzen?",
      "Was beinhaltet eine Phalloplastie und was sind typische Ergebnisse?",
      "Was beinhaltet eine Vaginoplastie und was sind typische Ergebnisse?",
      "Welche verschiedenen Arten der Vaginoplastie gibt es?",
      "Wie sollte jemand abwägen, ob er Hormone weiter nimmt oder absetzt?",
      "Gibt es messbare Unterschiede in den Diagnoseraten von Geschlechtsdysphorie zwischen Männern und Frauen?",
      "Was sagt die Hirnbildforschung über ‚männliche' versus ‚weibliche' Gehirne?",
      "Wie wird Geschlechtsdysphorie in Diagnosehandbüchern von psychischen Krankheiten unterschieden?",
      "Was ist vaginale Atrophie und was verursacht sie?",
      "Welche chirurgischen Revisionsoptionen gibt es für Vaginoplastie oder Phalloplastie?",
      "Wie regeln verschiedene Länder die öffentliche Finanzierung von Geschlechtsoperationen?",
      "Welche Optionen gibt es für die Brustrekonstruktion nach einer Mastektomie?",
      "Was sind Pubertätsblocker und pausieren sie wirklich nur die Pubertät?",
      "Ist es wahr, dass Pubertätsblocker dasselbe Medikament sind, das zur chemischen Kastration von Sexualstraftätern verwendet wird?",
      "Welche Langzeit-Follow-up-Daten gibt es zur Verwendung von Cross-Sex-Hormonen?",
      "Was sind die WPATH Standards of Care und wie werden sie entwickelt?",
      "Was ist das niederländische Protokoll (Dutch Protocol)?",
      "Was ist Rapid-Onset Gender Dysphoria (ROGD) und wie wird sie erforscht?",
      "Wie hoch sind die berichteten Bedauensraten bei verschiedenen Geschlechtsoperationen?",
      "Wie sieht explorative Geschlechtertherapie in der Praxis aus?",
    ],
  },
  {
    title: "Gesellschaft & Kultur",
    description: "Wie Geschlechterüberzeugungen mit der Welt interagieren",
    questions: [
      "Was sind die Implikationen des Narrativs ‚so geboren'?",
      "Sind Geschlechtsidentitäten eine Neuverpackung und Verstärkung sexistischer Stereotypen?",
      "Wie hat sich der Mainstream-Feminismus im Laufe der Zeit verändert, um transgeschlechtliche Identitäten aufzunehmen?",
      "Wie kann die Pronomen-Kultur zur Übermedikalisierung von Kindern führen?",
      "Was sind die dokumentierten Ergebnisse für Kinder, die früh eine soziale Transition durchführen?",
      "Welche Verbindungen gibt es zwischen BDSM und trans Identitäten?",
      "Wie hat sich das Konzept von Gender historisch entwickelt?",
      "Wie hat sich der trans Aktivismus mit der früheren Schwulenrechtsbewegung auseinandergesetzt?",
      "Wie wirken sich repetitive Mantras oder Slogans auf kritisches Denken in jeder Community aus?",
      "Wie schneidet zeitgenössischer Gender-Diskurs mit schwulen und lesbischen Identitäten?",
      "Was könnte den Anstieg der nicht-binären Identifikation erklären?",
      "Welche Erklärungen gibt es für das erhöhte Suizidrisiko in trans Populationen?",
      "Wie wirkt sich das wahrgenommene Suizidrisiko auf den öffentlichen Diskurs über Transition aus?",
      "Was bedeutet ‚genderkritisch' und wie unterscheidet es sich von trans-exklusiven Ansichten?",
      "Was ist die ‚Badezimmer-Debatte' und welche Beweise gibt es für Schaden oder Sicherheit?",
      "Was sind die Hauptargumente in der Sportteilhabe-Kontroverse?",
      "Wie haben Schulen in verschiedenen Gerichtsbarkeiten mit geschlechtserfragenden Schülern umgegangen?",
      "Was denken Personen mit Detransition-Erfahrung über Drag-Queen-Geschichten?",
      "Was bedeutet der Begriff ‚Medikalisierung geschlechts-nichtkonformer Kinder' für Kritiker und Befürworter?",
    ],
  },
  {
    title: "Psychologie & Identität",
    description: "Die mentalen und emotionalen Aspekte verstehen",
    questions: [
      "Kann jemand eine Frau sein, ohne weiblich zu sein, oder ein Mann, ohne männlich zu sein?",
      "Welche Rolle spielt Social Media bei der Annahme von Geschlechtsidentitäten?",
      "Was ist der neurochemische Kreislauf der Validierung?",
      "Warum könnten autistische Menschen überrepräsentiert in Geschlechtskliniken sein?",
      "Was ist internalisierter Misogynie und wie könnte er mit Körperdistress zusammenhängen?",
      "Was ist internalisierte Homophobie?",
      "Was ist Autogynophilie und wie wird sie in der Literatur debattiert?",
      "Was ist Gendereuphorie?",
      "Kann die Annahme einer trans Identität Dysphorie verstärken, anstatt sie zu lindern?",
      "Warum ist externe Validierung für einige trans Personen wichtig?",
      "Was ist der Unterschied zwischen körperdysmorpher Störung und Geschlechtsdysphorie?",
      "Welche Parallelen ziehen Kliniker zwischen Geschlechtsdysphorie und Essstörungen?",
      "Wie könnten Traumageschichten mit Geschlechtsdysphorie interagieren?",
      "Welche nicht-medizinischen Optionen gibt es, um Dysphorie zu bewältigen?",
      "Was bedeutet ‚passing' und warum kann es für einige Menschen zu einer Obsession werden?",
      "Wie beziehen sich jungianische Konzepte von Anima/Animus auf Geschlechtsidentität?",
      "Was ist Schattenarbeit (Shadow Work) und kann sie in der Therapie verwendet werden?",
    ],
  },
  {
    title: "Der Detransition-Weg",
    description: "Heilung, Unterstützung und den Weg zurück finden",
    questions: [
      "Wie kann ich Frieden mit den dauerhaften Veränderungen schließen, die ich an meinem Körper vorgenommen habe?",
      "Ich habe das Gefühl, dass einige Leute denken, ich bin einfach wieder ‚im Schrank', und dass ich nicht authentisch lebe",
      "Ist es wahr, dass die meisten Personen mit Detransition-Erfahrung am Ende erneut eine Transition durchführen?",
      "Wie können Transition und Detransition beide Teil derselben Heilungsreise sein?",
      "Wo kann man Therapeuten finden, die Erfahrung mit Detransition-Unterstützung haben?",
      "Bedeutet Detransition, dass die ursprüngliche Transition ein Fehlschlag war?",
      "Hat CBT (kognitive Verhaltenstherapie) oder DBT (dialektische Verhaltenstherapie) Personen mit Detransition-Erfahrung bei der Bewältigung von Dysphorie geholfen?",
      "Warum entmutigen einige trans Communities das Lesen von Detransition-Narrativen?",
      "Welche Selbsthilfegruppen gibt es speziell für Personen, die eine Detransition durchführen?",
      "Wie kann jemand (erneut) zur Familie als Person, die eine Detransition durchführt, herauskommen?",
      "Was sind häufige Trauerphasen, die während der Detransition berichtet werden?",
      "Welche Rolle haben Psychedelika in einigen Detransition-Geschichten gespielt?",
    ],
  },
  {
    title: "Akademische & Forschungsverzerrung",
    description: "Das Narrativ in Institutionen hinterfragen",
    questions: [
      "Welche methodischen Bedenken wurden zu wichtigen Detransition-Umfragen geäußert?",
      "Warum berichten Forscher über Schwierigkeiten, Finanzierung für Detransition-Studien zu sichern?",
      "Haben Forscher, die sich derzeit als trans identifizieren, einen Interessenkonflikt?",
      "Was war die Cass Review und welche Empfehlungen wurden erstellt?",
      "Was ist mit Lisa Littmans Studie von 2018 über ROGD passiert?",
      "Was ist die Tavistock-Klinik-Überprüfung und warum wurde sie beauftragt?",
      "Wie wurde Geschlechtsdysphorie zwischen DSM-IV und DSM-5 neu klassifiziert?",
    ],
  },
  {
    title: "Kontroverse Perspektiven",
    description:
      "Detrans-Perspektiven, die Gender-Aktivisten nicht hören wollen",
    questions: [
      "Wer verdient Geld mit geschlechtsbestätigender Versorgung?",
      "Welche strukturellen Faktoren führen zu einer Unterrepräsentation von Detransition-Geschichten in Mainstream-Medien?",
      "Inwiefern ähneln Geschlechterglaubenssysteme Religionen oder Kulten?",
      "Setzen Schulen Eltern außer Kraft, wenn Kinder Entscheidungen über Geschlechtsidentität treffen?",
      "Warum gibt es so viele Ladyboys in Thailand?",
      "Warum ist Iran ein globales Zentrum für Geschlechtsumwandlungsoperationen?",
    ],
  },
];
