/**
 * Polish question categories and featured questions for detrans.ai
 *
 * Uwagi dotyczące terminologii związanej z płcią:
 * - "Płeć" (sex) = płeć biologiczna (anatomia, chromosomy, reprodukcja, cechy niezmienne)
 * - "Gender" / "Płeć kulturowa" = płeć społeczna (role, zachowania, atrybuty, które społeczeństwo 
 *   uznaje za odpowiednie dla mężczyzn i kobiet w oparciu o ich płeć biologiczną)
 * - "Tożsamość płciowa" (gender identity) = wewnętrzne poczucie bycia mężczyzną, kobietą 
 *   lub gdzieś pomiędzy
 * - "Niezgodność z normami płciowymi" / "Nonkonformizm płciowy" (GNC) = gdy osoba zachowuje 
 *   się/prezentuje inaczej niż oczekuje tego społeczeństwo w oparciu o jej płeć biologiczną
 * - "AFAB/AMAB" = przypisano żeńską/męską płeć przy urodzeniu (w oparciu o zaobserwowaną płeć biologiczną)
 * - "Transpłciowość/trans" = identyfikowanie się z płcią różną od płci biologicznej
 * - "Destranzycja" = zaprzestanie identyfikacji jako osoba transpłciowa i/lub odwrócenie kroków tranzycji
 * - "Zaniechanie" = gdy osoba, która identyfikowała się jako trans (bez interwencji medycznych), 
 *   przestaje identyfikować się jako trans
 *
 * Ważne rozróżnienie: Koncepcja dysforii płciowej opiera się na zrozumieniu, że płeć biologiczna
 * i płeć społeczna są różne. Niezgodność z normami płciowymi (niepasowanie do stereotypów) to
 * co innego niż posiadanie tożsamości płciowej różnej od płci biologicznej.
 */

export const questionCategories = [
  {
    title: "Wyróżnione pytania",
    description: "Najlepsze pytania do zadawania osobom po destranzycji.",
    questions: [
      "Co oznacza transpłciowość?",
      "Czy osoby transpłciowe zawsze istniały?",
      "Czy to prawda, że tylko 1% osób przechodzi destranzycję?",
      "Czy blokerzy dojrzewania są odwracalni?",
      "Jakie dowody istnieją na protokoły medyczne afirmujące płeć?",
      "Co oznacza termin 'jajko' (egg) w społecznościach transpłciowych?",
      "Jakie są implikacje narracji 'tak się urodziłem'?",
      "W jaki sposób etykiety niebinarne wzmacniają tradycyjne stereotypy płciowe?",
      "Jaka jest różnica między płcią biologiczną a płcią kulturową (gender)?",
      "Co to jest dysforia płciowa i co może ją powodować?",
      "Dlaczego niektórzy ludzie decydują się na destranzycję?",
      "Jak przyjaciele lub rodzina mogą wspierać osobę, która chce przejść tranzycję?",
      "Jak przyjaciele lub rodzina mogą wspierać osobę, która chce przejść destranzycję?",
      "Czy powszechne jest, aby osoby po destranzycji żałowały tranzycji?",
      "Dlaczego niektórzy ludzie decydują się na powtórną tranzycję po destranzycji?",
      "Czego mogą nauczyć mnie historie osób po destranzycji, nawet jeśli moja tranzycja przebiega dobrze do tej pory?",
      "Skąd miałbym wiedzieć, czy wątpliwości to tylko nerwy, czy znak, że powinienem przestać?",
      "Dlaczego narracje transpłciowe o tym, dlaczego ludzie przechodzą destranzycję, różnią się od tych osób, które faktycznie przeszły destranzycję?",
      "Czy osoby po destranzycji uważają, że sama tranzycja jest zła?",
      "Jakie fałszywe twierdzenia są kierowane pod adresem osób transpłciowych?",
      "Jakie fałszywe twierdzenia są kierowane pod adresem osób, które przeszły destranzycję?",
      "Jakie wczesne oznaki życzyliby sobie osoby po destranzycji, żeby zauważyły wcześniej?",
      "Czy płeć kulturowa (gender) jest konstruktem społecznym? Co to oznacza?",
      "Jak ruchy feministyczne historycznie postrzegały koncepcję płci kulturowej (gender)?",
      "W jaki sposób niezgodność z normami płciowymi może zmniejszyć presję do dostosowania się do ról płciowych?",
      "Jak osoby po destranzycji opisują poczucie 'urodzenia się w niewłaściwym ciele'?",
      "Co to jest opieka afirmująca płeć i jakie są jej cele?",
      "Dlaczego opieka afirmująca płeć jest zazwyczaj jedyną opcją w większości regionów?",
      "Czym terapia eksplorująca płeć różni się od opieki afirmującej płeć?",
      "Dlaczego niektórzy ludzie nie lubią koncepcji terapii eksplorującej płeć i dlaczego jest ona zakazana w niektórych miejscach?",
      "Czy osoby po destranzycji uważają, że opieka afirmująca płeć i hormony powinny być zakazane?",
      "Czy osoby po destranzycji zazwyczaj żałują kroków medycznych, społecznych czy obu?",
      "Czym jest pułapka tożsamości i jak ludzie zazwyczaj zdają sobie sprawę, że się w niej znajdują?",
      "Gdzie ktoś może szukać terapeuty oferującego otwartą, niedyrektywną eksplorację płci? Na jakie czerwone flagi powinienem uważać?",
      "Czy proszenie o zaimki pomaga czy utrudnia osobom niezgodnym z normami płciowymi?",
      "Jeśli młoda dziewczynka z krótkimi włosami jest ciągle pytana o swoje zaimki, jaka jest implikacja i jak by się to poczuło?",
      "Czym jest kultura anulowania (cancel culture) i jakie ma skutki dla dyskursu o zdrowiu publicznym?",
      "Czy osoby po destranzycji postrzegają tranzycję jako mającą punkt końcowy czy jako proces trwający?",
      "Dlaczego niektóre nastoletnie dziewczyny mogą doświadczać stresu związanego z rozwojem piersi?",
      "W jaki sposób internetowe komory echa mogą wpływać na formowanie tożsamości?",
      "Dlaczego osoby po destranzycji często zgłaszają, że czują się, jakby ich historie i głosy były uciszane zarówno w przestrzeniach transpłciowych, jak i mainstreamowych?",
      "Jakie wzorce demograficzne są widoczne w skierowaniach do klinik płci?",
      "Czym współczesne tożsamości queer różnią się od wcześniejszego ruchu LGB?",
      "Co obecne badania mówią o pokrywaniu się cech spektrum autyzmu, dysforii płciowej i tożsamości transpłciowych?",
      "Dlaczego dysforia płciowa nie jest już klasyfikowana jako zaburzenie psychiczne w DSM-5?",
      "Jak zmieniała się zapadalność na transpłciowość w ostatnich czasach i co może to wyjaśniać?",
    ],
  },
  {
    title: "Terminologia ogólna",
    description: "Zrozumienie fundamentalnych koncepcji",
    questions: [
      "Co to jest mężczyzna?",
      "Co to jest kobieta?",
      "Co to jest płeć kulturowa (gender)?",
      "Co to jest dysforia płciowa?",
      "Co to jest tożsamość transpłciowa?",
      "Co to jest transfobia?",
      "Co to jest kultura anulowania (cancel culture)?",
      "Co to jest tożsamość niebinarna?",
      "Co to jest tożsamość queer?",
      "Co to jest teoria queer?",
      "Co to jest osobowość?",
      "Czym osobowość różni się od tożsamości płciowej?",
      "Co to jest niezgodność z normami płciowymi (GNC)?",
      "Co to jest konformizm płciowy?",
      "Co to jest destranzycja?",
      "Co to jest zaniechanie?",
      "Co to są zaimki i dlaczego są istotne dla niektórych?",
      "Co osoby transpłciowe mają na myśli, mówiąc o 'prawach trans'?",
      "Dlaczego niektórzy ludzie transpłciowi mówią 'śmierć przed destranzycją'?",
      "Jakie czynniki są uważane za przyczyny dysforii?",
      "Czym jest 'bibliia dysforii płciowej'?",
      "Jakie strategie (medyczne lub niemedyczne) pomagają ludziom radzić sobie z dysforią?",
      "Czy osoby interpłciowe są automatycznie transpłciowe?",
      "Co to jest płynność płciowa?",
      "Co oznaczają AFAB i AMAB?",
      "Co to jest TERF?",
      "Co to jest deadnaming?",
      "Co to jest misgendering?",
      "Co to jest osoba cispłciowa?",
      "Co oznacza płeć biologiczna?",
      "Jaka jest różnica między tranzycją społeczną a medyczną?",
    ],
  },
  {
    title: "Rzeczywistość medyczna",
    description: "Zdrowie, zabiegi i prawdy biologiczne",
    questions: [
      "Jakie są działania niepożądane stosowania testosteronu u kobiet?",
      "Jakie są działania niepożądane stosowania estrogenów u mężczyzn?",
      "Jakie zmiany fizjologiczne może wywołać testosteron u kobiet i jakie są limity?",
      "Jakie zmiany fizjologiczne może wywołać estrogen u mężczyzn i jakie są limity?",
      "Na czym polega faloplastyka i jakie są typowe wyniki?",
      "Na czym polega waginoplastyka i jakie są typowe wyniki?",
      "Jakie są różne rodzaje operacji waginoplastyki?",
      "Jak ktoś powinien rozważyć kontynuowanie vs zaprzestanie przyjmowania hormonów?",
      "Czy istnieją mierzalne różnice w występowaniu diagnozy dysforii płciowej między mężczyznami a kobietami?",
      "Co badania obrazowania mózgu mówią o 'męskich' vs 'żeńskich' mózgach?",
      "Jak dysforia płciowa jest odróżniana od choroby psychicznej w podręcznikach diagnostycznych?",
      "Co to jest zanik pochwy i co go powoduje?",
      "Jakie opcje rewizji chirurgicznej istnieją dla waginoplastyki lub faloplastyki?",
      "Jak różne kraje regulują publiczne finansowanie operacji płci?",
      "Jakie opcje istnieją dla rekonstrukcji klatki piersiowej po mastektomii?",
      "Co to są blokerzy dojrzewania i czy naprawdę tylko wstrzymują dojrzewanie?",
      "Czy to prawda, że blokerzy dojrzewania to ten sam lek, który jest używany do chemicznej kastracji przestępców seksualnych?",
      "Jakie dane o długoterminowym monitorowaniu istnieją dla stosowania hormonów krzyżowych?",
      "Czym są Standardy Opieki WPATH i jak są opracowywane?",
      "Czym jest Holenderski Protokół?",
      "Czym jest gwałtownie pojawiająca się dysforia płciowa (ROGD) i jak jest badana?",
      "Jakie są zgłaszane wskaźniki żalu po różnych operacjach płci?",
      "Jak wygląda terapia eksplorująca płeć w praktyce?",
    ],
  },
  {
    title: "Społeczeństwo i kultura",
    description: "Jak przekonania o płci oddziałują ze światem",
    questions: [
      "Jakie są implikacje narracji 'tak się urodziłem'?",
      "Czy tożsamości płciowe są przepakowywaniem i wzmacnianiem seksistowskich stereotypów?",
      "Jak główny nurt feminizmu zmieniał się z czasem, aby dostosować się do tożsamości transpłciowych?",
      "W jaki sposób kultura zaimków może prowadzić do nadmiernej medykalizacji dzieci?",
      "Jakie są udokumentowane wyniki dla dzieci, które wcześnie przeszły tranzycję społeczną?",
      "Jakie są związki między BDSM a tożsamościami transpłciowymi?",
      "Jak ewoluowała koncepcja płci historycznie?",
      "Jak aktywizm transpłciowy wchodził w interakcje z wcześniejszym aktywizmem na rzecz praw gejowskich?",
      "W jaki sposób powtarzające się mantry lub slogany wpływają na krytyczne myślenie w każdej społeczności?",
      "Jak współczesny dyskurs o płci przecina się z tożsamościami gejowskimi i lesbijskimi?",
      "Co może wyjaśniać wzrost identyfikacji niebinarnej?",
      "Jakie wyjaśnienia istnieją dla podwyższonego ryzyka samobójczego w populacjach transpłciowych?",
      "Jak postrzegane ryzyko samobójcze wpływa na dyskurs publiczny wokół tranzycji?",
      "Co oznacza 'krytyczny wobec płci' i czym różni się od poglądów wykluczających transpłciowość?",
      "Jaka jest 'debata o toaletach' i jakie dowody istnieją na szkody lub bezpieczeństwo?",
      "Jakie są główne argumenty w sporze o udział w sporcie?",
      "Jak szkoły radziły sobie z uczniami kwestionującymi płeć w różnych jurysdykcjach?",
      "Co osoby po destranzycji myślą o Drag Queen Story Hour?",
      "Co oznacza zwrot 'medykalizacja dzieci niezgodnych z normami płciowymi' dla krytyków i zwolenników?",
    ],
  },
  {
    title: "Psychologia i tożsamość",
    description: "Zrozumienie aspektów mentalnych i emocjonalnych",
    questions: [
      "Czy ktoś może być kobietą bez bycia kobiecością, lub mężczyzną bez bycia męskością?",
      "Jaką rolę odgrywają media społecznościowe w przyjmowaniu tożsamości płciowych przez ludzi?",
      "Czym jest neurochemiczny cykl walidacji?",
      "Dlaczego osoby autystyczne mogą być nadreprezentowane w klinikach płci?",
      "Co to jest zinternalizowany seksizm i jak może się to odnosić do cierpienia związanego z ciałem?",
      "Co to jest zinternalizowana homofobia?",
      "Czym jest autogynefilia i jak jest debatowana w literaturze?",
      "Czym jest euforia płciowa?",
      "Czy przyjęcie tożsamości transpłciowej może wzmocnić dysforię zamiast jej ulżyć?",
      "Dlaczego zewnętrzna walidacja jest ważna dla niektórych osób transpłciowych?",
      "Jaka jest różnica między zaburzeniem dysmorficznym ciała a dysforią płciową?",
      "Jakie paralele wyciągają klinicyści między dysforią płciową a zaburzeniami odżywiania?",
      "Jak historie traumy mogą wchodzić w interakcje z dysforią płciową?",
      "Jakie opcje niemedyczne istnieją dla radzenia sobie z dysforią?",
      "Co oznacza 'przechodzenie' i dlaczego może stać się obsesją dla niektórych ludzi?",
      "Jak jungiańskie koncepcje animy/animusa odnoszą się do tożsamości płciowej?",
      "Czym jest praca z cieniem i czy może być używana w terapii?",
    ],
  },
  {
    title: "Podróż destranzycji",
    description: "Uzdrawianie, wsparcie i znajdowanie własnej drogi",
    questions: [
      "Jak mogę pogodzić się z trwałymi zmianami, jakich dokonałem w swoim ciele?",
      "Czuję, że niektórzy ludzie myślą, że po prostu 'wróciłem do szafy' i że nie żyję autentycznie",
      "Czy to prawda, że większość osób po destranzycji kończy powtórną tranzycję?",
      "Jak tranzycja i destranzycja mogą być częścią tej samej podróży uzdrawiania?",
      "Gdzie ktoś może znaleźć terapeutów doświadczonych w wsparciu destranzycji?",
      "Czy destranzycja oznacza, że oryginalna tranzycja była porażką?",
      "Czy CBT lub DBT pomogły osobom po destranzycji w radzeniu sobie z dysforią?",
      "Dlaczego niektóre społeczności transpłciowe zniechęcają do czytania narracji destranzycji?",
      "Jakie grupy wsparcia istnieją specjalnie dla osób po destranzycji?",
      "Jak ktoś może ponownie 'wyjść' rodzinie jako osoba przechodząca destranzycję?",
      "Jakie są powszechne etapy żałoby zgłaszane podczas destranzycji?",
      "Jaką rolę odgrywały psychodeliki w niektórych historiach destranzycji?",
    ],
  },
  {
    title: "Stronniczość akademicka i badawcza",
    description: "Kwestionowanie narracji w instytucjach",
    questions: [
      "Jakie obawy metodologiczne zostały podniesione wobec głównych badań nad destranzycją?",
      "Dlaczego badacze zgłaszają trudności w zabezpieczaniu finansowania badań nad destranzycją?",
      "Czy badacze, którzy obecnie identyfikują się jako transpłciowi, mają konflikt interesów?",
      "Czym była Recenzja Cass i jakie zalecenia wysunęła?",
      "Co stało się z badaniem Lisa Littman z 2018 roku o ROGD?",
      "Czym jest recenzja kliniki Tavistock i dlaczego została zlecona?",
      "Jak dysforia płciowa została reklasyfikowana między DSM-IV a DSM-5?",
    ],
  },
  {
    title: "Kontrowersyjne perspektywy",
    description:
      "Perspektywy osób po destranzycji, których aktywiści płci kulturowej naprawdę nie chcą, żebyś usłyszał",
    questions: [
      "Kto zarabia na opiece afirmującej płeć?",
      "Jakie czynniki strukturalne prowadzą do niedoreprezentowania historii destranzycji w mediach mainstreamowych?",
      "W jaki sposób systemy przekonań o płci przypominają religie lub kulty?",
      "Czy szkoły pomijają rodziców, gdy dzieci dokonują wyborów dotyczących tożsamości płciowej?",
      "Dlaczego w Tajlandii jest tyle ladyboys?",
      "Dlaczego Iran jest globalnym centrum operacji zmiany płci?",
    ],
  },
];
