export const questionCategories = [
  {
    title: "Preguntas Destacadas",
    description: "Las mejores preguntas para hacer a personas detrans.",
    questions: [
      "¿Qué significa trans?",
      "¿Han existido siempre las personas trans?",
      "¿Es cierto que solo el 1% hace detransición?",
      "¿Son los bloqueadores de la pubertad reversibles?",
      "¿Qué evidencia existe para los protocolos médicos de afirmación de género?",
      "¿Qué significa el término 'huevo' en las comunidades trans?",
      "¿Cuáles son las implicaciones de la narrativa de 'nací así'?",
      "¿Cómo refuerzan las etiquetas no binarias los estereotipos tradicionales de género?",
      "¿Cuál es la diferencia entre sexo y género?",
      "¿Qué es la disforia de género y qué puede causarla?",
      "¿Por qué algunas personas deciden hacer detransición?",
      "¿Cómo pueden los amigos o familiares apoyar a alguien que quiere hacer transición?",
      "¿Cómo pueden los amigos o familiares apoyar a alguien que quiere hacer detransición?",
      "¿Es común que las personas detrans lamenten haber hecho la transición?",
      "¿Por qué algunas personas deciden hacer retransición después de la detransición?",
      "¿Qué pueden enseñarme las historias detrans, incluso si mi transición va bien hasta ahora?",
      "¿Cómo sabría si las dudas son solo nervios o una señal de que debería detenerme?",
      "¿Por qué las narrativas trans sobre por qué la gente hace detransición difieren de las de quienes realmente han hecho detransición?",
      "¿Creen las personas detrans que la transición en sí es mala?",
      "¿Cuáles son algunas afirmaciones falsas hechas sobre personas transgénero?",
      "¿Cuáles son algunas afirmaciones falsas hechas sobre personas que han hecho detransición?",
      "¿Qué señales tempranas desearían haber notado antes las personas detrans?",
      "¿Es el género una construcción social? ¿Qué significa esto?",
      "¿Cómo han visto históricamente los movimientos feministas el concepto de género?",
      "¿Cómo puede la no conformidad de género reducir la presión para conformarse a los roles de género?",
      "¿Cómo describen las personas detrans la sensación de haber 'nacido en el cuerpo equivocado'?",
      "¿Qué es la atención de afirmación de género y cuáles son sus objetivos?",
      "¿Por qué la atención de afirmación de género suele ser la única opción en la mayoría de las regiones?",
      "¿En qué se diferencia la terapia exploratoria de género de la atención de afirmación de género?",
      "¿Por qué algunas personas no les gusta el concepto de terapia exploratoria de género y por qué está prohibida en algunos lugares?",
      "¿Creen las personas detrans que la atención de afirmación de género y las hormonas deberían prohibirse?",
      "¿Las personas detrans suelen lamentar los pasos médicos, los pasos sociales o ambos?",
      "¿Qué es una trampa de identidad y cómo suelen darse cuenta las personas de que están en una?",
      "¿Dónde puede alguien buscar un terapeuta que ofrezca exploración de género abierta y no directiva? ¿Qué señales de alerta debería buscar?",
      "¿Ayuda o dificulta a las personas no conformes con el género el pedir pronombres?",
      "Si a una niña joven con pelo corto le preguntan constantemente por sus pronombres, ¿cuál es la implicación y cómo la haría sentir esto?",
      "¿Qué es la cultura de la cancelación y qué efectos tiene en el discurso de salud pública?",
      "¿Ven las personas detrans la transición como un proceso con un punto final o como un proceso continuo?",
      "¿Por qué algunas adolescentes pueden experimentar angustia sobre el desarrollo de los senos?",
      "¿Cómo pueden las cámaras de eco en línea influir en la formación de la identidad?",
      "¿Por qué las personas detrans a menudo informan sentir que sus historias y voces son silenciadas tanto en espacios trans como en espacios convencionales?",
      "¿Qué patrones demográficos son visibles en las referencias a clínicas de género?",
      "¿En qué se diferencian las identidades queer contemporáneas del movimiento LGB anterior?",
      "¿Qué dice la investigación actual sobre la superposición entre rasgos del espectro autista, disforia de género e identidades transgénero?",
      "¿Por qué la disforia de género ya no se clasifica como un trastorno mental en el DSM-5?",
      "¿Cómo ha cambiado la prevalencia trans en tiempos recientes y qué podría explicar esto?",
    ],
  },
  {
    title: "Términos Generales",
    description: "Comprender los conceptos fundamentales",
    questions: [
      "¿Qué es un hombre?",
      "¿Qué es una mujer?",
      "¿Qué es el género?",
      "¿Qué es la disforia de género?",
      "¿Qué es la identidad transgénero?",
      "¿Qué es la transfobia?",
      "¿Qué es la cultura de la cancelación?",
      "¿Qué es la identidad no binaria?",
      "¿Qué es la identidad queer?",
      "¿Qué es la teoría queer?",
      "¿Qué es la personalidad?",
      "¿En qué se diferencia la personalidad de la identidad de género?",
      "¿Qué es la no conformidad de género (GNC)?",
      "¿Qué es la conformidad de género?",
      "¿Qué es la detransición?",
      "¿Qué es el desistimiento?",
      "¿Qué son los pronombres y por qué son significativos para algunos?",
      "¿Qué quieren decir las personas trans cuando hablan de 'derechos trans'?",
      "¿Por qué algunas personas trans dicen 'muerte antes que detransición'?",
      "¿Qué factores se cree que causan la disforia?",
      "¿Qué es la 'biblia de la disforia de género'?",
      "¿Qué estrategias (médicas o no médicas) ayudan a las personas a manejar la disforia?",
      "¿Las personas intersex son automáticamente trans?",
      "¿Qué es la fluidez de género?",
      "¿Qué significan AFAB y AMAB?",
      "¿Qué es una TERF?",
      "¿Qué es el uso de nombre muerto?",
      "¿Qué es el género incorrecto?",
      "¿Qué es una persona cisgénero?",
      "¿Qué se entiende por sexo biológico?",
      "¿Cuál es la diferencia entre transición social y transición médica?",
    ],
  },
  {
    title: "La Realidad Médica",
    description: "Salud, procedimientos y verdades biológicas",
    questions: [
      "¿Cuáles son los efectos adversos del uso de testosterona en mujeres?",
      "¿Cuáles son los efectos adversos del uso de estrógeno en hombres?",
      "¿Qué cambios fisiológicos puede inducir la testosterona en mujeres y cuáles son los límites?",
      "¿Qué cambios fisiológicos puede inducir el estrógeno en hombres y cuáles son los límites?",
      "¿En qué consiste la faloplastia y cuáles son los resultados típicos?",
      "¿En qué consiste la vaginoplastia y cuáles son los resultados típicos?",
      "¿Cuáles son los diferentes tipos de cirugía de vaginoplastia?",
      "¿Cómo debería alguien sopesar continuar versus discontinuar las hormonas?",
      "¿Existen diferencias medibles en las tasas de diagnóstico de disforia de género entre hombres y mujeres?",
      "¿Qué dice la investigación de imágenes cerebrales sobre los cerebros 'masculinos' versus 'femeninos'?",
      "¿Cómo se distingue la disforia de género de la enfermedad mental en los manuales diagnósticos?",
      "¿Qué es la atrofia vaginal y qué la causa?",
      "¿Qué opciones de revisión quirúrgica existen para la vaginoplastia o la faloplastia?",
      "¿Cómo regulan los diferentes países la financiación pública para cirugías de género?",
      "¿Qué opciones existen para la reconstrucción de pecho después de la mastectomía?",
      "¿Qué son los bloqueadores de la pubertad y realmente solo pausan la pubertad?",
      "¿Es cierto que los bloqueadores de la pubertad son el mismo medicamento que se usa para castrar químicamente a delincuentes sexuales?",
      "¿Qué datos de seguimiento a largo plazo existen para el uso de hormonas cruzadas?",
      "¿Qué son los Estándares de Atención de WPATH y cómo se desarrollan?",
      "¿Qué es el Protocolo Holandés?",
      "¿Qué es la disforia de género de inicio rápido (ROGD) y cómo se estudia?",
      "¿Cuáles son las tasas de arrepentimiento reportadas para varias cirugías de género?",
      "¿Cómo se ve la terapia exploratoria de género en la práctica?",
    ],
  },
  {
    title: "Sociedad y Cultura",
    description: "Cómo interactúan las creencias de género con el mundo",
    questions: [
      "¿Cuáles son las implicaciones de la narrativa de 'nací así'?",
      "¿Las identidades de género son el reempaquetado y refuerzo de estereotipos sexistas?",
      "¿Cómo ha cambiado el feminismo convencional con el tiempo para acomodar las identidades transgénero?",
      "¿Cómo puede la cultura de los pronombres llevar a la sobremedicalización de los niños?",
      "¿Cuáles son los resultados documentados para niños que hacen transición social temprana?",
      "¿Cuáles son los vínculos entre BDSM e identidades trans?",
      "¿Cómo ha evolucionado históricamente el concepto de género?",
      "¿Cómo ha interactuado el activismo trans con el activismo anterior por derechos gay?",
      "¿Cómo afectan los mantras o esloganes repetitivos el pensamiento crítico en cualquier comunidad?",
      "¿Cómo se intersecta el discurso contemporáneo de género con las identidades gay y lésbica?",
      "¿Qué podría explicar el aumento en la identificación no binaria?",
      "¿Qué explicaciones existen para el elevado riesgo de suicidio en poblaciones trans?",
      "¿Cómo afecta el riesgo percibido de suicidio el discurso público sobre la transición?",
      "¿Qué significa 'crítico de género' y en qué se diferencia de las visiones trans excluyentes?",
      "¿Qué es el 'debate de los baños' y qué evidencia existe sobre daño o seguridad?",
      "¿Cuáles son los argumentos principales en la controversia de la participación deportiva?",
      "¿Cómo han manejado las escuelas a los alumnos con cuestionamiento de género en diferentes jurisdicciones?",
      "¿Qué piensan las personas detrans sobre los cuentos de drag queen?",
      "¿Qué significa la frase 'medicalización de niños no conformes con el género' para los críticos y para los defensores?",
    ],
  },
  {
    title: "Psicología e Identidad",
    description: "Comprender los aspectos mentales y emocionales",
    questions: [
      "¿Puede alguien ser mujer sin ser femenina, o hombre sin ser masculino?",
      "¿Qué papel juegan las redes sociales en la adopción de identidades de género?",
      "¿Qué es el ciclo neuroquímico de validación?",
      "¿Por qué las personas autistas podrían estar sobrerrepresentadas en clínicas de género?",
      "¿Qué es la misoginia internalizada y cómo podría relacionarse con la angustia corporal?",
      "¿Qué es la homofobia internalizada?",
      "¿Qué es la autoginefilia y cómo se debate en la literatura?",
      "¿Qué es la euforia de género?",
      "¿Puede adoptar una identidad trans amplificar la disforia en lugar de aliviarla?",
      "¿Por qué es importante la validación externa para algunas personas trans?",
      "¿Cuál es la diferencia entre el trastorno dismórfico corporal y la disforia de género?",
      "¿Qué paralelos establecen los clínicos entre la disforia de género y los trastornos alimentarios?",
      "¿Cómo podrían interactuar los historiales de trauma con la disforia de género?",
      "¿Qué opciones no médicas existen para manejar la disforia?",
      "¿Qué significa 'pasar' y por qué puede convertirse en una obsesión para algunas personas?",
      "¿Cómo se relacionan los conceptos jungianos de ánima/ánimus con la identidad de género?",
      "¿Qué es el trabajo de la sombra y se puede usar en terapia?",
    ],
  },
  {
    title: "El Viaje de la Detransición",
    description: "Sanación, apoyo y encontrar tu camino de regreso",
    questions: [
      "¿Cómo puedo hacer las paces con los cambios permanentes que he hecho en mi cuerpo?",
      "Siento que algunas personas piensan que simplemente he 'vuelto al armario' y que no estoy viviendo auténticamente",
      "¿Es cierto que la mayoría de las personas detrans terminan haciendo retransición?",
      "¿Cómo pueden la transición y la detransición ser parte del mismo viaje de sanación?",
      "¿Dónde puede alguien encontrar terapeutas con experiencia en apoyo a la detransición?",
      "¿Significa la detransición que la transición original fue un fracaso?",
      "¿Ha ayudado la TCC o la DBT a las personas detrans en el manejo de la disforia?",
      "¿Por qué algunas comunidades trans desalientan la lectura de narrativas de detransición?",
      "¿Qué grupos de apoyo existen específicamente para personas detrans?",
      "¿Cómo puede alguien salir del armario (otra vez) a la familia como persona en detransición?",
      "¿Cuáles son las etapas comunes de duelo reportadas durante la detransición?",
      "¿Qué papel han jugado las drogas psicodélicas en algunas historias detrans?",
    ],
  },
  {
    title: "Sesgo Académico y de Investigación",
    description: "Cuestionando la narrativa en las instituciones",
    questions: [
      "¿Qué preocupaciones metodológicas se han planteado sobre las principales encuestas de detransición?",
      "¿Por qué los investigadores informan dificultades para asegurar financiamiento para estudios de detransición?",
      "¿Tienen los investigadores que actualmente se identifican como trans un conflicto de intereses?",
      "¿Qué fue la Revisión Cass y qué recomendaciones produjo?",
      "¿Qué pasó con el estudio de 2018 de Lisa Littman sobre ROGD?",
      "¿Qué es la revisión de la clínica Tavistock y por qué se encargó?",
      "¿Cómo fue reclasificada la disforia de género entre el DSM-IV y el DSM-5?",
    ],
  },
  {
    title: "Perspectivas Controvertidas",
    description:
      "Perspectivas detrans que los activistas de género realmente no quieren que escuches",
    questions: [
      "¿Quién está ganando dinero con la atención de afirmación de género?",
      "¿Qué factores estructurales llevan a la subrepresentación de historias de detransición en los medios convencionales?",
      "¿En qué formas se parecen los sistemas de creencias de género a religiones o cultos?",
      "¿Están las escuelas dejando de lado a los padres cuando los niños toman decisiones sobre identidad de género?",
      "¿Por qué hay tantos ladyboys en Tailandia?",
      "¿Por qué es Irán un centro global para cirugías de reasignación de sexo?",
    ],
  },
];
