export const questionCategories = [
  {
    title: "Starter Questions",
    description: "Some of the best questions to ask detrans people...",
    questions: [
      "Is gender a social construct?",
      "Can people be born in the wrong body?",
      "Why do some people feel like they were born in the wrong body?",
      "What is gender affirming care?",
      "What is gender exploratory therapy?",
      "Why is it so easy to get gender affirming care but so difficult to find gender exploratory therapy?",
      "Do detrans people regret modifying their bodies?",
      "I didn't choose to be trans!",
      "What's an egg?",
      "What is the closet?",
      "What is a belief system?",
      "Can trans identity cause dysphoria?",
      "What is an identity trap?",
      "How can I get out of an identity trap?",
      "How can I help someone else get out of an identity trap?",
      "How can I find a gender exploratory therapist?",
      "What is the difference between sex and gender?",
      "What is the difference between identifying and being?",
      "What is cancel culture?",
      "How is cancel culture harmful?",
      "Does transition ever end?",
      "Why do some women hate their breasts?",
      "How do online and IRL echo chambers cause psychosis?",
      "Why do detrans voices get silenced?",
      "Is gender ideology at odds with the goals of feminism?",
      "How does asking someone what their pronouns are, instead of asking if they are a man or a woman if you need to, reinforce sexist stereotypes?",
      "What are the main reasons that women adopt trans identity?",
      "What are the main reasons that men adopt trans identity?",
      "How do non-binary identities re-inforce sexist stereotypes and roles?",
      "Why do people identify vaguely as queer now?",
      "How does LGB differ from the T?",
      "Is there a link between autism and transgender identity?",
      "Is gender-affirming care based on science?",
      "Why is gender-affirming care currently considered the only solution to dysphoria?",
      "Is academic research on trans topics biased?",
      "Is teaching gender ideology to kids progressive?",
      "Is gender ideology fuelling a culture war?",
      "Is the culture war preventing humanity from solving real problems?",
      "Why do some refer to gender ideology as a mind virus?",
      "Why are the rates of people who identify as trans increasing?",
      "Is the trans suicide rate possibly mis-represented?",
      "Why do some trans people say 'death before detransition'?",
      "Why is gender dysphoria no longer treated as a mental health issue?",
      "How can gender-nonconformity liberate us from gender ideology?",
      "Why are there so many ladyboys in Thailand?",
      "Why is Iran a global hub for transgender surgeries?",
    ],
  },
  {
    title: "General Terms",
    description: "Understanding the fundamental concepts",
    questions: [
      "What is a man?",
      "What is a woman?",
      "What is gender?",
      "What's an egg?",
      "What are pronouns?",
      "What are trans rights?",
      "What is cancel culture?",
      "What is dysphoria?",
      "What causes dysphoria?",
      "What is the gender dysphoria bible?",
      "How can I overcome dysphoria?",
      "What is transgender identity?",
      "What is transphobia?",
      "What is non-binary identity?",
      "What is queer identity?",
      "What is personality?",
      "What is gender non-conformity (GNC)?",
      "What is gender conformity?",
      "What is detransitioning?",
      "What is desisting?",
      "Are intersex people trans?",
      "What is gender fluidity?",
      "What does AFAB/AMAB mean?",
      "What is a TERF?",
      "What is deadnaming?",
      "What is misgendering?",
      "What is a cisgender person?",
      "What is biological sex?",
      "What is social transition vs medical transition?",
    ],
  },
  {
    title: "The Medical Reality",
    description: "Health, procedures, and biological truths",
    questions: [
      "Can humans change sex?",
      "What are the health risks of hormones?",
      "Should I get off hormones?",
      "What is vaginoplasty?",
      "What is phalloplasty?",
      "Can I undo phalloplasty?",
      "Can I undo vaginoplasty?",
      "Should everyone else have to pay for transgender surgeries?",
      "I had a double masectomy, should I get breast implants?",
      "Should I get facial reconstruction surgery?",
      "Why are hormones often prescribed before a single therapy session?",
      "Does unrestricted access to hormones and surgeries provide good outcomes?",
      "Do detrans people think hormones should be banned?",
      "What is the science behind gender affirming care?",
      "What are puberty blockers and are they reversible?",
      "What happened to the light in my eyes?",
      "What are the long-term effects of cross-sex hormones?",
      "What are the WPATH Standards of Care?",
      "Are the WPATH Standards of Care based on science?",
      "What is the Dutch Protocol?",
      "What is rapid-onset gender dysphoria (ROGD)?",
      "What are the regret rates for gender surgeries?",
      "What is gender exploratory therapy?",
    ],
  },
  {
    title: "Society & Culture",
    description: "How gender beleif systems affects us all",
    questions: [
      "What are the transition rates for men vs women?",
      "Why is the trans suicide rate so high?",
      "Is being trans a mental illness?",
      "Is the trans suicide rate mis-represented?",
      "What does it mean to be gender critical?",
      "Do suicides based on regret get blamed on social acceptance?",
      "How does the trans community use mantras?",
      "Does the trans community encourage suicide?",
      "Does society believe that gender is a social construct?",
      "Does gender ideology affect society?",
      "What's the difference between being a tomboy and transgender?",
      "Are there male brains and female brains?",
      "Where did the term gender come from?",
      "Why are autistic people overrepresented in the trans community?",
      "How is gender ideology at odds with homosexual identities?",
      "How is gender ideology at odds with heterosexual identities?",
      "Did gender activists hijack the gay rights movement?",
      "How is gender ideology at odds with the goals of feminism?",
      "Is it beneficial to teach the idea that you can change sex to children?",
      "Do children ever grow up to regret transitioning at such a young age?",
      "What are the effects the transgender movement has on our wider society?",
      "Is gender ideology fuelling a culture war?",
      "Does transgender ideology contradict itself?",
      "Why are so many people identifying as trans or non-binary now? Is it a trend?",
      "Is it common for friends of trans people to become trans too?",
      "What is the bathroom debate about?",
      "What are trans rights vs women's rights conflicts?",
      "What is the sports participation controversy?",
      "What is the medicalization of gender non-conforming children?",
      "What is the history of trans activism?",
      "What do detrans people think about drag queen story hours?",
      "What is the difference between gender and sex?",
      "Why are there so many ladyboys in Thailand?",
      "Why is Iran a global hub for transgender surgeries?",
    ],
  },
  {
    title: "Psychology & Identity",
    description: "Understanding the mental and emotional aspects",
    questions: [
      "What is internalised misogyny?",
      "What is internalised misandry?",
      "What is internalised homophobia?",
      "What is autogynephilia?",
      "What is gender euphoria?",
      "What is a belief system?",
      "Can trans identity cause or reinforce dysphoria?",
      "What is an identity trap?",
      "Does transition ever end?",
      "What is validation so important to people who identify as trans?",
      "What is the neurochemical cycle of validation?",
      "What is body dysmorphia vs gender dysphoria?",
      "What is the role of social media in trans identification?",
      "What are some examples of media messaging that can lead to a misdiagnosis of gender dysphoria?",
      "What is the impact of pornography on gender dysphoria?",
      "What is the impact of trauma on gender dysphoria?",
      "Are trans people living authentically?",
      "Can you be a woman if you're not 'feminine'?",
      "Can you be a man if you're not 'masculine'?",
      "Why do some women hate their breasts?",
      "What causes some gender non-conforming people to adopt trans identity?",
      "Do some homosexual people transition to get access to heterosexual people?",
      "How do I know if I have internalised a victim mentality?",
      "Why do some people think that trans identity is a choice?",
      "What are a persons options with how they deal with dysphoria?",
      "What are the stages that lead to an obsession with 'passing'?",
      "What are the Jungian perspectives on transgender identity?",
      "What role do the anima and animus play in transgender identity?",
      "What unconcious shadows are playing out in people who transition?",
      "What is shadow work?",
    ],
  },
  {
    title: "The Detransition Journey",
    description: "Healing, support, and finding your way back",
    questions: [
      "Am I a failure if I detransition?",
      "Is transition just part of some people's healing journey?",
      "How can I help someone who feels like they were born in the wrong body?",
      "How can the comparison with eating disorderes help understand dysphoria?",
      "How can understanding the struggles of the other sex help me heal?",
      "I want to detransition, where do I start?",
      "How did I fall into an identity trap?",
      "How can I get out of an identity trap?",
      "What is gender exploratory therapy?",
      "What is CBT therapy?",
      "What is DBT therapy?",
      "How can I make peace with the changes I have made to my body?",
      "How can I learn to love myself and my unique personality, and find my inner peace?",
      "Why do trans people encourage other trans people not to read detransition stories?",
      "Why do detrans people get silenced from trans communities and wider society?",
      "Why do trans people tell detransitioners that they have internalised transphobia?",
      "How can I help others question the validity of their transgender identity?",
      "I think my friends will 'cancel' me for detransitioning!",
      "How do I find a therapist who supports detransition?",
      "How can I find a gender exploratory therapist?",
      "How do I tell my family I'm detransitioning?",
      "What support groups exist for detransitioners?",
      "How do I deal with shame about detransitioning?",
      "How do I rebuild my life after detransition?",
      "What are the stages of grief in detransition?",
      "Have psychedelic drugs helped some detrans people?",
    ],
  },
  {
    title: "Academic & Research Bias",
    description: "Questioning the narrative in institutions",
    questions: [
      "Is academic research on trans topics biased?",
      "Why is it so hard to find a gender critical therapist?",
      "Why was gender dysphoria removed from list of mental health disorders?",
      "What is the Cass Review?",
      "What happened to Lisa Littman's research?",
      "What are the methodological flaws in the 2015 detransition survey?",
      "Why are detransition studies so controversial?",
      "What is the Tavistock scandal?",
      "Why are researchers afraid to study detransition?",
    ],
  },
  {
    title: "The Controversial Truth",
    description:
      "Detrans perspectives that gender activists really don't want you to hear",
    questions: [
      "Why do some people call the trans movement a cult?",
      "Why do some people call the trans movement a mind virus?",
      "Are gender beliefs similar to religious beliefs?",
      "What is the connection between trans activism and pharmaceutical companies?",
      "Is there a financial incentive to promote transition?",
      "Why are detransitioners silenced in mainstream media?",
      "What is the role of schools in promoting gender ideology?",
      "Are parents being replaced by the state when it comes to gender decisions?",
    ],
  },
];
export const affirmingQuestionCategories = [
  {
    title: "Am I valid?",
    description: "Quick reassurance when you are doubting",
    questions: [
      "What's an egg?",
      "What causes dysphoria?",
      "What does it mean to be a woman?",
      "What does it mean to be a man?",
      "What does it mean to be a non-binary?",
      "Was I born in the wrong body?",
      "Are there male brains and female brains?",
      "How long will it take before I pass?",
      "Will I be happy once I pass?",
      "Am I trans enough if I do not have dysphoria every day?",
      "Can my identity shift over time?",
      "Do I need to prove anything to anyone?",
      "Are trans tomboys valid?",
      "Are trans femboys valid?",
      "Are trans women biological females?",
      "Are trans men biological males?",
      "What if I only feel dysphoric in certain situations?",
      "Is it okay to explore labels privately before telling anyone?",
      "What are the transition rates for trans men vs trans women?",
      "How can I overcome dysphoria?",
      "How do I know if I'm transgender and not just gender non-conforming?",
    ],
  },
  {
    title: "Names, pronouns and everyday life",
    description: "Practical tools for getting through the week",
    questions: [
      "How do I pick a name that still feels like me?",
      "What is the safest way to test pronouns online first?",
      "How do I correct people misgendering me without ruining the mood?",
      "How can I practice my voice without triggering dysphoria?",
      "What apps help me track gender euphoria moments?",
    ],
  },
  {
    title: "Dysphoria and mental health hacks",
    description: "Coping with feeling uncomfortable in your body",
    questions: [
      "I've always been a feminine man, am I trans?",
      "What are five minute grounding exercises for body dysphoria?",
      "How do I tell the difference between dysphoria and ordinary body image bad days?",
      "Can hormones or surgery be one tool but not the whole toolbox?",
      "What do I do if my dysphoria spikes after starting HRT?",
      "How can meditation help dysphoria?",
      "Where can I find free, trans competent crisis lines?",
    ],
  },
  {
    title: "Medical roadmap, no pressure",
    description: "Consider your options before making big decisions.",
    questions: [
      "What are the health effects and risks of HRT?",
      "At what age should I start HRT?",
      "What is the usual order of steps if I want hormones in my country?",
      "What are the reversible versus irreversible changes of HRT with a timeline chart?",
      "How do I check whether my insurance covers blockers or HRT?",
      "What questions should I ask the endocrinologist at the first consult?",
      "What is the actual regret rate cited by major studies with citations?",
      "Can I bank sperm or eggs on a tight budget?",
      "I'm non-binary, should I get nullifcation surgery?",
      "Should I get phaloplasty surgery?",
      "How do I find a good surgeon for phalloplasty surgery?",
      "Should I get vaginoplasty?",
      "What are the different types of vaginoplasty surgery?",
      "How do I find a good surgeon for vaginoplasty surgery?",
      "When will my vagina be a vagina?",
      "What are the least invasive ways to deal with facial hair?",
      "What is the real scoop on puberty blocker reversibility in 2024?",
    ],
  },
  {
    title: "Family, dating and coming out",
    description: "Scripts and safety plans",
    questions: [
      "How do I come out to a partner who says they are super straight?",
      "How do I protect my privacy if I am not ready to tell my parents?",
      "What are red flags that a therapist is not gender affirming?",
      "How can I find local trans meet ups that are not Facebook based?",
      "What are my rights at school or work in my state or country?",
    ],
  },
  {
    title: "Trans Sex Life & Intimacy Guide",
    description:
      "Safer sex, dysphoria hacks and pleasure tips for trans, non-binary and post-op bodies",
    questions: [
      "What are safe sex toys for trans women with bottom dysphoria?",
      "What is the best dilator schedule after trans vaginoplasty surgery?",
      "How can I ask my partner for trans affirming dirty talk?",
      "What are the contraception options available for trans men on testosterone?",
      "Why are my top surgery scars are sensitive during sex?",
      "What erection aids are there for trans women on HRT?",
      "Is it normal for your orgasm to change after starting testosterone?",
      "How to navigate hookup apps safely as a trans person?",
      "Why am I so horny after starting testosterone?",
      "How can I disclose my trans identity to a casual partner?",
      "Dealing with bottom dysphoria during sex trans tips",
      "What lube ingredients should I avoid post vaginoplasty as a trans woman",
      "Which sex positions minimise hip dysphoria for trans women?",
      "How to maintain anal health after phalloplasty?",
      "How to find trans friendly STI testing clinics?",
      "How to find low cost viagra or cialis for trans women MTF?",
    ],
  },
];

export const affirmingDetransQuestions = [
  {
    title: "De-transitioning and Re-transitioning",
    description:
      "Explore the sensitive topics of de-transition and re-transition from a detrans perspective to make sure you're informed.",
    questions: [
      "Why do some people de-transition?",
      "How many people de-transition?",
      "Why do some people re-transition after de-transitioning?",
    ],
  },
];

export const compareQuestions = [
  {
    title: "Compare Questions",
    description: "Spicy questions to ask both trans and detrans people...",
    questions: [
      "What is a man?",
      "What is a woman?",
      "Are trans men biological males?",
      "Are trans women biological women?",
      "What is gender affirming care?",
      "What is gender exploratory therapy?",
      "Can people be born in the wrong body?",
      "Why do some people de-transition?",
      "How many people de-transition?",
      "Why do some people re-transition after de-transitioning?",
      "What's an egg?",
      "What's the closet?",
      "What is feminism?",
      "What is non-binary identity?",
      "Does transition ever end?",
      "Why do some women hate their breasts?",
      "Why do some people de-transition?",
      "Were detrans people real trans people?",
      "Why do people identify as queer now?",
      "Is gender-affirming care based on science?",
      "Why are the rates of people who identify as trans increasing?",
      "Why is gender dysphoria no longer treated as a mental health issue?",
    ],
  },
];
