/**
 * Dansk oversættelse af spørgsmålskategorier og udvalgte spørgsmål til detrans.ai
 *
 * NOTER OM KØNSRELATERET TERMINOLOGI:
 * - "Biologisk køn" (Sex) = biologisk køn (anatomi, kromosomer, reproduktion, uforanderlige karakteristika)
 * - "Socialt køn" (Gender) = socialt køn (roller, adfærd, attributter som samfundet anser for passende
 *   for mænd og kvinder baseret på deres biologiske køn)
 * - "Kønsidentitet" (Gender identity) = indre følelse af at være mand, kvinde eller et sted imellem
 * - "Kønsnonkonformitet (GNC)" (Gender non-conformity) = når en person handler/præsenterer sig anderledes 
 *   end samfundets forventninger baseret på deres biologiske køn
 * - "Tildelt køn ved fødslen" (AFAB/AMAB) = tildelt kvinde/mand ved fødslen (baseret på observeret biologisk køn)
 * - "Transkønnet/trans" (Transgender/trans) = identificerer sig med et køn der adskiller sig fra ens biologiske køn
 * - "Detransition" (Detransition) = ophører med at identificere sig som transkønnet og/eller ophæver transitionstrin
 * - "Desistens" (Desist) = når nogen, der identificerede sig som trans (uden medicinske indgreb), ikke længere 
 *   identificerer sig som trans
 *
 * VIGTIG DISTINKTION: Kønsdysphori som koncept er afhængig af forståelsen af, at biologisk køn og socialt 
 * køn er forskellige. Kønsnonkonformitet (passer ikke ind i stereotyper) er forskellig fra at have en kønsidentitet 
 * der adskiller sig fra ens biologiske køn.
 */

export const questionCategories = [
  {
    title: "Fremhævede Spørgsmål",
    description: "De bedste spørgsmål at stille til detrans-mennesker.",
    questions: [
      "Hvad betyder trans?",
      "Har transkønnede mennesker altid eksisteret?",
      "Er det sandt at kun 1% detransitionerer?",
      "Er pubertetsblokkere reversible?",
      "Hvilke beviser findes der for kønsbekræftende medicinske protokoller?",
      "Hvad betyder udtrykket 'æg' i transmiljøer?",
      "Hvad er implikationerne af 'født sådan'-narrativet?",
      "Hvordan forstærker ikke-binære etiketter traditionelle kønsstereotyper?",
      "Hvad er forskellen på biologisk køn og socialt køn?",
      "Hvad er kønsdysphori og hvad kan forårsage det?",
      "Hvorfor beslutter nogle mennesker sig for at detransitionere?",
      "Hvordan kan venner eller familie støtte nogen der ønsker at transitionere?",
      "Hvordan kan venner eller familie støtte nogen der ønsker at detransitionere?",
      "Er det almindeligt at detransitionerede fortryder at have transitioneret?",
      "Hvorfor beslutter nogle mennesker sig for at retransitionere efter detransition?",
      "Hvad kan detransitioneredes historier lære mig, selvom min transition går godt indtil videre?",
      "Hvordan ved jeg om tvivl bare er nerver eller et tegn på at jeg skal stoppe?",
      "Hvorfor adskiller transnarrativer om hvorfor folk detransitionerer sig fra dem der faktisk har detransitioneret?",
      "Mener detransitionerede at transition i sig selv er dårligt?",
      "Hvilke falske påstande fremsættes om transkønnede mennesker?",
      "Hvilke falske påstande fremsættes om mennesker der har detransitioneret?",
      "Hvilke tidlige tegn ønsker detransitionerede at de havde lagt mærke til tidligere?",
      "Er køn en social konstruktion? Hvad betyder det?",
      "Hvordan har feministiske bevægelser historisk betragtet begrebet køn?",
      "Hvordan kan kønsnonkonformitet reducere presset for at leve op til kønsroller?",
      "Hvordan beskriver detransitionerede følelsen af at være 'født i den forkerte krop'?",
      "Hvad er kønsbekræftende behandling og hvad er dens mål?",
      "Hvorfor er kønsbekræftende behandling normalt den eneste mulighed i de fleste regioner?",
      "Hvordan adskiller kønseksplorativ terapi sig fra kønsbekræftende behandling?",
      "Hvorfor kan nogle mennesker ikke lide konceptet med kønseksplorativ terapi, og hvorfor er det forbudt nogle steder?",
      "Mener detransitionerede at kønsbekræftende behandling og hormoner bør forbydes?",
      "Fortryder detransitionerede normalt medicinske skridt, sociale skridt eller begge dele?",
      "Hvad er en identitetsfælde og hvordan indser folk typisk at de er i en?",
      "Hvor kan man finde en terapeut der tilbyder åben, ikke-direktiv kønseksploration? Hvilke advarselssignaler skal jeg holde øje med?",
      "Hjælper eller hindrer det at spørge om pronominer kønsnonkonforme mennesker?",
      "Hvis en ung pige med kort hår konstant bliver spurgt om sine pronominer, hvad er implikationen og hvordan ville hun føle sig?",
      "Hvad er cancelkultur og hvilke effekter har det på den offentlige sundhedsdiskurs?",
      "Ser detransitionerede transition som en proces med et slutpunkt eller som en igangværende proces?",
      "Hvorfor kan nogle unge piger opleve nød over brystudvikling?",
      "Hvordan kan online ekkokamre påvirke identitetsdannelsen?",
      "Hvorfor rapporterer detransitionerede ofte at føle deres historier og stemmer bliver tiet ihjel i både trans- og mainstream-miljøer?",
      "Hvilke demografiske mønstre er synlige i henvisninger til kønsklinikker?",
      "Hvordan adskiller moderne queeridentiteter sig fra den tidligere LGB-bevægelse?",
      "Hvad siger aktuel forskning om overlap mellem autisme-spektrum-træk, kønsdysphori og transkønnede identiteter?",
      "Hvorfor er kønsdysphori ikke længere klassificeret som en psykisk lidelse i DSM-5?",
      "Hvordan har transprævalensen ændret sig på det seneste og hvad kan forklare dette?",
    ],
  },
  {
    title: "Generelle Begreber",
    description: "Forståelse af de grundlæggende koncepter",
    questions: [
      "Hvad er en mand?",
      "Hvad er en kvinde?",
      "Hvad er køn?",
      "Hvad er kønsdysphori?",
      "Hvad er transkønnet identitet?",
      "Hvad er transfobi?",
      "Hvad er cancelkultur?",
      "Hvad er ikke-binær identitet?",
      "Hvad er queeridentitet?",
      "Hvad er queerteori?",
      "Hvad er personlighed?",
      "Hvordan adskiller personlighed sig fra kønsidentitet?",
      "Hvad er kønsnonkonformitet (GNC)?",
      "Hvad er kønskonformitet?",
      "Hvad er detransition?",
      "Hvad er at desistere?",
      "Hvad er pronominer og hvorfor er de vigtige for nogle?",
      "Hvad mener transkønnede mennesker når de taler om 'transrettigheder'?",
      "Hvorfor siger nogle transkønnede mennesker 'hellere død end detransition'?",
      "Hvilke faktorer antages at forårsage dysphori?",
      "Hvad er 'kønsdysphori-bibelen'?",
      "Hvilke strategier (medicinske eller ikke-medicinske) hjælper folk med at håndtere dysphori?",
      "Er interseksuelle mennesker automatisk transkønnede?",
      "Hvad er kønsfluiditet?",
      "Hvad betyder AFAB og AMAB?",
      "Hvad er en TERF?",
      "Hvad er deadnaming?",
      "Hvad er misgendering?",
      "Hvad er en ciskønnet person?",
      "Hvad menes der med biologisk køn?",
      "Hvad er forskellen mellem social og medicinsk transition?",
    ],
  },
  {
    title: "Den Medicinske Virkelighed",
    description: "Sundhed, procedurer og biologiske sandheder",
    questions: [
      "Hvad er de bivirkninger af testosteron hos kvinder?",
      "Hvad er de bivirkninger af østrogen hos mænd?",
      "Hvilke fysiologiske ændringer kan testosteron forårsage hos kvinder og hvad er grænserne?",
      "Hvilke fysiologiske ændringer kan østrogen forårsage hos mænd og hvad er grænserne?",
      "Hvad indebærer en falloplastik og hvad er typiske resultater?",
      "Hvad indebærer en vaginoplastik og hvad er typiske resultater?",
      "Hvilke forskellige typer vaginoplastik-kirurgi findes der?",
      "Hvordan bør man afveje at fortsætte versus ophøre med hormoner?",
      "Findes der målbare forskelle i kønsdysphori-diagnoser mellem mænd og kvinder?",
      "Hvad siger hjerneskanninger om 'mandlige' versus 'kvindelige' hjerner?",
      "Hvordan adskilles kønsdysphori fra psykisk sygdom i diagnostiske manualer?",
      "Hvad er vaginal atrofi og hvad forårsager det?",
      "Hvilke kirurgiske revisionsmuligheder findes for enten vaginoplastik eller falloplastik?",
      "Hvordan regulerer forskellige lande offentlig finansiering af kønskirurgi?",
      "Hvilke muligheder findes der for brystrekonstriktion efter mastektomi?",
      "Hvad er pubertetsblokkere og pauserer de virkelig kun puberteten?",
      "Er det sandt at pubertetsblokkere er den samme medicin der bruges til kemisk kastration af sexforbrydere?",
      "Hvilke langtidsopfølgninger findes der for brug af kønsskiftende hormoner?",
      "Hvad er WPATH Standards of Care og hvordan udvikles de?",
      "Hvad er den hollandske protokol?",
      "Hvad er hurtig debuterende kønsdysphori (ROGD) og hvordan undersøges den?",
      "Hvad er de rapporterede fortrydelsesrater for forskellige kønskirurgier?",
      "Hvordan ser kønseksplorativ terapi ud i praksis?",
    ],
  },
  {
    title: "Samfund & Kultur",
    description: "Hvordan kønsoverbevisninger interagerer med verden",
    questions: [
      "Hvad er implikationerne af 'født sådan'-narrativet?",
      "Er kønsidentiteter en ompakning og forstærkning af sexistiske stereotyper?",
      "Hvordan har mainstream-feminisme ændret sig over tid for at rumme transkønnede identiteter?",
      "Hvordan kan pronominkultur føre til overmedicinering af børn?",
      "Hvad er de dokumenterede resultater for børn der transitionerer socialt tidligt?",
      "Hvilke forbindelser findes der mellem BDSM og transidentiteter?",
      "Hvordan har begrebet køn udviklet sig historisk?",
      "Hvordan har transaktivisme interageret med tidligere homorettighedsaktivisme?",
      "Hvordan påvirker repetitive mantraer eller slogans kritisk tænkning i ethvert samfund?",
      "Hvordan skærer moderne kønsdiskurs med homoseksuelle og lesbiske identiteter?",
      "Hvad kan forklare stigningen i ikke-binær identifikation?",
      "Hvilke forklaringer findes på den forhøjede selvmordsrisiko i transpopulationer?",
      "Hvordan påvirker den opfattede selvmordsrisiko den offentlige diskurs om transition?",
      "Hvad betyder 'kønskritisk' og hvordan adskiller det sig fra trans-ekskluderende synspunkter?",
      "Hvad er 'toiletdebatten' og hvilke beviser findes for enten skade eller sikkerhed?",
      "Hvad er de hovedargumenter i sport-deltagelseskontroversen?",
      "Hvordan har skoler håndteret kønsspørgende elever i forskellige retsområder?",
      "Hvad mener detransitionerede om drag queen-fortælling?",
      "Hvad betyder begrebet 'medicinering af kønsnonkonforme børn' for kritikere og fortalere?",
    ],
  },
  {
    title: "Psykologi & Identitet",
    description: "Forståelse af de mentale og følelsesmæssige aspekter",
    questions: [
      "Kan nogen være en kvinde uden at være feminin, eller en mand uden at være maskulin?",
      "Hvilken rolle spiller sociale medier i at folk overtager kønsidentiteter?",
      "Hvad er den neurokemiske cirkel af validering?",
      "Hvorfor kan autistiske mennesker være overrepræsenterede i kønsklinikker?",
      "Hvad er internaliseret misogyni og hvordan kan det relatere til kropsnød?",
      "Hvad er internaliseret homofobi?",
      "Hvad er autogynefili og hvordan debatteres det i litteraturen?",
      "Hvad er kønseufori?",
      "Kan det at overtage en transidentitet forstærke dysphori i stedet for at lindre det?",
      "Hvorfor er ekstern validering vigtig for nogle transkønnede mennesker?",
      "Hvad er forskellen på kropsdysmorfi og kønsdysphori?",
      "Hvilke paralleller drager klinikere mellem kønsdysphori og spiseforstyrrelser?",
      "Hvordan kan traumehistorier interagere med kønsdysphori?",
      "Hvilke ikke-medicinske muligheder findes for at håndtere dysphori?",
      "Hvad betyder 'at passe' (passing) og hvorfor kan det blive en besættelse for nogle?",
      "Hvordan relaterer jungianske koncepter om anima/animus til kønsidentitet?",
      "Hvad er skyggearbejde (shadow work) og kan det bruges i terapi?",
    ],
  },
  {
    title: "Detransition-Rejsen",
    description: "Helbredelse, støtte og at finde vejen tilbage",
    questions: [
      "Hvordan kan jeg gøre fred med de permanente ændringer jeg har gjort ved min krop?",
      "Jeg har følelsen af at nogle mennesker tror jeg bare er gået 'tilbage i skabet' og ikke lever autentisk",
      "Er det sandt at de fleste detransitionerede ender med at retransitionere?",
      "Hvordan kan både transition og detransition være en del af den samme helbredelsesrejse?",
      "Hvor kan man finde terapeuter med erfaring i detransitionsstøtte?",
      "Betyder detransition at den oprindelige transition var en fiasko?",
      "Har CBT eller DBT hjulpet detransitionerede med at håndtere dysphori?",
      "Hvorfor fraråder nogle transmiljøer at læse detransitionsfortællinger?",
      "Hvilke støttegrupper findes specifikt for detransitionerede?",
      "Hvordan kan nogen komme ud (igen) over for familien som detransitionerende?",
      "Hvad er almindelige sorgstadier rapporteret under detransition?",
      "Hvilken rolle har psykedeliske stoffer spillet i nogle detranshistorier?",
    ],
  },
  {
    title: "Akademisk & Forskningsbias",
    description: "Sætter spørgsmål ved narrativet i institutioner",
    questions: [
      "Hvilke metodiske bekymringer er rejst om store detransitionsundersøgelser?",
      "Hvorfor rapporterer forskere vanskeligheder med at sikre finansiering til detransitionsstudier?",
      "Har forskere der i øjeblikket identificerer sig som trans en interessekonflikt?",
      "Hvad var Cass Review og hvilke anbefalinger kom den med?",
      "Hvad skete der med Lisa Littmans undersøgelse fra 2018 om ROGD?",
      "Hvad er Tavistock-klinikkens gennemgang og hvorfor blev den bestilt?",
      "Hvordan blev kønsdysphori reklassificeret mellem DSM-IV og DSM-5?",
    ],
  },
  {
    title: "Kontroversielle Perspektiver",
    description:
      "Detransperspektiver, som kønsaktivister virkelig ikke vil have dig til at høre",
    questions: [
      "Hvem tjener penge på kønsbekræftende behandling?",
      "Hvilke strukturelle faktorer fører til underrepræsentation af detransitionshistorier i mainstream-medier?",
      "På hvilke måder ligner kønsoverbevisningssystemer religioner eller sekter?",
      "Sætter skoler forældre til side når børn træffer valg om kønsidentitet?",
      "Hvorfor er der så mange ladyboys i Thailand?",
      "Hvorfor er Iran et globalt centrum for kønsskiftende kirurgi?",
    ],
  },
];
