/**
 * Svensk översättning av frågekategorier och utvalda frågor för detrans.ai
 *
 * Anmärkningar om könsrelaterad terminologi:
 * - "Kön" (biologiskt kön) = biological sex (anatomi, kromosomer, reproduktion, oföränderliga egenskaper)
 * - "Genus" (socialt kön) = social gender (roller, beteenden, attribut som samhället anser lämpliga
 *   för män och kvinnor baserat på deras biologiska kön)
 * - "Könsidentitet" = inre känsla av att vara man, kvinna eller något däremellan
 * - "Könsöverskridande (GNC)" = när en person agerar/presenterar sig annorlunda än samhällets
 *   förväntningar baserat på deras biologiska kön
 * - "AFAB/AMAB" = tilldelad kvinna/man vid födseln (baserat på observerat biologiskt kön)
 * - "Transperson/trans" = identifierar sig med ett kön som skiljer sig från ens biologiska kön
 * - "Detransition" = upphör med att identifiera sig som transperson och/eller återgår från transition
 * - "Desistera" = när någon som identifierade sig som trans (utan medicinska ingrepp) inte längre
 *   identifierar sig som trans
 *
 * Viktig distinktion: Könsdysfori som koncept förutsätter förståelsen att biologiskt kön och socialt
 * kön är olika. Könsöverskridande (att inte passa in i stereotyper) skiljer sig från att ha en
 * könsidentitet som skiljer sig från ens biologiska kön.
 */

export const questionCategories = [
  {
    title: "Utvalda frågor",
    description: "De bästa frågorna att ställa till människor med detransitionserfarenhet.",
    questions: [
      "Vad betyder trans?",
      "Har transpersoner alltid funnits?",
      "Är det sant att endast 1% detransitionerar?",
      "Är pubertetsblockerare reversibla?",
      "Vilka bevis finns för könsbekräftande medicinska protokoll?",
      "Vad betyder termen 'ägg' i transgemenskaper?",
      "Vilka är implikationerna av 'född sådan'-berättelsen?",
      "Hur förstärker icke-binära etiketter traditionella könsstereotyper?",
      "Vad är skillnaden mellan kön och genus?",
      "Vad är könsdysfori och vad kan orsaka det?",
      "Varför beslutar sig vissa människor för att detransitionera?",
      "Hur kan vänner eller familj stödja någon som vill transitionera?",
      "Hur kan vänner eller familj stödja någon som vill detransitionera?",
      "Är det vanligt att detransitionerade ångrar att de har transitionerat?",
      "Varför beslutar sig vissa människor för att återtransitionera efter detransition?",
      "Vad kan detransitionerades berättelser lära mig, även om min transition går bra hittills?",
      "Hur vet jag om tvivel bara är nerver eller ett tecken på att jag ska sluta?",
      "Varför skiljer sig transberättelser om varför folk detransitionerar från de som faktiskt har detransitionerat?",
      "Anser detransitionerade att transition i sig är dåligt?",
      "Vilka falska påståenden görs om transpersoner?",
      "Vilka falska påståenden görs om människor som har detransitionerat?",
      "Vilka tidiga tecken önskar detransitionerade att de hade lagt märke till tidigare?",
      "Är genus en social konstruktion? Vad betyder det?",
      "Hur har feministiska rörelser historiskt betraktat begreppet genus?",
      "Hur kan könsöverskridande minska pressen att följa könsroller?",
      "Hur beskriver detransitionerade känslan av att vara 'född i fel kropp'?",
      "Vad är könsbekräftande vård och vad är dess mål?",
      "Varför är könsbekräftande vård vanligtvis det enda alternativet i de flesta regioner?",
      "Hur skiljer sig könsexplorativ terapi från könsbekräftande vård?",
      "Varför tycker vissa människor inte om konceptet med könsexplorativ terapi, och varför är det förbjudet på vissa platser?",
      "Anser detransitionerade att könsbekräftande vård och hormoner bör förbjudas?",
      "Ångrar detransitionerade vanligtvis medicinska steg, sociala steg eller båda?",
      "Vad är en identitetsfälla och hur inser människor vanligtvis att de är i en?",
      "Var kan någon hitta en terapeut som erbjuder öppen, icke-direktiv könsexploration? Vilka varningstecken ska jag se upp med?",
      "Hjälper eller hindrar det att fråga om pronomen könsöverskridande människor?",
      "Om en ung flicka med kort hår konstant blir tillfrågad om sina pronomen, vad är implikationen och hur skulle hon känna sig?",
      "Vad är cancelkultur och vilka effekter har det på den offentliga hälsodiskursen?",
      "Ser detransitionerade transition som en process med ett slut eller som en pågående process?",
      "Varför kan vissa unga flickor uppleva nöd över bröstutveckling?",
      "Hur kan online-ekokammare påverka identitetsbildning?",
      "Varför rapporterar detransitionerade ofta att de känner att deras berättelser och röster tystas i både trans- och mainstream-miljöer?",
      "Vilka demografiska mönster är synliga i remisser till könskliniker?",
      "Hur skiljer sig samtida queeridentiteter från den tidigare HBT-rörelsen?",
      "Vad säger aktuell forskning om överlappning mellan autismspektrumdrag, könsdysfori och transidentiteter?",
      "Varför klassificeras könsdysfori inte längre som en psykisk störning i DSM-5?",
      "Hur har transprevalens förändrats på senare tid och vad kan förklara detta?",
    ],
  },
  {
    title: "Allmänna begrepp",
    description: "Att förstå de grundläggande koncepten",
    questions: [
      "Vad är en man?",
      "Vad är en kvinna?",
      "Vad är genus?",
      "Vad är könsdysfori?",
      "Vad är transidentitet?",
      "Vad är transfobi?",
      "Vad är cancelkultur?",
      "Vad är icke-binär identitet?",
      "Vad är queeridentitet?",
      "Vad är queerteori?",
      "Vad är personlighet?",
      "Hur skiljer sig personlighet från könsidentitet?",
      "Vad är könsöverskridande (GNC)?",
      "Vad är könskonformitet?",
      "Vad är detransition?",
      "Vad är att desistera?",
      "Vad är pronomen och varför är de betydelsefulla för vissa?",
      "Vad menar transpersoner när de talar om 'transrättigheter'?",
      "Varför säger vissa transpersoner 'hellre död än detransition'?",
      "Vilka faktorer antas orsaka dysfori?",
      "Vad är 'könsdysforibibeln'?",
      "Vilka strategier (medicinska eller icke-medicinska) hjälper människor att hantera dysfori?",
      "Är intersexuella människor automatiskt transpersoner?",
      "Vad är könsfluiditet?",
      "Vad betyder AFAB och AMAB?",
      "Vad är en TERF?",
      "Vad är deadnaming?",
      "Vad är misgendering?",
      "Vad är en cisperson?",
      "Vad menas med biologiskt kön?",
      "Vad är skillnaden mellan social och medicinsk transition?",
    ],
  },
  {
    title: "Den medicinska verkligheten",
    description: "Hälsa, ingrepp och biologiska sanningar",
    questions: [
      "Vilka är biverkningarna av testosteronanvändning hos kvinnor?",
      "Vilka är biverkningarna av östrogenanvändning hos män?",
      "Vilka fysiologiska förändringar kan testosteron orsaka hos kvinnor och vad är begränsningarna?",
      "Vilka fysiologiska förändringar kan östrogen orsaka hos män och vad är begränsningarna?",
      "Vad innebär falloplastik och vad är typiska resultat?",
      "Vad innebär vaginoplastik och vad är typiska resultat?",
      "Vilka olika typer av vaginoplastikkirurgi finns det?",
      "Hur bör någon väga att fortsätta kontra att sluta med hormoner?",
      "Finns det mätbara skillnader i könsdysforidiagnoser mellan män och kvinnor?",
      "Vad säger hjärnavbildningsforskning om 'manliga' kontra 'kvinnliga' hjärnor?",
      "Hur skiljs könsdysfori från psykisk sjukdom i diagnostiska manualer?",
      "Vad är vaginal atrofi och vad orsakar det?",
      "Vilka kirurgiska revisionsalternativ finns för antingen vaginoplastik eller falloplastik?",
      "Hur reglerar olika länder offentlig finansiering av könskirurgi?",
      "Vilka alternativ finns för bröstrekonstuktion efter mastektomi?",
      "Vad är pubertetsblockerare och pausar de verkligen bara puberteten?",
      "Är det sant att pubertetsblockerare är samma läkemedel som används för att kemiskt kastrera sexförbrytare?",
      "Vilka långtidsuppföljningsdata finns för användning av könshormoner?",
      "Vad är WPATH Standards of Care och hur utvecklas de?",
      "Vad är den nederländska protokollen?",
      "Vad är snabbt insättande könsdysfori (ROGD) och hur studeras det?",
      "Vilka rapporterade ångerrater finns för olika könskirurgier?",
      "Hur ser könsexplorativ terapi ut i praktiken?",
    ],
  },
  {
    title: "Samhälle och kultur",
    description: "Hur könsövertygelser interagerar med världen",
    questions: [
      "Vilka är implikationerna av 'född sådan'-berättelsen?",
      "Är könsidentiteter en ompackning och förstärkning av sexistiska stereotyper?",
      "Hur har mainstream-feminism förändrats över tid för att rymma transidentiteter?",
      "Hur kan pronomenkultur leda till övermedicinering av barn?",
      "Vad är dokumenterade resultat för barn som socialt transitionerar tidigt?",
      "Vilka kopplingar finns mellan BDSM och transidentiteter?",
      "Hur har genusbegreppet utvecklats historiskt?",
      "Hur har transaktivism interagerat med tidigare HBT-aktivism?",
      "Hur påverkar repetitiva mantra eller slogans kritiskt tänkande i alla gemenskaper?",
      "Hur skär nutida genusdiskurs med homosexuella och lesbiska identiteter?",
      "Vad kan förklara ökningen i icke-binär identifiering?",
      "Vilka förklaringar finns till förhöjd självmordsrisk i transpopulationer?",
      "Hur påverkar den upplevda självmordsrisken den offentliga diskursen om transition?",
      "Vad betyder 'könskritisk' och hur skiljer det sig från trans-uteslutande perspektiv?",
      "Vad är 'toalettdebatten' och vilka bevis finns för antingen skada eller säkerhet?",
      "Vilka är huvudargumenten i sportdeltagelsekontroversen?",
      "Hur har skolor hanterat könsfrågande elever i olika jurisdiktioner?",
      "Vad tycker detransitionerade om drag queen-berättande?",
      "Vad betyder begreppet 'medicinering av könsöverskridande barn' för kritiker och förespråkare?",
    ],
  },
  {
    title: "Psykologi och identitet",
    description: "Att förstå de mentala och emotionella aspekterna",
    questions: [
      "Kan någon vara en kvinna utan att vara feminin, eller en man utan att vara maskulin?",
      "Vilken roll spelar sociala medier i att människor antar könsidentiteter?",
      "Vad är den neurokemiska cirkeln av validering?",
      "Varför kan autistiska människor vara överrepresenterade i könskliniker?",
      "Vad är internaliserad misogyni och hur kan det relatera till kroppsnöd?",
      "Vad är internaliserad homofobi?",
      "Vad är autogynefili och hur debatteras det i litteraturen?",
      "Vad är könseufori?",
      "Kan antagande av en transidentitet förstärka dysfori istället för att lindra det?",
      "Varför är extern validering viktig för vissa transpersoner?",
      "Vad är skillnaden mellan kroppsdysmorfi och könsdysfori?",
      "Vilka paralleller drar kliniker mellan könsdysfori och ätstörningar?",
      "Hur kan traumahistorier interagera med könsdysfori?",
      "Vilka icke-medicinska alternativ finns för att hantera dysfori?",
      "Vad betyder 'passa' (passing) och varför kan det bli en besatthet för vissa?",
      "Hur relaterar jungianska koncept om anima/animus till könsidentitet?",
      "Vad är skuggarbete (shadow work) och kan det användas i terapi?",
    ],
  },
  {
    title: "Detransitionsresan",
    description: "Läkning, stöd och att hitta vägen tillbaka",
    questions: [
      "Hur kan jag göra fred med de permanenta förändringar jag har gjort med min kropp?",
      "Jag har känslan av att vissa människor tror att jag bara har gått 'tillbaka i garderoben' och inte lever autentiskt",
      "Är det sant att de flesta detransitionerade slutar med att återtransitionera?",
      "Hur kan både transition och detransition vara en del av samma läkningsresa?",
      "Var kan någon hitta terapeuter med erfarenhet av detransitionsstöd?",
      "Betyder detransition att den ursprungliga transitionen var ett misslyckande?",
      "Har KBT eller DBT hjälpt detransitionerade med att hantera dysfori?",
      "Varför avråder vissa transgemenskaper från att läsa detransitionsberättelser?",
      "Vilka stödgrupper finns specifikt för detransitionerade?",
      "Hur kan någon komma ut (igen) inför familjen som detransitionerande?",
      "Vilka är vanliga sorgstadier som rapporteras under detransition?",
      "Vilken roll har psykedeliska droger spelat i vissa detransberättelser?",
    ],
  },
  {
    title: "Akademisk och forskningsmässig bias",
    description: "Att ifrågasätta narrativet i institutioner",
    questions: [
      "Vilka metodiska farhågor har väckts om stora detransitionsstudier?",
      "Varför rapporterar forskare svårigheter att säkra finansiering för detransitionsstudier?",
      "Har forskare som för närvarande identifierar sig som trans en intressekonflikt?",
      "Vad var Cass Review och vilka rekommendationer kom den med?",
      "Vad hände med Lisa Littmans studie från 2018 om ROGD?",
      "Vad är Tavistock-klinikens granskning och varför beställdes den?",
      "Hur omklassificerades könsdysfori mellan DSM-IV och DSM-5?",
    ],
  },
  {
    title: "Kontroversiella perspektiv",
    description:
      "Detrans-perspektiv som genusaktivister verkligen inte vill att du ska höra",
    questions: [
      "Vem tjänar pengar på könsbekräftande vård?",
      "Vilka strukturella faktorer leder till underrepresentation av detransitionsberättelser i mainstream-medier?",
      "På vilka sätt liknar könsövertygelsesystem religioner eller sekter?",
      "Sätter skolor föräldrar åt sidan när barn fattar beslut om könsidentitet?",
      "Varför finns det så många ladyboys i Thailand?",
      "Varför är Iran ett globalt centrum för könskirurgi?",
    ],
  },
];
