/**
 * Indonesian question categories and featured questions for detrans.ai
 * 
 * Catatan Terminologi Terkait Gender:
 * - "Seks/Jenis Kelamin Biologis" = jenis kelamin biologis (anatomi, kromosom, reproduksi, karakteristik yang tidak dapat diubah)
 * - "Gender" = gender sosial (peran, perilaku, atribut yang dianggap sesuai oleh masyarakat
 *   untuk pria dan wanita berdasarkan jenis kelamin biologis mereka)
 * - "Identitas gender" = perasaan internal tentang menjadi laki-laki, perempuan, atau di antaranya
 * - "Ketidaksesuaian gender (GNC - Gender Non-Conformity)" = ketika seseorang bertindak/menampilkan diri berbeda dari harapan masyarakat
 *   berdasarkan jenis kelamin biologis mereka
 * - "AFAB/AMAB" = assigned female/male at birth (ditetapkan perempuan/laki-laki saat lahir) berdasarkan jenis kelamin biologis yang diamati
 * - "Transgender/trans" = mengidentifikasi diri dengan gender yang berbeda dari jenis kelamin biologis
 * - "Detransisi" = berhenti mengidentifikasi diri sebagai transgender dan/atau membalikkan langkah-langkah transisi
 * - "Desist" = ketika seseorang yang mengidentifikasi diri sebagai trans (tanpa intervensi medis) tidak lagi
 *   mengidentifikasi diri sebagai trans
 * 
 * Perbedaan penting: Konsep disforia gender bergantung pada pemahaman bahwa jenis kelamin biologis
 * dan gender sosial adalah berbeda. Ketidaksesuaian gender (tidak sesuai stereotip) adalah
 * berbeda dari memiliki identitas gender yang berbeda dari jenis kelamin biologis.
 */

export const questionCategories = [
  {
    title: "Pertanyaan Unggulan",
    description: "Pertanyaan terbaik untuk ditanyakan kepada orang detrans.",
    questions: [
      "Apa artinya trans?",
      "Apakah orang trans selalu ada?",
      "Benarkah hanya 1% yang detransisi?",
      "Apakah penghambat pubertas dapat dibalik?",
      "Bukti apa yang ada untuk protokol medis afirmasi gender?",
      "Apa artinya istilah 'egg' dalam komunitas trans?",
      "Apa implikasi dari narasi 'terlahir seperti ini'?",
      "Bagaimana label non-biner memperkuat stereotip gender tradisional?",
      "Apa perbedaan antara seks dan gender?",
      "Apa itu disforia gender dan apa yang menyebabkannya?",
      "Mengapa beberapa orang memutuskan untuk detransisi?",
      "Bagaimana teman atau keluarga dapat mendukung seseorang yang ingin transisi?",
      "Bagaimana teman atau keluarga dapat mendukung seseorang yang ingin detransisi?",
      "Apakah umum bagi detransitioner untuk menyesali transisi?",
      "Mengapa beberapa orang memutuskan untuk retransition setelah detransisi?",
      "Apa yang dapat dipelajari dari cerita detrans, bahkan jika transisi saya berjalan baik sejauh ini?",
      "Bagaimana saya tahu jika keraguan hanya kegelisahan atau tanda bahwa saya harus berhenti?",
      "Mengapa narasi trans tentang mengapa orang detransisi berbeda dari mereka yang sebenarnya telah detransisi?",
      "Apakah orang detrans berpikir transisi itu buruk?",
      "Klaim palsu apa yang dibuat tentang orang transgender?",
      "Klaim palsu apa yang dibuat tentang orang yang telah detransisi?",
      "Tanda-tanda awal apa yang diharapkan orang detrans telah mereka perhatikan lebih cepat?",
      "Apakah gender adalah konstruksi sosial? Apa artinya ini?",
      "Bagaimana gerakan feminis secara historis memandang konsep gender?",
      "Bagaimana ketidaksesuaian gender dapat mengurangi tekanan untuk sesuai dengan peran gender?",
      "Bagaimana orang detrans menggambarkan perasaan 'terlahir di tubuh yang salah'?",
      "Apa itu perawatan afirmasi gender dan apa tujuannya?",
      "Mengapa perawatan afirmasi gender biasanya menjadi satu-satunya pilihan di sebagian besar wilayah?",
      "Bagaimana terapi eksplorasi gender berbeda dari perawatan afirmasi gender?",
      "Mengapa beberapa orang tidak menyukai konsep terapi eksplorasi gender, dan mengapa itu dilarang di beberapa tempat?",
      "Apakah orang detrans berpikir perawatan afirmasi gender dan hormon harus dilarang?",
      "Apakah detransitioner biasanya menyesali langkah-langkah medis, langkah-langkah sosial, atau keduanya?",
      "Apa itu perangkap identitas dan bagaimana orang biasanya menyadari bahwa mereka berada di dalamnya?",
      "Di mana seseorang dapat mencari terapis yang menawarkan eksplorasi gender terbuka, non-direktif? Bendera merah apa yang harus saya waspadai?",
      "Apakah meminta kata ganti membantu atau menghambat orang yang tidak sesuai gender?",
      "Jika seorang gadis muda dengan rambut pendek terus-menerus ditanya kata gantinya, apa implikasinya dan bagaimana perasaannya?",
      "Apa itu budaya cancel dan efek apa yang dimilikinya pada diskursus kesehatan publik?",
      "Apakah orang detrans melihat transisi sebagai memiliki titik akhir atau sebagai proses yang berkelanjutan?",
      "Mengapa beberapa gadis remaja mungkin mengalami penderitaan tentang perkembangan payudara?",
      "Bagaimana ruang echo online dapat mempengaruhi pembentukan identitas?",
      "Mengapa detransitioner sering melaporkan merasa seperti cerita dan suara mereka dibungkam di ruang trans dan arus utama?",
      "Pola demografis apa yang terlihat dalam rujukan ke klinik gender?",
      "Bagaimana identitas queer kontemporer berbeda dari gerakan LGB sebelumnya?",
      "Apa yang dikatakan penelitian saat ini tentang tumpang tindih antara ciri-ciri spektrum autisme, disforia gender, dan identitas transgender?",
      "Mengapa disforia gender tidak lagi diklasifikasikan sebagai gangguan mental dalam DSM-5?",
      "Bagaimana prevalensi trans berubah dalam beberapa waktu terakhir dan apa yang mungkin menjelaskannya?",
    ],
  },
  {
    title: "Istilah Umum",
    description: "Memahami konsep-konsep fundamental",
    questions: [
      "Apa itu pria?",
      "Apa itu wanita?",
      "Apa itu gender?",
      "Apa itu disforia gender?",
      "Apa itu identitas transgender?",
      "Apa itu transfobia?",
      "Apa itu budaya cancel?",
      "Apa itu identitas non-biner?",
      "Apa itu identitas queer?",
      "Apa itu teori queer?",
      "Apa itu kepribadian?",
      "Bagaimana kepribadian berbeda dari identitas gender?",
      "Apa itu ketidaksesuaian gender (GNC)?",
      "Apa itu kesesuaian gender?",
      "Apa itu detransisi?",
      "Apa itu desisting (berhenti)?",
      "Apa itu kata ganti dan mengapa itu penting bagi beberapa orang?",
      "Apa yang dimaksud orang trans ketika berbicara tentang 'hak trans'?",
      "Mengapa beberapa orang trans mengatakan 'mati sebelum detransisi'?",
      "Faktor-faktor apa yang dianggap menyebabkan disforia?",
      "Apa itu 'gender dysphoria bible'?",
      "Strategi apa (medis atau non-medis) yang membantu orang mengelola disforia?",
      "Apakah orang interseks secara otomatis trans?",
      "Apa itu keluwesan gender?",
      "Apa artinya AFAB dan AMAB?",
      "Apa itu TERF?",
      "Apa itu deadnaming?",
      "Apa itu misgendering?",
      "Apa itu orang cisgender?",
      "Apa yang dimaksud dengan jenis kelamin biologis?",
      "Apa perbedaan antara transisi sosial dan transisi medis?",
    ],
  },
  {
    title: "Realitas Medis",
    description: "Kesehatan, prosedur, dan kebenaran biologis",
    questions: [
      "Apa efek samping penggunaan testosteron pada perempuan?",
      "Apa efek samping penggunaan estrogen pada laki-laki?",
      "Perubahan fisiologis apa yang dapat disebabkan testosteron pada perempuan dan apa batasannya?",
      "Perubahan fisiologis apa yang dapat disebabkan estrogen pada laki-laki dan apa batasannya?",
      "Apa yang dimaksud dengan phalloplasty dan apa hasil tipikalnya?",
      "Apa yang dimaksud dengan vaginoplasty dan apa hasil tipikalnya?",
      "Apa saja jenis operasi vaginoplasty yang berbeda?",
      "Bagaimana seseorang harus mempertimbangkan melanjutkan versus menghentikan hormon?",
      "Apakah ada perbedaan yang dapat diukur dalam tingkat diagnosis disforia gender antara laki-laki dan perempuan?",
      "Apa yang dikatakan penelitian pencitraan otak tentang otak 'laki-laki' versus 'perempuan'?",
      "Bagaimana disforia gender dibedakan dari penyakit mental dalam manual diagnostik?",
      "Apa itu atrofi vagina dan apa yang menyebabkannya?",
      "Pilihan revisi operasi apa yang ada untuk vaginoplasty atau phalloplasty?",
      "Bagaimana negara-negara berbeda mengatur pendanaan publik untuk operasi gender?",
      "Pilihan apa yang ada untuk rekonstruksi dada setelah mastektomi?",
      "Apa itu penghambat pubertas dan apakah mereka benar-benar hanya menghentikan pubertas?",
      "Benarkah bahwa penghambat pubertas adalah obat yang sama yang digunakan untuk kastrasi kimia pelaku kejahatan seksual?",
      "Data tindak lanjut jangka panjang apa yang ada untuk penggunaan hormon seks silang?",
      "Apa itu Standar Perawatan WPATH dan bagaimana pengembangannya?",
      "Apa itu Protokol Belanda?",
      "Apa itu disforia gender onset cepat (ROGD) dan bagaimana itu dipelajari?",
      "Apa tingkat penyesalan yang dilaporkan untuk berbagai operasi gender?",
      "Seperti apa terapi eksplorasi gender dalam praktik?",
    ],
  },
  {
    title: "Masyarakat & Budaya",
    description: "Bagaimana kepercayaan gender berinteraksi dengan dunia",
    questions: [
      "Apa implikasi dari narasi 'terlahir seperti ini'?",
      "Apakah identitas gender mengemas dan memperkuat kembali stereotip seksis?",
      "Bagaimana feminisme arus utama berubah dari waktu ke waktu untuk mengakomodasi identitas transgender?",
      "Bagaimana budaya kata ganti dapat menyebabkan over-medikalisasi anak-anak?",
      "Apa hasil yang didokumentasikan untuk anak-anak yang bertransisi sosial sejak dini?",
      "Apa hubungan antara BDSM dan identitas trans?",
      "Bagaimana konsep gender berevolusi secara historis?",
      "Bagaimana aktivisme trans berinteraksi dengan aktivisme hak gay sebelumnya?",
      "Bagaimana mantra atau slogan berulang mempengaruhi berpikir kritis dalam komunitas apa pun?",
      "Bagaimana diskursus gender kontemporer berpotongan dengan identitas gay dan lesbian?",
      "Apa yang bisa menjelaskan peningkatan identifikasi non-biner?",
      "Penjelasan apa yang ada untuk risiko bunuh diri yang lebih tinggi pada populasi trans?",
      "Bagaimana risiko bunuh diri yang dirasakan mempengaruhi diskursus publik tentang transisi?",
      "Apa artinya 'gender-kritis' dan bagaimana itu berbeda dari pandangan anti-trans?",
      "Apa 'perdebatan kamar mandi' dan bukti apa yang ada untuk bahaya atau keselamatan?",
      "Apa argumen utama dalam kontroversi partisipasi olahraga?",
      "Bagaimana sekolah menangani siswa yang mempertanyakan gender di berbagai yurisdiksi?",
      "Apa pendapat orang detrans tentang drag queen story telling?",
      "Apa artinya frasa 'medikalisasi anak-anak yang tidak sesuai gender' bagi para kritikus dan advokat?",
    ],
  },
  {
    title: "Psikologi & Identitas",
    description: "Memahami aspek mental dan emosional",
    questions: [
      "Bisakah seseorang menjadi wanita tanpa menjadi feminin, atau pria tanpa menjadi maskulin?",
      "Peran apa yang dimainkan media sosial dalam orang yang mengadopsi identitas gender?",
      "Apa itu siklus neurokimia validasi?",
      "Mengapa orang autis mungkin terlalu banyak diwakili di klinik gender?",
      "Apa itu misogini internalisasi dan bagaimana kaitannya dengan penderitaan tubuh?",
      "Apa itu homofobia internalisasi?",
      "Apa itu autogynephilia dan bagaimana itu diperdebatkan dalam literatur?",
      "Apa itu euforia gender?",
      "Bisakah mengadopsi identitas trans memperkuat disforia alih-alih meringankannya?",
      "Mengapa validasi eksternal penting bagi beberapa orang trans?",
      "Apa perbedaan antara gangguan dismorfik tubuh dan disforia gender?",
      "Paralel apa yang ditarik klinisi antara disforia gender dan gangguan makan?",
      "Bagaimana sejarah trauma dapat berinteraksi dengan disforia gender?",
      "Pilihan non-medis apa yang ada untuk mengelola disforia?",
      "Apa artinya 'passing' dan mengapa itu bisa menjadi obsesi bagi beberapa orang?",
      "Bagaimana konsep Jungian anima/animus berhubungan dengan identitas gender?",
      "Apa itu shadow work dan bisakah itu digunakan dalam terapi?",
    ],
  },
  {
    title: "Perjalanan Detransisi",
    description: "Penyembuhan, dukungan, dan menemukan jalan kembali",
    questions: [
      "Bagaimana saya bisa berdamai dengan perubahan permanen yang telah saya buat pada tubuh saya?",
      "Saya merasa beberapa orang berpikir saya baru saja 'kembali ke lemari' dan bahwa saya tidak hidup secara otentik",
      "Benarkah bahwa sebagian besar orang detrans akhirnya re-transition?",
      "Bagaimana transisi dan detransisi keduanya bisa menjadi bagian dari perjalanan penyembuhan yang sama?",
      "Di mana seseorang dapat menemukan terapis yang berpengalaman dalam dukungan detransisi?",
      "Apakah detransisi berarti transisi asli adalah kegagalan?",
      "Apakah CBT atau DBT telah membantu orang detrans dalam mengelola disforia?",
      "Mengapa beberapa komunitas trans menyarankan untuk tidak membaca narasi detransisi?",
      "Grup dukungan apa yang ada khusus untuk detransitioner?",
      "Bagaimana seseorang dapat keluar (lagi) ke keluarga sebagai detransisi?",
      "Tahapan berduka apa yang umum dilaporkan selama detransisi?",
      "Peran apa yang dimainkan obat psychedelic dalam beberapa cerita detrans?",
    ],
  },
  {
    title: "Bias Akademik & Penelitian",
    description: "Mempertanyakan narasi di institusi",
    questions: [
      "Kekhawatiran metodologis apa yang telah diajukan tentang survei detransisi utama?",
      "Mengapa peneliti melaporkan kesulitan mendapatkan pendanaan untuk studi detransisi?",
      "Apakah peneliti yang saat ini mengidentifikasi diri sebagai trans memiliki konflik kepentingan?",
      "Apa itu Tinjauan Cass dan rekomendasi apa yang dihasilkannya?",
      "Apa yang terjadi pada studi ROGD Lisa Littman tahun 2018?",
      "Apa itu tinjauan klinik Tavistock dan mengapa itu dipesan?",
      "Bagaimana disforia gender diklasifikasikan ulang antara DSM-IV dan DSM-5?",
    ],
  },
  {
    title: "Perspektif Kontroversial",
    description:
      "Perspektif detrans yang aktivis gender sangat tidak ingin Anda dengar",
    questions: [
      "Siapa yang menghasilkan uang dari perawatan afirmasi gender?",
      "Faktor-faktor struktural apa yang menyebabkan under-representasi cerita detransisi di media arus utama?",
      "Dalam hal apa sistem kepercayaan gender menyerupai agama atau kultus?",
      "Apakah sekolah mengesampingkan orang tua ketika anak-anak membuat pilihan tentang identitas gender?",
      "Mengapa ada begitu banyak ladyboys di Thailand?",
      "Mengapa Iran menjadi pusat global untuk operasi penggantian seks?",
    ],
  },
];
