export interface Video {
  id: string;
  title: string;
  author: string;
  type: "M" | "F";
  url: string;
}

export const videos: Video[] = [
  {
    id: "dxlRQAj2iZE",
    title: "Detrans: How I Ruined My Life",
    author: "Max Wayfarer",
    type: "M",
    url: "https://www.youtube.com/watch?v=dxlRQAj2iZE",
  },
  {
    id: "JxLAxhhZwGo",
    title:
      "Why Detransitioning After 25 Years Was the Most Healing Thing I Have Ever Done",
    author: "Call me sam",
    type: "M",
    url: "https://www.youtube.com/watch?v=JxLAxhhZwGo",
  },
  {
    id: "tk7NX7iPr9k",
    title: "Doctors Pushed Me into Surgery",
    author: "Ritchie Herron",
    type: "M",
    url: "https://www.youtube.com/watch?v=tk7NX7iPr9k",
  },
  {
    id: "Mu8ADnsy8yg",
    title: "Detrans: On the Spot Part 1",
    author: "Layla Jane",
    type: "F",
    url: "https://www.youtube.com/watch?v=Mu8ADnsy8yg",
  },
  {
    id: "WQ330Q3eykM",
    title: "Detransition | True Colors",
    author: "Euryale Enitan",
    type: "F",
    url: "https://www.youtube.com/watch?v=WQ330Q3eykM",
  },
  {
    id: "910JVOJSM2I",
    title: "The Detransition Diaries: Saving Our Sisters",
    author: "Helena, Cat, and Grace",
    type: "F",
    url: "https://www.youtube.com/watch?v=910JVOJSM2I",
  },
  {
    id: "GFeSifnxr",
    title: "Detrans: On the Spot Part 2",
    author: "Layla Jane",
    type: "F",
    url: "https://www.youtube.com/watch?v=GFeSifnxr-M",
  },
  {
    id: "T9UYDyqkH2E",
    title: "My Journey of Transition and Detransition",
    author: "placeswebreath",
    type: "F",
    url: "https://www.youtube.com/watch?v=T9UYDyqkH2E",
  },
  {
    id: "8msAX8FyfXs",
    title: "My Penis Is Gone Forever",
    author: "Alexander",
    type: "M",
    url: "https://www.youtube.com/watch?v=8msAX8FyfXs",
  },
  {
    id: "GfvJjWlF8Ss",
    title: "I Transitioned, Here's What Happened",
    author: "Maddy Edwards",
    type: "F",
    url: "https://www.youtube.com/watch?v=GfvJjWlF8Ss",
  },
  {
    id: "TyX6A4QxKgY",
    title: "The Cost of Transitioning - My Body Was Never the Problem",
    author: "Cat Cattinson",
    type: "F",
    url: "https://www.youtube.com/watch?v=TyX6A4QxKgY",
  },
  {
    id: "I5-9YnLP9pY",
    title: "The Detransitioned Male Experience",
    author: "Waffling Willow",
    type: "M",
    url: "https://www.youtube.com/watch?v=I5-9YnLP9pY",
  },
  {
    id: "CFqyW56P6-g",
    title: "Why I Transitioned and Detransitioned",
    author: "40daysofrain",
    type: "M",
    url: "https://www.youtube.com/watch?v=CFqyW56P6-g",
  },
  {
    id: "zFDQ2OKVZnk",
    title: "Detrans and Back - My Story",
    author: "Max M",
    type: "M",
    url: "https://www.youtube.com/watch?v=zFDQ2OKVZnk",
  },
  {
    id: "SaGaONkkEQs",
    title: "Detransitioning and Transhuman Dysphoria",
    author: "Courtney Coulson",
    type: "F",
    url: "https://www.youtube.com/watch?v=SaGaONkkEQs",
  },
  {
    id: "H3WyLd1fBrA",
    title: "Detransition & Betrayal: My Story",
    author: "Laura Becker",
    type: "F",
    url: "https://www.youtube.com/watch?v=H3WyLd1fBrA",
  },
  {
    id: "fDi-jFVBLA8",
    title: "Detransitioning: Reversing a Gender Transition - BBC Newsnight",
    author: "Debbie",
    type: "F",
    url: "https://www.youtube.com/watch?v=fDi-jFVBLA8",
  },
  {
    id: "3yvjFSX0TB0",
    title: "Detrans | Full Documentary | PragerU",
    author: "Daisy Strongin and Abel Garcia",
    type: "F",
    url: "https://www.youtube.com/watch?v=3yvjFSX0TB0",
  },
  {
    id: "iFYAN_fHYEQ",
    title: "The Tragic Aftermath of Joining the Trans Cult",
    author: "Matt Walsh with KC Miller",
    type: "F",
    url: "https://www.youtube.com/watch?v=iFYAN_fHYEQ",
  },
  {
    id: "Z98XFUfCI-Y",
    title: "Born in the Wrong Body, or Childhood Trauma?",
    author: "Transition Justice with Airiel Salvatore",
    type: "F",
    url: "https://www.youtube.com/watch?v=Z98XFUfCI-Y",
  },
  {
    id: "LHyTf2sjpW8",
    title: "Transition Harms Begin Long Before the Doctor's Office",
    author: "Transition Justice with Maia Poet",
    type: "F",
    url: "https://www.youtube.com/watch?v=LHyTf2sjpW8",
  },
  {
    id: "f1-mXiyuHPc",
    title:
      "Planned Parenthood Prescribed Her Testosterone for Transition. The Side Effects Could've Killed Her.",
    author: "Transition Justice with Kate Pond",
    type: "F",
    url: "https://www.youtube.com/watch?v=f1-mXiyuHPc",
  },
  {
    id: "tVXNeNFJsDA",
    title: "He Detransitioned. Now, the State Won't Allow Him to Change Back.",
    author: "Transition Justice with Levi Hayes",
    type: "M",
    url: "https://www.youtube.com/watch?v=tVXNeNFJsDA",
  },
  {
    id: "-64oiNs4YSc",
    title: "Think You're Trans? Think Again!",
    author: "Buck Angel and Jade",
    type: "F",
    url: "https://www.youtube.com/watch?v=-64oiNs4YSc",
  },
  {
    id: "Y9N6Y1XHLUk",
    title:
      "Detransition: School Indoctrination, Bullying, Testosterone Damage, and Healing",
    author: "Chloe Cole with Jade Martin",
    type: "F",
    url: "https://www.youtube.com/watch?v=Y9N6Y1XHLUk",
  },
  {
    id: "gZWslwe3W1c",
    title: "The Disruptive Reality of Child Transition",
    author: "Chloe Cole with Layla Jane",
    type: "F",
    url: "https://www.youtube.com/watch?v=gZWslwe3W1c",
  },
  {
    id: "tzdkPhTb7Yk",
    title:
      "Detransition: Surviving War-Torn Israel and Escaping Gender Ideology",
    author: "Chloe Cole with Maia Poet",
    type: "F",
    url: "https://www.youtube.com/watch?v=tzdkPhTb7Yk",
  },
  {
    id: "6O3MzPeomqs",
    title: "The Wounds That Won't Heal",
    author: "Jordan Peterson and Chloe Cole",
    type: "F",
    url: "https://www.youtube.com/watch?v=6O3MzPeomqs",
  },
  {
    id: "WtFZaPC3jPk",
    title: "I Should Never Have Transitioned",
    author: "Noah",
    type: "M",
    url: "https://www.youtube.com/watch?v=WtFZaPC3jPk",
  },
  {
    id: "gAYCQB8qFL4",
    title: "Identity Crisis: Breaking Free from the Transgender Contagion",
    author: "Simon Amaya Price",
    type: "M",
    url: "https://www.youtube.com/watch?v=gAYCQB8qFL4",
  },
  {
    id: "Fs5e6sOhLsE",
    title: "I Was a Trans Kid So You Don't Have to Be",
    author: "Unknown",
    type: "F",
    url: "https://www.youtube.com/watch?v=Fs5e6sOhLsE",
  },
  {
    id: "hBImcJz7-XA",
    title: "The Most Moving Detransition Story I've Ever Heard",
    author: "Jack Jewell Ft. Airiel D Salvatore",
    type: "M",
    url: "https://www.youtube.com/watch?v=hBImcJz7-XA",
  },
  {
    id: "rY5Et6FCOrc",
    title: "I Wouldn't Wish Detransition on Anyone",
    author: "Buck Angel and LaRell",
    type: "M",
    url: "https://www.youtube.com/watch?v=rY5Et6FCOrc",
  },
  {
    id: "KXCGi5tbGyk",
    title:
      "My Detransition Story: The Dark Truth Behind Gender Dysphoria and Regret",
    author: "Alexander L",
    type: "M",
    url: "https://www.youtube.com/watch?v=KXCGi5tbGyk",
  },
  {
    id: "mId-jsnjGLM",
    title: "Ex (Detransitioning) Trans Man Interview",
    author: "SoftWhiteUnderbelly featuring Laura",
    type: "M",
    url: "https://www.youtube.com/watch?v=mId-jsnjGLM",
  },
  {
    id: "SExy0BEcEtc",
    title: "Digital Influences on Trans Identities: A Detrans Perspective",
    author: "Soren Aldaco",
    type: "F",
    url: "https://www.youtube.com/watch?v=SExy0BEcEtc",
  },
  {
    id: "l5KvDjLqNxs",
    title: "Woke Doctors Gave Me Facial Hair & Low Voice Forever",
    author: "Keira Bell",
    type: "F",
    url: "https://www.youtube.com/watch?v=l5KvDjLqNxs",
  },
  {
    id: "DtItMuCW0vI",
    title: "Chloe Cole: 'I'm Still Recovering' from Hormones, Surgery at 15",
    author: "Chloe Cole",
    type: "F",
    url: "https://www.youtube.com/watch?v=DtItMuCW0vI",
  },
  {
    id: "efSpVYS8cXU",
    title: "Stunted by Transition | A Detrans Story",
    author: "Kobe",
    type: "M",
    url: "https://www.youtube.com/watch?v=efSpVYS8cXU",
  },
  {
    id: "fbwcz8_7exM",
    title: "My Detransition Story",
    author: "RattleThatAnimation",
    type: "F",
    url: "https://www.youtube.com/watch?v=fbwcz8_7exM",
  },
  {
    id: "KBkVhqgRz6U",
    title: "Hysterectomy, Double Mastectomy, and Deep Trans Regret at 24",
    author: "Katie Anderson",
    type: "F",
    url: "https://www.youtube.com/watch?v=KBkVhqgRz6U",
  },
  {
    id: "eWzXk9XRNHA",
    title:
      "He Transitioned, Regretted It, and Faced the Truth about Autogynephilia",
    author: "Beyond Gender with Ray",
    type: "M",
    url: "https://www.youtube.com/watch?v=eWzXk9XRNHA",
  },
  {
    id: "Mj9dImEgNqI",
    title: "Ramblings of a Detransitioned Woman",
    author: "Watson",
    type: "F",
    url: "https://www.youtube.com/watch?v=Mj9dImEgNqI",
  },
  {
    id: "24tSBRA6I4k",
    title:
      "Clementine Breen Sues Famous Gender Doctor, after Rushed Medical Transition",
    author: "Gender: A wider lens with Clementine Breen",
    type: "F",
    url: "https://www.youtube.com/watch?v=24tSBRA6I4k",
  },
  {
    id: "zRPRiElQ94c",
    title: "30 Years after Transition, Cori Cohn Speaks Out",
    author: "Beyond Gender with Cori Cohn",
    type: "M",
    url: "https://www.youtube.com/watch?v=zRPRiElQ94c",
  },
  {
    id: "MzkdqwL--oo",
    title: "Detransitioner Takes on Trans Activist",
    author: "Billboard Chris and Chloe Cole",
    type: "F",
    url: "https://www.youtube.com/watch?v=MzkdqwL--oo",
  },
  {
    id: "lWze94MzoDE",
    title: "The Dark Side of Gender Ideology, BDSM, and Detransition",
    author: "Beyond Gender with Victoria",
    type: "F",
    url: "https://www.youtube.com/watch?v=lWze94MzoDE",
  },
  {
    id: "uNyaoJn00Mo",
    title: "The Devastating Impact of Missing Puberty",
    author: "Beyond Gender with James Linehan ",
    type: "M",
    url: "https://www.youtube.com/watch?v=uNyaoJn00Mo",
  },
  {
    id: "QRW-jyCT5Y8",
    title: "The Dark Reality Behind 'Gender Affirming Care'",
    author: "Beyond Gender with Keira Bell",
    type: "F",
    url: "https://www.youtube.com/watch?v=QRW-jyCT5Y8",
  },
  {
    id: "6EFckKmYcgU",
    title: "I Was Thirteen When They Put Me on Estrogen",
    author: "Beyond Gender with Jonni Skinner",
    type: "M",
    url: "https://www.youtube.com/watch?v=6EFckKmYcgU",
  },
  {
    id: "Z2AIAX8-CqQ",
    title: "Female Transition & Detransition Timeline",
    author: "Elle",
    type: "F",
    url: "https://www.youtube.com/watch?v=Z2AIAX8-CqQ",
  },
  {
    id: "M0zWaNdkp7Y",
    title: "What the Hormones Didn't Solve",
    author: "Sinead",
    type: "F",
    url: "https://www.youtube.com/watch?v=M0zWaNdkp7Y",
  },
  {
    id: "7uJ2fwN32Eg",
    title: "Internalized Misogyny Led to My Transition",
    author: "Waffling Willow",
    type: "F",
    url: "https://www.youtube.com/watch?v=7uJ2fwN32Eg",
  },
  {
    id: "QpPc4fexROg",
    title: "Gender Transition Destroys Families",
    author: "Chloe Cole with Luke Healy",
    type: "M",
    url: "https://www.youtube.com/watch?v=QpPc4fexROg",
  },
  {
    id: "PqisKeHKPzs",
    title:
      "Detransitioner Interview: Botched Surgery, Regret, & the Social Contagion",
    author: "Shape",
    type: "M",
    url: "https://www.youtube.com/watch?v=PqisKeHKPzs",
  },
  {
    id: "QbXyyq1333I",
    title: "I Became Transgender. Here's Why I Regret It.",
    author: "Walt Heyer",
    type: "M",
    url: "https://www.youtube.com/watch?v=QbXyyq1333I",
  },
  {
    id: "LnbL74RJoYQ",
    title: "A Story of Detransition and the Journey That Followed",
    author: "Calvin Lunt",
    type: "M",
    url: "https://www.youtube.com/watch?v=LnbL74RJoYQ",
  },
  {
    id: "Vj3EXt4xiWU",
    title: "Confessions of a Woman Who Lived as a Man (A Detransition Story)",
    author: "Maddie Durbin",
    type: "F",
    url: "https://www.youtube.com/watch?v=Vj3EXt4xiWU",
  },
  {
    id: "B9krmEILsNQ",
    title: "Venus Rising with Mary: My Detransition Story",
    author: "Mary",
    type: "F",
    url: "https://www.youtube.com/watch?v=B9krmEILsNQ",
  },
  {
    id: "UT7GHTHl61M",
    title: "What Made Detransitioners Know Their Transition Was a Mistake",
    author: "Mary Margaret Olohan and Luka Hein",
    type: "F",
    url: "https://www.youtube.com/watch?v=UT7GHTHl61M",
  },
  {
    id: "_aGZat6fF1I",
    title: "'I Regret Trusting' the Doctors Who Pushed Me to Transition Gender",
    author: "Ritchie Herron",
    type: "M",
    url: "https://www.youtube.com/watch?v=_aGZat6fF1I",
  },
];
